// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch_jobs.sql

package db

import (
	"context"
	"database/sql"
)

const countBatchJobsByStatus = `-- name: CountBatchJobsByStatus :many
SELECT status, COUNT(*) as count FROM batch_jobs GROUP BY status
`

type CountBatchJobsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountBatchJobsByStatus(ctx context.Context) ([]CountBatchJobsByStatusRow, error) {
	rows, err := q.query(ctx, q.countBatchJobsByStatusStmt, countBatchJobsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountBatchJobsByStatusRow{}
	for rows.Next() {
		var i CountBatchJobsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatchJob = `-- name: GetBatchJob :one
SELECT id, file_path, status, error, paper_id, created_at, updated_at, attempt_count, max_attempts FROM batch_jobs WHERE id = ?
`

func (q *Queries) GetBatchJob(ctx context.Context, id string) (BatchJob, error) {
	row := q.queryRow(ctx, q.getBatchJobStmt, getBatchJob, id)
	var i BatchJob
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.Status,
		&i.Error,
		&i.PaperID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptCount,
		&i.MaxAttempts,
	)
	return i, err
}

const incrementBatchJobAttempt = `-- name: IncrementBatchJobAttempt :exec
UPDATE batch_jobs SET attempt_count = attempt_count + 1, updated_at = unixepoch() WHERE id = ?
`

func (q *Queries) IncrementBatchJobAttempt(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.incrementBatchJobAttemptStmt, incrementBatchJobAttempt, id)
	return err
}

const insertBatchJob = `-- name: InsertBatchJob :exec
INSERT INTO batch_jobs (id, file_path, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertBatchJobParams struct {
	ID        string `json:"id"`
	FilePath  string `json:"file_path"`
	Status    string `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) InsertBatchJob(ctx context.Context, arg InsertBatchJobParams) error {
	_, err := q.exec(ctx, q.insertBatchJobStmt, insertBatchJob,
		arg.ID,
		arg.FilePath,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listFailedBatchJobs = `-- name: ListFailedBatchJobs :many
SELECT id, file_path, status, error, paper_id, created_at, updated_at, attempt_count, max_attempts FROM batch_jobs WHERE status = 'failed' ORDER BY created_at LIMIT ?
`

func (q *Queries) ListFailedBatchJobs(ctx context.Context, limit int64) ([]BatchJob, error) {
	rows, err := q.query(ctx, q.listFailedBatchJobsStmt, listFailedBatchJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchJob{}
	for rows.Next() {
		var i BatchJob
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.Status,
			&i.Error,
			&i.PaperID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AttemptCount,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingBatchJobs = `-- name: ListPendingBatchJobs :many
SELECT id, file_path, status, error, paper_id, created_at, updated_at, attempt_count, max_attempts FROM batch_jobs WHERE status = 'pending' ORDER BY created_at LIMIT ?
`

func (q *Queries) ListPendingBatchJobs(ctx context.Context, limit int64) ([]BatchJob, error) {
	rows, err := q.query(ctx, q.listPendingBatchJobsStmt, listPendingBatchJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchJob{}
	for rows.Next() {
		var i BatchJob
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.Status,
			&i.Error,
			&i.PaperID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AttemptCount,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetBatchJobForRetry = `-- name: ResetBatchJobForRetry :exec
UPDATE batch_jobs SET status = 'pending', updated_at = unixepoch() WHERE id = ? AND attempt_count < max_attempts
`

func (q *Queries) ResetBatchJobForRetry(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.resetBatchJobForRetryStmt, resetBatchJobForRetry, id)
	return err
}

const resetFailedBatchJobs = `-- name: ResetFailedBatchJobs :exec
UPDATE batch_jobs SET status = 'pending', error = NULL, updated_at = ? WHERE status = 'failed'
`

func (q *Queries) ResetFailedBatchJobs(ctx context.Context, updatedAt int64) error {
	_, err := q.exec(ctx, q.resetFailedBatchJobsStmt, resetFailedBatchJobs, updatedAt)
	return err
}

const updateBatchJobStatus = `-- name: UpdateBatchJobStatus :exec
UPDATE batch_jobs SET status = ?, error = ?, paper_id = ?, updated_at = ? WHERE id = ?
`

type UpdateBatchJobStatusParams struct {
	Status    string         `json:"status"`
	Error     sql.NullString `json:"error"`
	PaperID   sql.NullString `json:"paper_id"`
	UpdatedAt int64          `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateBatchJobStatus(ctx context.Context, arg UpdateBatchJobStatusParams) error {
	_, err := q.exec(ctx, q.updateBatchJobStatusStmt, updateBatchJobStatus,
		arg.Status,
		arg.Error,
		arg.PaperID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
