// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bib_entries.sql

package db

import (
	"context"
	"database/sql"
)

const createBibEntry = `-- name: CreateBibEntry :exec
INSERT INTO bib_entries (
    id, session_id, title, authors, year, venue, abstract,
    doi, arxiv_id, semantic_scholar_id, cite_key, bib_type,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateBibEntryParams struct {
	ID                string         `json:"id"`
	SessionID         string         `json:"session_id"`
	Title             string         `json:"title"`
	Authors           string         `json:"authors"`
	Year              sql.NullInt64  `json:"year"`
	Venue             sql.NullString `json:"venue"`
	Abstract          sql.NullString `json:"abstract"`
	Doi               sql.NullString `json:"doi"`
	ArxivID           sql.NullString `json:"arxiv_id"`
	SemanticScholarID sql.NullString `json:"semantic_scholar_id"`
	CiteKey           string         `json:"cite_key"`
	BibType           string         `json:"bib_type"`
	CreatedAt         int64          `json:"created_at"`
	UpdatedAt         int64          `json:"updated_at"`
}

func (q *Queries) CreateBibEntry(ctx context.Context, arg CreateBibEntryParams) error {
	_, err := q.exec(ctx, q.createBibEntryStmt, createBibEntry,
		arg.ID,
		arg.SessionID,
		arg.Title,
		arg.Authors,
		arg.Year,
		arg.Venue,
		arg.Abstract,
		arg.Doi,
		arg.ArxivID,
		arg.SemanticScholarID,
		arg.CiteKey,
		arg.BibType,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteBibEntriesBySession = `-- name: DeleteBibEntriesBySession :exec
DELETE FROM bib_entries WHERE session_id = ?
`

func (q *Queries) DeleteBibEntriesBySession(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteBibEntriesBySessionStmt, deleteBibEntriesBySession, sessionID)
	return err
}

const deleteBibEntry = `-- name: DeleteBibEntry :exec
DELETE FROM bib_entries WHERE id = ?
`

func (q *Queries) DeleteBibEntry(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteBibEntryStmt, deleteBibEntry, id)
	return err
}

const getBibEntry = `-- name: GetBibEntry :one
SELECT id, session_id, title, authors, year, venue, abstract, doi, arxiv_id, semantic_scholar_id, cite_key, bib_type, created_at, updated_at FROM bib_entries WHERE id = ?
`

func (q *Queries) GetBibEntry(ctx context.Context, id string) (BibEntry, error) {
	row := q.queryRow(ctx, q.getBibEntryStmt, getBibEntry, id)
	var i BibEntry
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Title,
		&i.Authors,
		&i.Year,
		&i.Venue,
		&i.Abstract,
		&i.Doi,
		&i.ArxivID,
		&i.SemanticScholarID,
		&i.CiteKey,
		&i.BibType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBibEntryByCiteKey = `-- name: GetBibEntryByCiteKey :one
SELECT id, session_id, title, authors, year, venue, abstract, doi, arxiv_id, semantic_scholar_id, cite_key, bib_type, created_at, updated_at FROM bib_entries WHERE cite_key = ? AND session_id = ?
`

type GetBibEntryByCiteKeyParams struct {
	CiteKey   string `json:"cite_key"`
	SessionID string `json:"session_id"`
}

func (q *Queries) GetBibEntryByCiteKey(ctx context.Context, arg GetBibEntryByCiteKeyParams) (BibEntry, error) {
	row := q.queryRow(ctx, q.getBibEntryByCiteKeyStmt, getBibEntryByCiteKey, arg.CiteKey, arg.SessionID)
	var i BibEntry
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Title,
		&i.Authors,
		&i.Year,
		&i.Venue,
		&i.Abstract,
		&i.Doi,
		&i.ArxivID,
		&i.SemanticScholarID,
		&i.CiteKey,
		&i.BibType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBibEntryByDOI = `-- name: GetBibEntryByDOI :one
SELECT id, session_id, title, authors, year, venue, abstract, doi, arxiv_id, semantic_scholar_id, cite_key, bib_type, created_at, updated_at FROM bib_entries WHERE doi = ? AND session_id = ?
`

type GetBibEntryByDOIParams struct {
	Doi       sql.NullString `json:"doi"`
	SessionID string         `json:"session_id"`
}

func (q *Queries) GetBibEntryByDOI(ctx context.Context, arg GetBibEntryByDOIParams) (BibEntry, error) {
	row := q.queryRow(ctx, q.getBibEntryByDOIStmt, getBibEntryByDOI, arg.Doi, arg.SessionID)
	var i BibEntry
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Title,
		&i.Authors,
		&i.Year,
		&i.Venue,
		&i.Abstract,
		&i.Doi,
		&i.ArxivID,
		&i.SemanticScholarID,
		&i.CiteKey,
		&i.BibType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBibEntriesBySession = `-- name: ListBibEntriesBySession :many
SELECT id, session_id, title, authors, year, venue, abstract, doi, arxiv_id, semantic_scholar_id, cite_key, bib_type, created_at, updated_at FROM bib_entries WHERE session_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListBibEntriesBySession(ctx context.Context, sessionID string) ([]BibEntry, error) {
	rows, err := q.query(ctx, q.listBibEntriesBySessionStmt, listBibEntriesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BibEntry{}
	for rows.Next() {
		var i BibEntry
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Title,
			&i.Authors,
			&i.Year,
			&i.Venue,
			&i.Abstract,
			&i.Doi,
			&i.ArxivID,
			&i.SemanticScholarID,
			&i.CiteKey,
			&i.BibType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBibEntriesByTitle = `-- name: SearchBibEntriesByTitle :many
SELECT id, session_id, title, authors, year, venue, abstract, doi, arxiv_id, semantic_scholar_id, cite_key, bib_type, created_at, updated_at FROM bib_entries
WHERE session_id = ? AND title LIKE '%' || ? || '%'
ORDER BY year DESC
LIMIT ?
`

type SearchBibEntriesByTitleParams struct {
	SessionID string         `json:"session_id"`
	Column2   sql.NullString `json:"column_2"`
	Limit     int64          `json:"limit"`
}

func (q *Queries) SearchBibEntriesByTitle(ctx context.Context, arg SearchBibEntriesByTitleParams) ([]BibEntry, error) {
	rows, err := q.query(ctx, q.searchBibEntriesByTitleStmt, searchBibEntriesByTitle, arg.SessionID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BibEntry{}
	for rows.Next() {
		var i BibEntry
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Title,
			&i.Authors,
			&i.Year,
			&i.Venue,
			&i.Abstract,
			&i.Doi,
			&i.ArxivID,
			&i.SemanticScholarID,
			&i.CiteKey,
			&i.BibType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
