// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.backfillMessageSearchTextStmt, err = db.PrepareContext(ctx, backfillMessageSearchText); err != nil {
		return nil, fmt.Errorf("error preparing query BackfillMessageSearchText: %w", err)
	}
	if q.batchInsertPaperChunksStmt, err = db.PrepareContext(ctx, batchInsertPaperChunks); err != nil {
		return nil, fmt.Errorf("error preparing query BatchInsertPaperChunks: %w", err)
	}
	if q.cancelKBTaskStmt, err = db.PrepareContext(ctx, cancelKBTask); err != nil {
		return nil, fmt.Errorf("error preparing query CancelKBTask: %w", err)
	}
	if q.claimPendingKBTaskStmt, err = db.PrepareContext(ctx, claimPendingKBTask); err != nil {
		return nil, fmt.Errorf("error preparing query ClaimPendingKBTask: %w", err)
	}
	if q.claimPendingKBTaskByTypeStmt, err = db.PrepareContext(ctx, claimPendingKBTaskByType); err != nil {
		return nil, fmt.Errorf("error preparing query ClaimPendingKBTaskByType: %w", err)
	}
	if q.clearPaperChunksFTSStmt, err = db.PrepareContext(ctx, clearPaperChunksFTS); err != nil {
		return nil, fmt.Errorf("error preparing query ClearPaperChunksFTS: %w", err)
	}
	if q.completeKBTaskStmt, err = db.PrepareContext(ctx, completeKBTask); err != nil {
		return nil, fmt.Errorf("error preparing query CompleteKBTask: %w", err)
	}
	if q.countBatchJobsByStatusStmt, err = db.PrepareContext(ctx, countBatchJobsByStatus); err != nil {
		return nil, fmt.Errorf("error preparing query CountBatchJobsByStatus: %w", err)
	}
	if q.countKBUsageStatsStmt, err = db.PrepareContext(ctx, countKBUsageStats); err != nil {
		return nil, fmt.Errorf("error preparing query CountKBUsageStats: %w", err)
	}
	if q.countNodeContentsStmt, err = db.PrepareContext(ctx, countNodeContents); err != nil {
		return nil, fmt.Errorf("error preparing query CountNodeContents: %w", err)
	}
	if q.countNodeSummariesStmt, err = db.PrepareContext(ctx, countNodeSummaries); err != nil {
		return nil, fmt.Errorf("error preparing query CountNodeSummaries: %w", err)
	}
	if q.countPaperChunksStmt, err = db.PrepareContext(ctx, countPaperChunks); err != nil {
		return nil, fmt.Errorf("error preparing query CountPaperChunks: %w", err)
	}
	if q.countPaperIndexStatesByStatusStmt, err = db.PrepareContext(ctx, countPaperIndexStatesByStatus); err != nil {
		return nil, fmt.Errorf("error preparing query CountPaperIndexStatesByStatus: %w", err)
	}
	if q.countPapersStmt, err = db.PrepareContext(ctx, countPapers); err != nil {
		return nil, fmt.Errorf("error preparing query CountPapers: %w", err)
	}
	if q.createBibEntryStmt, err = db.PrepareContext(ctx, createBibEntry); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBibEntry: %w", err)
	}
	if q.createDocxDiagnosticStmt, err = db.PrepareContext(ctx, createDocxDiagnostic); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDocxDiagnostic: %w", err)
	}
	if q.createDocxDocumentStmt, err = db.PrepareContext(ctx, createDocxDocument); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDocxDocument: %w", err)
	}
	if q.createDocxExportStmt, err = db.PrepareContext(ctx, createDocxExport); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDocxExport: %w", err)
	}
	if q.createDocxMaterialStmt, err = db.PrepareContext(ctx, createDocxMaterial); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDocxMaterial: %w", err)
	}
	if q.createDocxVersionStmt, err = db.PrepareContext(ctx, createDocxVersion); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDocxVersion: %w", err)
	}
	if q.createFileStmt, err = db.PrepareContext(ctx, createFile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFile: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createPermissionRuleStmt, err = db.PrepareContext(ctx, createPermissionRule); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePermissionRule: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.deleteBibEntriesBySessionStmt, err = db.PrepareContext(ctx, deleteBibEntriesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBibEntriesBySession: %w", err)
	}
	if q.deleteBibEntryStmt, err = db.PrepareContext(ctx, deleteBibEntry); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBibEntry: %w", err)
	}
	if q.deleteDocxDiagnosticsByDocumentStmt, err = db.PrepareContext(ctx, deleteDocxDiagnosticsByDocument); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDocxDiagnosticsByDocument: %w", err)
	}
	if q.deleteFileStmt, err = db.PrepareContext(ctx, deleteFile); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFile: %w", err)
	}
	if q.deleteMemoryItemStmt, err = db.PrepareContext(ctx, deleteMemoryItem); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMemoryItem: %w", err)
	}
	if q.deleteMessageStmt, err = db.PrepareContext(ctx, deleteMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessage: %w", err)
	}
	if q.deleteNodeContentsStmt, err = db.PrepareContext(ctx, deleteNodeContents); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteNodeContents: %w", err)
	}
	if q.deleteNodeSummariesStmt, err = db.PrepareContext(ctx, deleteNodeSummaries); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteNodeSummaries: %w", err)
	}
	if q.deletePaperStmt, err = db.PrepareContext(ctx, deletePaper); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePaper: %w", err)
	}
	if q.deletePaperChunksStmt, err = db.PrepareContext(ctx, deletePaperChunks); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePaperChunks: %w", err)
	}
	if q.deletePaperChunksFTSForPaperStmt, err = db.PrepareContext(ctx, deletePaperChunksFTSForPaper); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePaperChunksFTSForPaper: %w", err)
	}
	if q.deletePaperTreeStmt, err = db.PrepareContext(ctx, deletePaperTree); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePaperTree: %w", err)
	}
	if q.deletePermissionRuleStmt, err = db.PrepareContext(ctx, deletePermissionRule); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePermissionRule: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.deleteSessionMessagesStmt, err = db.PrepareContext(ctx, deleteSessionMessages); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionMessages: %w", err)
	}
	if q.deleteSessionPermissionsStmt, err = db.PrepareContext(ctx, deleteSessionPermissions); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionPermissions: %w", err)
	}
	if q.enqueueKBTaskStmt, err = db.PrepareContext(ctx, enqueueKBTask); err != nil {
		return nil, fmt.Errorf("error preparing query EnqueueKBTask: %w", err)
	}
	if q.failKBTaskStmt, err = db.PrepareContext(ctx, failKBTask); err != nil {
		return nil, fmt.Errorf("error preparing query FailKBTask: %w", err)
	}
	if q.forceRequeueKBTaskStmt, err = db.PrepareContext(ctx, forceRequeueKBTask); err != nil {
		return nil, fmt.Errorf("error preparing query ForceRequeueKBTask: %w", err)
	}
	if q.getBatchJobStmt, err = db.PrepareContext(ctx, getBatchJob); err != nil {
		return nil, fmt.Errorf("error preparing query GetBatchJob: %w", err)
	}
	if q.getBibEntryStmt, err = db.PrepareContext(ctx, getBibEntry); err != nil {
		return nil, fmt.Errorf("error preparing query GetBibEntry: %w", err)
	}
	if q.getBibEntryByCiteKeyStmt, err = db.PrepareContext(ctx, getBibEntryByCiteKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetBibEntryByCiteKey: %w", err)
	}
	if q.getBibEntryByDOIStmt, err = db.PrepareContext(ctx, getBibEntryByDOI); err != nil {
		return nil, fmt.Errorf("error preparing query GetBibEntryByDOI: %w", err)
	}
	if q.getDocxDocumentStmt, err = db.PrepareContext(ctx, getDocxDocument); err != nil {
		return nil, fmt.Errorf("error preparing query GetDocxDocument: %w", err)
	}
	if q.getFileStmt, err = db.PrepareContext(ctx, getFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetFile: %w", err)
	}
	if q.getFileByPathStmt, err = db.PrepareContext(ctx, getFileByPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileByPath: %w", err)
	}
	if q.getKBTaskStmt, err = db.PrepareContext(ctx, getKBTask); err != nil {
		return nil, fmt.Errorf("error preparing query GetKBTask: %w", err)
	}
	if q.getMemoryItemStmt, err = db.PrepareContext(ctx, getMemoryItem); err != nil {
		return nil, fmt.Errorf("error preparing query GetMemoryItem: %w", err)
	}
	if q.getMemorySkillStatsStmt, err = db.PrepareContext(ctx, getMemorySkillStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetMemorySkillStats: %w", err)
	}
	if q.getMessageStmt, err = db.PrepareContext(ctx, getMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessage: %w", err)
	}
	if q.getNodeContentStmt, err = db.PrepareContext(ctx, getNodeContent); err != nil {
		return nil, fmt.Errorf("error preparing query GetNodeContent: %w", err)
	}
	if q.getNodeContentsStmt, err = db.PrepareContext(ctx, getNodeContents); err != nil {
		return nil, fmt.Errorf("error preparing query GetNodeContents: %w", err)
	}
	if q.getNodeSummariesStmt, err = db.PrepareContext(ctx, getNodeSummaries); err != nil {
		return nil, fmt.Errorf("error preparing query GetNodeSummaries: %w", err)
	}
	if q.getNodeSummaryStmt, err = db.PrepareContext(ctx, getNodeSummary); err != nil {
		return nil, fmt.Errorf("error preparing query GetNodeSummary: %w", err)
	}
	if q.getPaperStmt, err = db.PrepareContext(ctx, getPaper); err != nil {
		return nil, fmt.Errorf("error preparing query GetPaper: %w", err)
	}
	if q.getPaperByArxivIDStmt, err = db.PrepareContext(ctx, getPaperByArxivID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPaperByArxivID: %w", err)
	}
	if q.getPaperByDOIStmt, err = db.PrepareContext(ctx, getPaperByDOI); err != nil {
		return nil, fmt.Errorf("error preparing query GetPaperByDOI: %w", err)
	}
	if q.getPaperByFilePathStmt, err = db.PrepareContext(ctx, getPaperByFilePath); err != nil {
		return nil, fmt.Errorf("error preparing query GetPaperByFilePath: %w", err)
	}
	if q.getPaperChunkStmt, err = db.PrepareContext(ctx, getPaperChunk); err != nil {
		return nil, fmt.Errorf("error preparing query GetPaperChunk: %w", err)
	}
	if q.getPaperChunksStmt, err = db.PrepareContext(ctx, getPaperChunks); err != nil {
		return nil, fmt.Errorf("error preparing query GetPaperChunks: %w", err)
	}
	if q.getPaperIndexStateStmt, err = db.PrepareContext(ctx, getPaperIndexState); err != nil {
		return nil, fmt.Errorf("error preparing query GetPaperIndexState: %w", err)
	}
	if q.getPaperRelationsStmt, err = db.PrepareContext(ctx, getPaperRelations); err != nil {
		return nil, fmt.Errorf("error preparing query GetPaperRelations: %w", err)
	}
	if q.getPaperTreeStmt, err = db.PrepareContext(ctx, getPaperTree); err != nil {
		return nil, fmt.Errorf("error preparing query GetPaperTree: %w", err)
	}
	if q.getPermissionRuleStmt, err = db.PrepareContext(ctx, getPermissionRule); err != nil {
		return nil, fmt.Errorf("error preparing query GetPermissionRule: %w", err)
	}
	if q.getSessionByIDStmt, err = db.PrepareContext(ctx, getSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByID: %w", err)
	}
	if q.getTopAccessedPapersStmt, err = db.PrepareContext(ctx, getTopAccessedPapers); err != nil {
		return nil, fmt.Errorf("error preparing query GetTopAccessedPapers: %w", err)
	}
	if q.incrementBatchJobAttemptStmt, err = db.PrepareContext(ctx, incrementBatchJobAttempt); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementBatchJobAttempt: %w", err)
	}
	if q.incrementMemoryAccessCountStmt, err = db.PrepareContext(ctx, incrementMemoryAccessCount); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementMemoryAccessCount: %w", err)
	}
	if q.insertBatchJobStmt, err = db.PrepareContext(ctx, insertBatchJob); err != nil {
		return nil, fmt.Errorf("error preparing query InsertBatchJob: %w", err)
	}
	if q.insertKBTaskStmt, err = db.PrepareContext(ctx, insertKBTask); err != nil {
		return nil, fmt.Errorf("error preparing query InsertKBTask: %w", err)
	}
	if q.insertMemoryItemStmt, err = db.PrepareContext(ctx, insertMemoryItem); err != nil {
		return nil, fmt.Errorf("error preparing query InsertMemoryItem: %w", err)
	}
	if q.insertNodeContentStmt, err = db.PrepareContext(ctx, insertNodeContent); err != nil {
		return nil, fmt.Errorf("error preparing query InsertNodeContent: %w", err)
	}
	if q.insertNodeSummaryStmt, err = db.PrepareContext(ctx, insertNodeSummary); err != nil {
		return nil, fmt.Errorf("error preparing query InsertNodeSummary: %w", err)
	}
	if q.insertPaperStmt, err = db.PrepareContext(ctx, insertPaper); err != nil {
		return nil, fmt.Errorf("error preparing query InsertPaper: %w", err)
	}
	if q.insertPaperChunkStmt, err = db.PrepareContext(ctx, insertPaperChunk); err != nil {
		return nil, fmt.Errorf("error preparing query InsertPaperChunk: %w", err)
	}
	if q.insertPaperTreeStmt, err = db.PrepareContext(ctx, insertPaperTree); err != nil {
		return nil, fmt.Errorf("error preparing query InsertPaperTree: %w", err)
	}
	if q.insertResearchTopicStmt, err = db.PrepareContext(ctx, insertResearchTopic); err != nil {
		return nil, fmt.Errorf("error preparing query InsertResearchTopic: %w", err)
	}
	if q.insertUsageStatStmt, err = db.PrepareContext(ctx, insertUsageStat); err != nil {
		return nil, fmt.Errorf("error preparing query InsertUsageStat: %w", err)
	}
	if q.listBibEntriesBySessionStmt, err = db.PrepareContext(ctx, listBibEntriesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListBibEntriesBySession: %w", err)
	}
	if q.listDocxDiagnosticsStmt, err = db.PrepareContext(ctx, listDocxDiagnostics); err != nil {
		return nil, fmt.Errorf("error preparing query ListDocxDiagnostics: %w", err)
	}
	if q.listDocxDocumentsByPipelineStmt, err = db.PrepareContext(ctx, listDocxDocumentsByPipeline); err != nil {
		return nil, fmt.Errorf("error preparing query ListDocxDocumentsByPipeline: %w", err)
	}
	if q.listDocxExportsStmt, err = db.PrepareContext(ctx, listDocxExports); err != nil {
		return nil, fmt.Errorf("error preparing query ListDocxExports: %w", err)
	}
	if q.listDocxMaterialsStmt, err = db.PrepareContext(ctx, listDocxMaterials); err != nil {
		return nil, fmt.Errorf("error preparing query ListDocxMaterials: %w", err)
	}
	if q.listDocxVersionsStmt, err = db.PrepareContext(ctx, listDocxVersions); err != nil {
		return nil, fmt.Errorf("error preparing query ListDocxVersions: %w", err)
	}
	if q.listFailedBatchJobsStmt, err = db.PrepareContext(ctx, listFailedBatchJobs); err != nil {
		return nil, fmt.Errorf("error preparing query ListFailedBatchJobs: %w", err)
	}
	if q.listFilesBySessionStmt, err = db.PrepareContext(ctx, listFilesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesBySession: %w", err)
	}
	if q.listGlobalMemoryItemsStmt, err = db.PrepareContext(ctx, listGlobalMemoryItems); err != nil {
		return nil, fmt.Errorf("error preparing query ListGlobalMemoryItems: %w", err)
	}
	if q.listKBTasksByPaperStmt, err = db.PrepareContext(ctx, listKBTasksByPaper); err != nil {
		return nil, fmt.Errorf("error preparing query ListKBTasksByPaper: %w", err)
	}
	if q.listMemoryItemsForSessionStmt, err = db.PrepareContext(ctx, listMemoryItemsForSession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMemoryItemsForSession: %w", err)
	}
	if q.listMessagesBySessionStmt, err = db.PrepareContext(ctx, listMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySession: %w", err)
	}
	if q.listMessagesMissingSearchTextStmt, err = db.PrepareContext(ctx, listMessagesMissingSearchText); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesMissingSearchText: %w", err)
	}
	if q.listMessagesMissingSearchTextForResumeSearchStmt, err = db.PrepareContext(ctx, listMessagesMissingSearchTextForResumeSearch); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesMissingSearchTextForResumeSearch: %w", err)
	}
	if q.listPaperIndexStatesStmt, err = db.PrepareContext(ctx, listPaperIndexStates); err != nil {
		return nil, fmt.Errorf("error preparing query ListPaperIndexStates: %w", err)
	}
	if q.listPapersStmt, err = db.PrepareContext(ctx, listPapers); err != nil {
		return nil, fmt.Errorf("error preparing query ListPapers: %w", err)
	}
	if q.listPapersWithIndexStateAndTaskStmt, err = db.PrepareContext(ctx, listPapersWithIndexStateAndTask); err != nil {
		return nil, fmt.Errorf("error preparing query ListPapersWithIndexStateAndTask: %w", err)
	}
	if q.listPendingBatchJobsStmt, err = db.PrepareContext(ctx, listPendingBatchJobs); err != nil {
		return nil, fmt.Errorf("error preparing query ListPendingBatchJobs: %w", err)
	}
	if q.listPendingKBTasksStmt, err = db.PrepareContext(ctx, listPendingKBTasks); err != nil {
		return nil, fmt.Errorf("error preparing query ListPendingKBTasks: %w", err)
	}
	if q.listPermissionRulesStmt, err = db.PrepareContext(ctx, listPermissionRules); err != nil {
		return nil, fmt.Errorf("error preparing query ListPermissionRules: %w", err)
	}
	if q.listRecentMemoryItemsStmt, err = db.PrepareContext(ctx, listRecentMemoryItems); err != nil {
		return nil, fmt.Errorf("error preparing query ListRecentMemoryItems: %w", err)
	}
	if q.listResearchTopicsStmt, err = db.PrepareContext(ctx, listResearchTopics); err != nil {
		return nil, fmt.Errorf("error preparing query ListResearchTopics: %w", err)
	}
	if q.listSessionMemoryItemsStmt, err = db.PrepareContext(ctx, listSessionMemoryItems); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionMemoryItems: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.listSessionsForResumeStmt, err = db.PrepareContext(ctx, listSessionsForResume); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionsForResume: %w", err)
	}
	if q.rebuildPaperChunksFTSStmt, err = db.PrepareContext(ctx, rebuildPaperChunksFTS); err != nil {
		return nil, fmt.Errorf("error preparing query RebuildPaperChunksFTS: %w", err)
	}
	if q.rebuildPaperChunksFTSForPaperStmt, err = db.PrepareContext(ctx, rebuildPaperChunksFTSForPaper); err != nil {
		return nil, fmt.Errorf("error preparing query RebuildPaperChunksFTSForPaper: %w", err)
	}
	if q.resetBatchJobForRetryStmt, err = db.PrepareContext(ctx, resetBatchJobForRetry); err != nil {
		return nil, fmt.Errorf("error preparing query ResetBatchJobForRetry: %w", err)
	}
	if q.resetFailedBatchJobsStmt, err = db.PrepareContext(ctx, resetFailedBatchJobs); err != nil {
		return nil, fmt.Errorf("error preparing query ResetFailedBatchJobs: %w", err)
	}
	if q.resolveSessionByExactTitleStmt, err = db.PrepareContext(ctx, resolveSessionByExactTitle); err != nil {
		return nil, fmt.Errorf("error preparing query ResolveSessionByExactTitle: %w", err)
	}
	if q.retryKBTaskStmt, err = db.PrepareContext(ctx, retryKBTask); err != nil {
		return nil, fmt.Errorf("error preparing query RetryKBTask: %w", err)
	}
	if q.searchAllPaperChunksStmt, err = db.PrepareContext(ctx, searchAllPaperChunks); err != nil {
		return nil, fmt.Errorf("error preparing query SearchAllPaperChunks: %w", err)
	}
	if q.searchBibEntriesByTitleStmt, err = db.PrepareContext(ctx, searchBibEntriesByTitle); err != nil {
		return nil, fmt.Errorf("error preparing query SearchBibEntriesByTitle: %w", err)
	}
	if q.searchNodeContentsStmt, err = db.PrepareContext(ctx, searchNodeContents); err != nil {
		return nil, fmt.Errorf("error preparing query SearchNodeContents: %w", err)
	}
	if q.searchNodeSummariesStmt, err = db.PrepareContext(ctx, searchNodeSummaries); err != nil {
		return nil, fmt.Errorf("error preparing query SearchNodeSummaries: %w", err)
	}
	if q.searchPaperChunksStmt, err = db.PrepareContext(ctx, searchPaperChunks); err != nil {
		return nil, fmt.Errorf("error preparing query SearchPaperChunks: %w", err)
	}
	if q.searchPapersByTitleStmt, err = db.PrepareContext(ctx, searchPapersByTitle); err != nil {
		return nil, fmt.Errorf("error preparing query SearchPapersByTitle: %w", err)
	}
	if q.searchRootSessionsByMessageFTSStmt, err = db.PrepareContext(ctx, searchRootSessionsByMessageFTS); err != nil {
		return nil, fmt.Errorf("error preparing query SearchRootSessionsByMessageFTS: %w", err)
	}
	if q.searchSessionsByMetadataStmt, err = db.PrepareContext(ctx, searchSessionsByMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query SearchSessionsByMetadata: %w", err)
	}
	if q.sumPaperChunkBytesStmt, err = db.PrepareContext(ctx, sumPaperChunkBytes); err != nil {
		return nil, fmt.Errorf("error preparing query SumPaperChunkBytes: %w", err)
	}
	if q.updateBatchJobStatusStmt, err = db.PrepareContext(ctx, updateBatchJobStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBatchJobStatus: %w", err)
	}
	if q.updateDocxDocumentStateStmt, err = db.PrepareContext(ctx, updateDocxDocumentState); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDocxDocumentState: %w", err)
	}
	if q.updateDocxMaterialParsedStmt, err = db.PrepareContext(ctx, updateDocxMaterialParsed); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDocxMaterialParsed: %w", err)
	}
	if q.updateFTSStateStmt, err = db.PrepareContext(ctx, updateFTSState); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateFTSState: %w", err)
	}
	if q.updateKBTaskProgressStmt, err = db.PrepareContext(ctx, updateKBTaskProgress); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateKBTaskProgress: %w", err)
	}
	if q.updateMemoryItemStmt, err = db.PrepareContext(ctx, updateMemoryItem); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMemoryItem: %w", err)
	}
	if q.updateMessageStmt, err = db.PrepareContext(ctx, updateMessage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessage: %w", err)
	}
	if q.updatePaperTreeVersionStmt, err = db.PrepareContext(ctx, updatePaperTreeVersion); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePaperTreeVersion: %w", err)
	}
	if q.updateRawParseStateStmt, err = db.PrepareContext(ctx, updateRawParseState); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateRawParseState: %w", err)
	}
	if q.updateSemanticTreeStateStmt, err = db.PrepareContext(ctx, updateSemanticTreeState); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSemanticTreeState: %w", err)
	}
	if q.updateSessionStmt, err = db.PrepareContext(ctx, updateSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSession: %w", err)
	}
	if q.upsertMemorySkillStatStmt, err = db.PrepareContext(ctx, upsertMemorySkillStat); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertMemorySkillStat: %w", err)
	}
	if q.upsertPaperIndexStateStmt, err = db.PrepareContext(ctx, upsertPaperIndexState); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertPaperIndexState: %w", err)
	}
	if q.upsertPaperRelationStmt, err = db.PrepareContext(ctx, upsertPaperRelation); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertPaperRelation: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.backfillMessageSearchTextStmt != nil {
		if cerr := q.backfillMessageSearchTextStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing backfillMessageSearchTextStmt: %w", cerr)
		}
	}
	if q.batchInsertPaperChunksStmt != nil {
		if cerr := q.batchInsertPaperChunksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing batchInsertPaperChunksStmt: %w", cerr)
		}
	}
	if q.cancelKBTaskStmt != nil {
		if cerr := q.cancelKBTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cancelKBTaskStmt: %w", cerr)
		}
	}
	if q.claimPendingKBTaskStmt != nil {
		if cerr := q.claimPendingKBTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing claimPendingKBTaskStmt: %w", cerr)
		}
	}
	if q.claimPendingKBTaskByTypeStmt != nil {
		if cerr := q.claimPendingKBTaskByTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing claimPendingKBTaskByTypeStmt: %w", cerr)
		}
	}
	if q.clearPaperChunksFTSStmt != nil {
		if cerr := q.clearPaperChunksFTSStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearPaperChunksFTSStmt: %w", cerr)
		}
	}
	if q.completeKBTaskStmt != nil {
		if cerr := q.completeKBTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing completeKBTaskStmt: %w", cerr)
		}
	}
	if q.countBatchJobsByStatusStmt != nil {
		if cerr := q.countBatchJobsByStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countBatchJobsByStatusStmt: %w", cerr)
		}
	}
	if q.countKBUsageStatsStmt != nil {
		if cerr := q.countKBUsageStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countKBUsageStatsStmt: %w", cerr)
		}
	}
	if q.countNodeContentsStmt != nil {
		if cerr := q.countNodeContentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countNodeContentsStmt: %w", cerr)
		}
	}
	if q.countNodeSummariesStmt != nil {
		if cerr := q.countNodeSummariesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countNodeSummariesStmt: %w", cerr)
		}
	}
	if q.countPaperChunksStmt != nil {
		if cerr := q.countPaperChunksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countPaperChunksStmt: %w", cerr)
		}
	}
	if q.countPaperIndexStatesByStatusStmt != nil {
		if cerr := q.countPaperIndexStatesByStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countPaperIndexStatesByStatusStmt: %w", cerr)
		}
	}
	if q.countPapersStmt != nil {
		if cerr := q.countPapersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countPapersStmt: %w", cerr)
		}
	}
	if q.createBibEntryStmt != nil {
		if cerr := q.createBibEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBibEntryStmt: %w", cerr)
		}
	}
	if q.createDocxDiagnosticStmt != nil {
		if cerr := q.createDocxDiagnosticStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDocxDiagnosticStmt: %w", cerr)
		}
	}
	if q.createDocxDocumentStmt != nil {
		if cerr := q.createDocxDocumentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDocxDocumentStmt: %w", cerr)
		}
	}
	if q.createDocxExportStmt != nil {
		if cerr := q.createDocxExportStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDocxExportStmt: %w", cerr)
		}
	}
	if q.createDocxMaterialStmt != nil {
		if cerr := q.createDocxMaterialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDocxMaterialStmt: %w", cerr)
		}
	}
	if q.createDocxVersionStmt != nil {
		if cerr := q.createDocxVersionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDocxVersionStmt: %w", cerr)
		}
	}
	if q.createFileStmt != nil {
		if cerr := q.createFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFileStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createPermissionRuleStmt != nil {
		if cerr := q.createPermissionRuleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPermissionRuleStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.deleteBibEntriesBySessionStmt != nil {
		if cerr := q.deleteBibEntriesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBibEntriesBySessionStmt: %w", cerr)
		}
	}
	if q.deleteBibEntryStmt != nil {
		if cerr := q.deleteBibEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBibEntryStmt: %w", cerr)
		}
	}
	if q.deleteDocxDiagnosticsByDocumentStmt != nil {
		if cerr := q.deleteDocxDiagnosticsByDocumentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDocxDiagnosticsByDocumentStmt: %w", cerr)
		}
	}
	if q.deleteFileStmt != nil {
		if cerr := q.deleteFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFileStmt: %w", cerr)
		}
	}
	if q.deleteMemoryItemStmt != nil {
		if cerr := q.deleteMemoryItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMemoryItemStmt: %w", cerr)
		}
	}
	if q.deleteMessageStmt != nil {
		if cerr := q.deleteMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageStmt: %w", cerr)
		}
	}
	if q.deleteNodeContentsStmt != nil {
		if cerr := q.deleteNodeContentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteNodeContentsStmt: %w", cerr)
		}
	}
	if q.deleteNodeSummariesStmt != nil {
		if cerr := q.deleteNodeSummariesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteNodeSummariesStmt: %w", cerr)
		}
	}
	if q.deletePaperStmt != nil {
		if cerr := q.deletePaperStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePaperStmt: %w", cerr)
		}
	}
	if q.deletePaperChunksStmt != nil {
		if cerr := q.deletePaperChunksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePaperChunksStmt: %w", cerr)
		}
	}
	if q.deletePaperChunksFTSForPaperStmt != nil {
		if cerr := q.deletePaperChunksFTSForPaperStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePaperChunksFTSForPaperStmt: %w", cerr)
		}
	}
	if q.deletePaperTreeStmt != nil {
		if cerr := q.deletePaperTreeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePaperTreeStmt: %w", cerr)
		}
	}
	if q.deletePermissionRuleStmt != nil {
		if cerr := q.deletePermissionRuleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePermissionRuleStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionMessagesStmt != nil {
		if cerr := q.deleteSessionMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionMessagesStmt: %w", cerr)
		}
	}
	if q.deleteSessionPermissionsStmt != nil {
		if cerr := q.deleteSessionPermissionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionPermissionsStmt: %w", cerr)
		}
	}
	if q.enqueueKBTaskStmt != nil {
		if cerr := q.enqueueKBTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing enqueueKBTaskStmt: %w", cerr)
		}
	}
	if q.failKBTaskStmt != nil {
		if cerr := q.failKBTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing failKBTaskStmt: %w", cerr)
		}
	}
	if q.forceRequeueKBTaskStmt != nil {
		if cerr := q.forceRequeueKBTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing forceRequeueKBTaskStmt: %w", cerr)
		}
	}
	if q.getBatchJobStmt != nil {
		if cerr := q.getBatchJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBatchJobStmt: %w", cerr)
		}
	}
	if q.getBibEntryStmt != nil {
		if cerr := q.getBibEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBibEntryStmt: %w", cerr)
		}
	}
	if q.getBibEntryByCiteKeyStmt != nil {
		if cerr := q.getBibEntryByCiteKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBibEntryByCiteKeyStmt: %w", cerr)
		}
	}
	if q.getBibEntryByDOIStmt != nil {
		if cerr := q.getBibEntryByDOIStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBibEntryByDOIStmt: %w", cerr)
		}
	}
	if q.getDocxDocumentStmt != nil {
		if cerr := q.getDocxDocumentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDocxDocumentStmt: %w", cerr)
		}
	}
	if q.getFileStmt != nil {
		if cerr := q.getFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileStmt: %w", cerr)
		}
	}
	if q.getFileByPathStmt != nil {
		if cerr := q.getFileByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileByPathStmt: %w", cerr)
		}
	}
	if q.getKBTaskStmt != nil {
		if cerr := q.getKBTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getKBTaskStmt: %w", cerr)
		}
	}
	if q.getMemoryItemStmt != nil {
		if cerr := q.getMemoryItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMemoryItemStmt: %w", cerr)
		}
	}
	if q.getMemorySkillStatsStmt != nil {
		if cerr := q.getMemorySkillStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMemorySkillStatsStmt: %w", cerr)
		}
	}
	if q.getMessageStmt != nil {
		if cerr := q.getMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageStmt: %w", cerr)
		}
	}
	if q.getNodeContentStmt != nil {
		if cerr := q.getNodeContentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNodeContentStmt: %w", cerr)
		}
	}
	if q.getNodeContentsStmt != nil {
		if cerr := q.getNodeContentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNodeContentsStmt: %w", cerr)
		}
	}
	if q.getNodeSummariesStmt != nil {
		if cerr := q.getNodeSummariesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNodeSummariesStmt: %w", cerr)
		}
	}
	if q.getNodeSummaryStmt != nil {
		if cerr := q.getNodeSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNodeSummaryStmt: %w", cerr)
		}
	}
	if q.getPaperStmt != nil {
		if cerr := q.getPaperStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPaperStmt: %w", cerr)
		}
	}
	if q.getPaperByArxivIDStmt != nil {
		if cerr := q.getPaperByArxivIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPaperByArxivIDStmt: %w", cerr)
		}
	}
	if q.getPaperByDOIStmt != nil {
		if cerr := q.getPaperByDOIStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPaperByDOIStmt: %w", cerr)
		}
	}
	if q.getPaperByFilePathStmt != nil {
		if cerr := q.getPaperByFilePathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPaperByFilePathStmt: %w", cerr)
		}
	}
	if q.getPaperChunkStmt != nil {
		if cerr := q.getPaperChunkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPaperChunkStmt: %w", cerr)
		}
	}
	if q.getPaperChunksStmt != nil {
		if cerr := q.getPaperChunksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPaperChunksStmt: %w", cerr)
		}
	}
	if q.getPaperIndexStateStmt != nil {
		if cerr := q.getPaperIndexStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPaperIndexStateStmt: %w", cerr)
		}
	}
	if q.getPaperRelationsStmt != nil {
		if cerr := q.getPaperRelationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPaperRelationsStmt: %w", cerr)
		}
	}
	if q.getPaperTreeStmt != nil {
		if cerr := q.getPaperTreeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPaperTreeStmt: %w", cerr)
		}
	}
	if q.getPermissionRuleStmt != nil {
		if cerr := q.getPermissionRuleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPermissionRuleStmt: %w", cerr)
		}
	}
	if q.getSessionByIDStmt != nil {
		if cerr := q.getSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIDStmt: %w", cerr)
		}
	}
	if q.getTopAccessedPapersStmt != nil {
		if cerr := q.getTopAccessedPapersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTopAccessedPapersStmt: %w", cerr)
		}
	}
	if q.incrementBatchJobAttemptStmt != nil {
		if cerr := q.incrementBatchJobAttemptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementBatchJobAttemptStmt: %w", cerr)
		}
	}
	if q.incrementMemoryAccessCountStmt != nil {
		if cerr := q.incrementMemoryAccessCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementMemoryAccessCountStmt: %w", cerr)
		}
	}
	if q.insertBatchJobStmt != nil {
		if cerr := q.insertBatchJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertBatchJobStmt: %w", cerr)
		}
	}
	if q.insertKBTaskStmt != nil {
		if cerr := q.insertKBTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertKBTaskStmt: %w", cerr)
		}
	}
	if q.insertMemoryItemStmt != nil {
		if cerr := q.insertMemoryItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertMemoryItemStmt: %w", cerr)
		}
	}
	if q.insertNodeContentStmt != nil {
		if cerr := q.insertNodeContentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertNodeContentStmt: %w", cerr)
		}
	}
	if q.insertNodeSummaryStmt != nil {
		if cerr := q.insertNodeSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertNodeSummaryStmt: %w", cerr)
		}
	}
	if q.insertPaperStmt != nil {
		if cerr := q.insertPaperStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertPaperStmt: %w", cerr)
		}
	}
	if q.insertPaperChunkStmt != nil {
		if cerr := q.insertPaperChunkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertPaperChunkStmt: %w", cerr)
		}
	}
	if q.insertPaperTreeStmt != nil {
		if cerr := q.insertPaperTreeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertPaperTreeStmt: %w", cerr)
		}
	}
	if q.insertResearchTopicStmt != nil {
		if cerr := q.insertResearchTopicStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertResearchTopicStmt: %w", cerr)
		}
	}
	if q.insertUsageStatStmt != nil {
		if cerr := q.insertUsageStatStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertUsageStatStmt: %w", cerr)
		}
	}
	if q.listBibEntriesBySessionStmt != nil {
		if cerr := q.listBibEntriesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBibEntriesBySessionStmt: %w", cerr)
		}
	}
	if q.listDocxDiagnosticsStmt != nil {
		if cerr := q.listDocxDiagnosticsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDocxDiagnosticsStmt: %w", cerr)
		}
	}
	if q.listDocxDocumentsByPipelineStmt != nil {
		if cerr := q.listDocxDocumentsByPipelineStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDocxDocumentsByPipelineStmt: %w", cerr)
		}
	}
	if q.listDocxExportsStmt != nil {
		if cerr := q.listDocxExportsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDocxExportsStmt: %w", cerr)
		}
	}
	if q.listDocxMaterialsStmt != nil {
		if cerr := q.listDocxMaterialsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDocxMaterialsStmt: %w", cerr)
		}
	}
	if q.listDocxVersionsStmt != nil {
		if cerr := q.listDocxVersionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDocxVersionsStmt: %w", cerr)
		}
	}
	if q.listFailedBatchJobsStmt != nil {
		if cerr := q.listFailedBatchJobsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFailedBatchJobsStmt: %w", cerr)
		}
	}
	if q.listFilesBySessionStmt != nil {
		if cerr := q.listFilesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesBySessionStmt: %w", cerr)
		}
	}
	if q.listGlobalMemoryItemsStmt != nil {
		if cerr := q.listGlobalMemoryItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listGlobalMemoryItemsStmt: %w", cerr)
		}
	}
	if q.listKBTasksByPaperStmt != nil {
		if cerr := q.listKBTasksByPaperStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listKBTasksByPaperStmt: %w", cerr)
		}
	}
	if q.listMemoryItemsForSessionStmt != nil {
		if cerr := q.listMemoryItemsForSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMemoryItemsForSessionStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionStmt != nil {
		if cerr := q.listMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listMessagesMissingSearchTextStmt != nil {
		if cerr := q.listMessagesMissingSearchTextStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesMissingSearchTextStmt: %w", cerr)
		}
	}
	if q.listMessagesMissingSearchTextForResumeSearchStmt != nil {
		if cerr := q.listMessagesMissingSearchTextForResumeSearchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesMissingSearchTextForResumeSearchStmt: %w", cerr)
		}
	}
	if q.listPaperIndexStatesStmt != nil {
		if cerr := q.listPaperIndexStatesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPaperIndexStatesStmt: %w", cerr)
		}
	}
	if q.listPapersStmt != nil {
		if cerr := q.listPapersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPapersStmt: %w", cerr)
		}
	}
	if q.listPapersWithIndexStateAndTaskStmt != nil {
		if cerr := q.listPapersWithIndexStateAndTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPapersWithIndexStateAndTaskStmt: %w", cerr)
		}
	}
	if q.listPendingBatchJobsStmt != nil {
		if cerr := q.listPendingBatchJobsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPendingBatchJobsStmt: %w", cerr)
		}
	}
	if q.listPendingKBTasksStmt != nil {
		if cerr := q.listPendingKBTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPendingKBTasksStmt: %w", cerr)
		}
	}
	if q.listPermissionRulesStmt != nil {
		if cerr := q.listPermissionRulesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPermissionRulesStmt: %w", cerr)
		}
	}
	if q.listRecentMemoryItemsStmt != nil {
		if cerr := q.listRecentMemoryItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRecentMemoryItemsStmt: %w", cerr)
		}
	}
	if q.listResearchTopicsStmt != nil {
		if cerr := q.listResearchTopicsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listResearchTopicsStmt: %w", cerr)
		}
	}
	if q.listSessionMemoryItemsStmt != nil {
		if cerr := q.listSessionMemoryItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionMemoryItemsStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.listSessionsForResumeStmt != nil {
		if cerr := q.listSessionsForResumeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsForResumeStmt: %w", cerr)
		}
	}
	if q.rebuildPaperChunksFTSStmt != nil {
		if cerr := q.rebuildPaperChunksFTSStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing rebuildPaperChunksFTSStmt: %w", cerr)
		}
	}
	if q.rebuildPaperChunksFTSForPaperStmt != nil {
		if cerr := q.rebuildPaperChunksFTSForPaperStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing rebuildPaperChunksFTSForPaperStmt: %w", cerr)
		}
	}
	if q.resetBatchJobForRetryStmt != nil {
		if cerr := q.resetBatchJobForRetryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resetBatchJobForRetryStmt: %w", cerr)
		}
	}
	if q.resetFailedBatchJobsStmt != nil {
		if cerr := q.resetFailedBatchJobsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resetFailedBatchJobsStmt: %w", cerr)
		}
	}
	if q.resolveSessionByExactTitleStmt != nil {
		if cerr := q.resolveSessionByExactTitleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resolveSessionByExactTitleStmt: %w", cerr)
		}
	}
	if q.retryKBTaskStmt != nil {
		if cerr := q.retryKBTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing retryKBTaskStmt: %w", cerr)
		}
	}
	if q.searchAllPaperChunksStmt != nil {
		if cerr := q.searchAllPaperChunksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchAllPaperChunksStmt: %w", cerr)
		}
	}
	if q.searchBibEntriesByTitleStmt != nil {
		if cerr := q.searchBibEntriesByTitleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchBibEntriesByTitleStmt: %w", cerr)
		}
	}
	if q.searchNodeContentsStmt != nil {
		if cerr := q.searchNodeContentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchNodeContentsStmt: %w", cerr)
		}
	}
	if q.searchNodeSummariesStmt != nil {
		if cerr := q.searchNodeSummariesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchNodeSummariesStmt: %w", cerr)
		}
	}
	if q.searchPaperChunksStmt != nil {
		if cerr := q.searchPaperChunksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchPaperChunksStmt: %w", cerr)
		}
	}
	if q.searchPapersByTitleStmt != nil {
		if cerr := q.searchPapersByTitleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchPapersByTitleStmt: %w", cerr)
		}
	}
	if q.searchRootSessionsByMessageFTSStmt != nil {
		if cerr := q.searchRootSessionsByMessageFTSStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchRootSessionsByMessageFTSStmt: %w", cerr)
		}
	}
	if q.searchSessionsByMetadataStmt != nil {
		if cerr := q.searchSessionsByMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchSessionsByMetadataStmt: %w", cerr)
		}
	}
	if q.sumPaperChunkBytesStmt != nil {
		if cerr := q.sumPaperChunkBytesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing sumPaperChunkBytesStmt: %w", cerr)
		}
	}
	if q.updateBatchJobStatusStmt != nil {
		if cerr := q.updateBatchJobStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBatchJobStatusStmt: %w", cerr)
		}
	}
	if q.updateDocxDocumentStateStmt != nil {
		if cerr := q.updateDocxDocumentStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDocxDocumentStateStmt: %w", cerr)
		}
	}
	if q.updateDocxMaterialParsedStmt != nil {
		if cerr := q.updateDocxMaterialParsedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDocxMaterialParsedStmt: %w", cerr)
		}
	}
	if q.updateFTSStateStmt != nil {
		if cerr := q.updateFTSStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateFTSStateStmt: %w", cerr)
		}
	}
	if q.updateKBTaskProgressStmt != nil {
		if cerr := q.updateKBTaskProgressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateKBTaskProgressStmt: %w", cerr)
		}
	}
	if q.updateMemoryItemStmt != nil {
		if cerr := q.updateMemoryItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMemoryItemStmt: %w", cerr)
		}
	}
	if q.updateMessageStmt != nil {
		if cerr := q.updateMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageStmt: %w", cerr)
		}
	}
	if q.updatePaperTreeVersionStmt != nil {
		if cerr := q.updatePaperTreeVersionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePaperTreeVersionStmt: %w", cerr)
		}
	}
	if q.updateRawParseStateStmt != nil {
		if cerr := q.updateRawParseStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateRawParseStateStmt: %w", cerr)
		}
	}
	if q.updateSemanticTreeStateStmt != nil {
		if cerr := q.updateSemanticTreeStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSemanticTreeStateStmt: %w", cerr)
		}
	}
	if q.updateSessionStmt != nil {
		if cerr := q.updateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionStmt: %w", cerr)
		}
	}
	if q.upsertMemorySkillStatStmt != nil {
		if cerr := q.upsertMemorySkillStatStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertMemorySkillStatStmt: %w", cerr)
		}
	}
	if q.upsertPaperIndexStateStmt != nil {
		if cerr := q.upsertPaperIndexStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertPaperIndexStateStmt: %w", cerr)
		}
	}
	if q.upsertPaperRelationStmt != nil {
		if cerr := q.upsertPaperRelationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertPaperRelationStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                               DBTX
	tx                                               *sql.Tx
	backfillMessageSearchTextStmt                    *sql.Stmt
	batchInsertPaperChunksStmt                       *sql.Stmt
	cancelKBTaskStmt                                 *sql.Stmt
	claimPendingKBTaskStmt                           *sql.Stmt
	claimPendingKBTaskByTypeStmt                     *sql.Stmt
	clearPaperChunksFTSStmt                          *sql.Stmt
	completeKBTaskStmt                               *sql.Stmt
	countBatchJobsByStatusStmt                       *sql.Stmt
	countKBUsageStatsStmt                            *sql.Stmt
	countNodeContentsStmt                            *sql.Stmt
	countNodeSummariesStmt                           *sql.Stmt
	countPaperChunksStmt                             *sql.Stmt
	countPaperIndexStatesByStatusStmt                *sql.Stmt
	countPapersStmt                                  *sql.Stmt
	createBibEntryStmt                               *sql.Stmt
	createDocxDiagnosticStmt                         *sql.Stmt
	createDocxDocumentStmt                           *sql.Stmt
	createDocxExportStmt                             *sql.Stmt
	createDocxMaterialStmt                           *sql.Stmt
	createDocxVersionStmt                            *sql.Stmt
	createFileStmt                                   *sql.Stmt
	createMessageStmt                                *sql.Stmt
	createPermissionRuleStmt                         *sql.Stmt
	createSessionStmt                                *sql.Stmt
	deleteBibEntriesBySessionStmt                    *sql.Stmt
	deleteBibEntryStmt                               *sql.Stmt
	deleteDocxDiagnosticsByDocumentStmt              *sql.Stmt
	deleteFileStmt                                   *sql.Stmt
	deleteMemoryItemStmt                             *sql.Stmt
	deleteMessageStmt                                *sql.Stmt
	deleteNodeContentsStmt                           *sql.Stmt
	deleteNodeSummariesStmt                          *sql.Stmt
	deletePaperStmt                                  *sql.Stmt
	deletePaperChunksStmt                            *sql.Stmt
	deletePaperChunksFTSForPaperStmt                 *sql.Stmt
	deletePaperTreeStmt                              *sql.Stmt
	deletePermissionRuleStmt                         *sql.Stmt
	deleteSessionStmt                                *sql.Stmt
	deleteSessionMessagesStmt                        *sql.Stmt
	deleteSessionPermissionsStmt                     *sql.Stmt
	enqueueKBTaskStmt                                *sql.Stmt
	failKBTaskStmt                                   *sql.Stmt
	forceRequeueKBTaskStmt                           *sql.Stmt
	getBatchJobStmt                                  *sql.Stmt
	getBibEntryStmt                                  *sql.Stmt
	getBibEntryByCiteKeyStmt                         *sql.Stmt
	getBibEntryByDOIStmt                             *sql.Stmt
	getDocxDocumentStmt                              *sql.Stmt
	getFileStmt                                      *sql.Stmt
	getFileByPathStmt                                *sql.Stmt
	getKBTaskStmt                                    *sql.Stmt
	getMemoryItemStmt                                *sql.Stmt
	getMemorySkillStatsStmt                          *sql.Stmt
	getMessageStmt                                   *sql.Stmt
	getNodeContentStmt                               *sql.Stmt
	getNodeContentsStmt                              *sql.Stmt
	getNodeSummariesStmt                             *sql.Stmt
	getNodeSummaryStmt                               *sql.Stmt
	getPaperStmt                                     *sql.Stmt
	getPaperByArxivIDStmt                            *sql.Stmt
	getPaperByDOIStmt                                *sql.Stmt
	getPaperByFilePathStmt                           *sql.Stmt
	getPaperChunkStmt                                *sql.Stmt
	getPaperChunksStmt                               *sql.Stmt
	getPaperIndexStateStmt                           *sql.Stmt
	getPaperRelationsStmt                            *sql.Stmt
	getPaperTreeStmt                                 *sql.Stmt
	getPermissionRuleStmt                            *sql.Stmt
	getSessionByIDStmt                               *sql.Stmt
	getTopAccessedPapersStmt                         *sql.Stmt
	incrementBatchJobAttemptStmt                     *sql.Stmt
	incrementMemoryAccessCountStmt                   *sql.Stmt
	insertBatchJobStmt                               *sql.Stmt
	insertKBTaskStmt                                 *sql.Stmt
	insertMemoryItemStmt                             *sql.Stmt
	insertNodeContentStmt                            *sql.Stmt
	insertNodeSummaryStmt                            *sql.Stmt
	insertPaperStmt                                  *sql.Stmt
	insertPaperChunkStmt                             *sql.Stmt
	insertPaperTreeStmt                              *sql.Stmt
	insertResearchTopicStmt                          *sql.Stmt
	insertUsageStatStmt                              *sql.Stmt
	listBibEntriesBySessionStmt                      *sql.Stmt
	listDocxDiagnosticsStmt                          *sql.Stmt
	listDocxDocumentsByPipelineStmt                  *sql.Stmt
	listDocxExportsStmt                              *sql.Stmt
	listDocxMaterialsStmt                            *sql.Stmt
	listDocxVersionsStmt                             *sql.Stmt
	listFailedBatchJobsStmt                          *sql.Stmt
	listFilesBySessionStmt                           *sql.Stmt
	listGlobalMemoryItemsStmt                        *sql.Stmt
	listKBTasksByPaperStmt                           *sql.Stmt
	listMemoryItemsForSessionStmt                    *sql.Stmt
	listMessagesBySessionStmt                        *sql.Stmt
	listMessagesMissingSearchTextStmt                *sql.Stmt
	listMessagesMissingSearchTextForResumeSearchStmt *sql.Stmt
	listPaperIndexStatesStmt                         *sql.Stmt
	listPapersStmt                                   *sql.Stmt
	listPapersWithIndexStateAndTaskStmt              *sql.Stmt
	listPendingBatchJobsStmt                         *sql.Stmt
	listPendingKBTasksStmt                           *sql.Stmt
	listPermissionRulesStmt                          *sql.Stmt
	listRecentMemoryItemsStmt                        *sql.Stmt
	listResearchTopicsStmt                           *sql.Stmt
	listSessionMemoryItemsStmt                       *sql.Stmt
	listSessionsStmt                                 *sql.Stmt
	listSessionsForResumeStmt                        *sql.Stmt
	rebuildPaperChunksFTSStmt                        *sql.Stmt
	rebuildPaperChunksFTSForPaperStmt                *sql.Stmt
	resetBatchJobForRetryStmt                        *sql.Stmt
	resetFailedBatchJobsStmt                         *sql.Stmt
	resolveSessionByExactTitleStmt                   *sql.Stmt
	retryKBTaskStmt                                  *sql.Stmt
	searchAllPaperChunksStmt                         *sql.Stmt
	searchBibEntriesByTitleStmt                      *sql.Stmt
	searchNodeContentsStmt                           *sql.Stmt
	searchNodeSummariesStmt                          *sql.Stmt
	searchPaperChunksStmt                            *sql.Stmt
	searchPapersByTitleStmt                          *sql.Stmt
	searchRootSessionsByMessageFTSStmt               *sql.Stmt
	searchSessionsByMetadataStmt                     *sql.Stmt
	sumPaperChunkBytesStmt                           *sql.Stmt
	updateBatchJobStatusStmt                         *sql.Stmt
	updateDocxDocumentStateStmt                      *sql.Stmt
	updateDocxMaterialParsedStmt                     *sql.Stmt
	updateFTSStateStmt                               *sql.Stmt
	updateKBTaskProgressStmt                         *sql.Stmt
	updateMemoryItemStmt                             *sql.Stmt
	updateMessageStmt                                *sql.Stmt
	updatePaperTreeVersionStmt                       *sql.Stmt
	updateRawParseStateStmt                          *sql.Stmt
	updateSemanticTreeStateStmt                      *sql.Stmt
	updateSessionStmt                                *sql.Stmt
	upsertMemorySkillStatStmt                        *sql.Stmt
	upsertPaperIndexStateStmt                        *sql.Stmt
	upsertPaperRelationStmt                          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                               tx,
		tx:                                               tx,
		backfillMessageSearchTextStmt:                    q.backfillMessageSearchTextStmt,
		batchInsertPaperChunksStmt:                       q.batchInsertPaperChunksStmt,
		cancelKBTaskStmt:                                 q.cancelKBTaskStmt,
		claimPendingKBTaskStmt:                           q.claimPendingKBTaskStmt,
		claimPendingKBTaskByTypeStmt:                     q.claimPendingKBTaskByTypeStmt,
		clearPaperChunksFTSStmt:                          q.clearPaperChunksFTSStmt,
		completeKBTaskStmt:                               q.completeKBTaskStmt,
		countBatchJobsByStatusStmt:                       q.countBatchJobsByStatusStmt,
		countKBUsageStatsStmt:                            q.countKBUsageStatsStmt,
		countNodeContentsStmt:                            q.countNodeContentsStmt,
		countNodeSummariesStmt:                           q.countNodeSummariesStmt,
		countPaperChunksStmt:                             q.countPaperChunksStmt,
		countPaperIndexStatesByStatusStmt:                q.countPaperIndexStatesByStatusStmt,
		countPapersStmt:                                  q.countPapersStmt,
		createBibEntryStmt:                               q.createBibEntryStmt,
		createDocxDiagnosticStmt:                         q.createDocxDiagnosticStmt,
		createDocxDocumentStmt:                           q.createDocxDocumentStmt,
		createDocxExportStmt:                             q.createDocxExportStmt,
		createDocxMaterialStmt:                           q.createDocxMaterialStmt,
		createDocxVersionStmt:                            q.createDocxVersionStmt,
		createFileStmt:                                   q.createFileStmt,
		createMessageStmt:                                q.createMessageStmt,
		createPermissionRuleStmt:                         q.createPermissionRuleStmt,
		createSessionStmt:                                q.createSessionStmt,
		deleteBibEntriesBySessionStmt:                    q.deleteBibEntriesBySessionStmt,
		deleteBibEntryStmt:                               q.deleteBibEntryStmt,
		deleteDocxDiagnosticsByDocumentStmt:              q.deleteDocxDiagnosticsByDocumentStmt,
		deleteFileStmt:                                   q.deleteFileStmt,
		deleteMemoryItemStmt:                             q.deleteMemoryItemStmt,
		deleteMessageStmt:                                q.deleteMessageStmt,
		deleteNodeContentsStmt:                           q.deleteNodeContentsStmt,
		deleteNodeSummariesStmt:                          q.deleteNodeSummariesStmt,
		deletePaperStmt:                                  q.deletePaperStmt,
		deletePaperChunksStmt:                            q.deletePaperChunksStmt,
		deletePaperChunksFTSForPaperStmt:                 q.deletePaperChunksFTSForPaperStmt,
		deletePaperTreeStmt:                              q.deletePaperTreeStmt,
		deletePermissionRuleStmt:                         q.deletePermissionRuleStmt,
		deleteSessionStmt:                                q.deleteSessionStmt,
		deleteSessionMessagesStmt:                        q.deleteSessionMessagesStmt,
		deleteSessionPermissionsStmt:                     q.deleteSessionPermissionsStmt,
		enqueueKBTaskStmt:                                q.enqueueKBTaskStmt,
		failKBTaskStmt:                                   q.failKBTaskStmt,
		forceRequeueKBTaskStmt:                           q.forceRequeueKBTaskStmt,
		getBatchJobStmt:                                  q.getBatchJobStmt,
		getBibEntryStmt:                                  q.getBibEntryStmt,
		getBibEntryByCiteKeyStmt:                         q.getBibEntryByCiteKeyStmt,
		getBibEntryByDOIStmt:                             q.getBibEntryByDOIStmt,
		getDocxDocumentStmt:                              q.getDocxDocumentStmt,
		getFileStmt:                                      q.getFileStmt,
		getFileByPathStmt:                                q.getFileByPathStmt,
		getKBTaskStmt:                                    q.getKBTaskStmt,
		getMemoryItemStmt:                                q.getMemoryItemStmt,
		getMemorySkillStatsStmt:                          q.getMemorySkillStatsStmt,
		getMessageStmt:                                   q.getMessageStmt,
		getNodeContentStmt:                               q.getNodeContentStmt,
		getNodeContentsStmt:                              q.getNodeContentsStmt,
		getNodeSummariesStmt:                             q.getNodeSummariesStmt,
		getNodeSummaryStmt:                               q.getNodeSummaryStmt,
		getPaperStmt:                                     q.getPaperStmt,
		getPaperByArxivIDStmt:                            q.getPaperByArxivIDStmt,
		getPaperByDOIStmt:                                q.getPaperByDOIStmt,
		getPaperByFilePathStmt:                           q.getPaperByFilePathStmt,
		getPaperChunkStmt:                                q.getPaperChunkStmt,
		getPaperChunksStmt:                               q.getPaperChunksStmt,
		getPaperIndexStateStmt:                           q.getPaperIndexStateStmt,
		getPaperRelationsStmt:                            q.getPaperRelationsStmt,
		getPaperTreeStmt:                                 q.getPaperTreeStmt,
		getPermissionRuleStmt:                            q.getPermissionRuleStmt,
		getSessionByIDStmt:                               q.getSessionByIDStmt,
		getTopAccessedPapersStmt:                         q.getTopAccessedPapersStmt,
		incrementBatchJobAttemptStmt:                     q.incrementBatchJobAttemptStmt,
		incrementMemoryAccessCountStmt:                   q.incrementMemoryAccessCountStmt,
		insertBatchJobStmt:                               q.insertBatchJobStmt,
		insertKBTaskStmt:                                 q.insertKBTaskStmt,
		insertMemoryItemStmt:                             q.insertMemoryItemStmt,
		insertNodeContentStmt:                            q.insertNodeContentStmt,
		insertNodeSummaryStmt:                            q.insertNodeSummaryStmt,
		insertPaperStmt:                                  q.insertPaperStmt,
		insertPaperChunkStmt:                             q.insertPaperChunkStmt,
		insertPaperTreeStmt:                              q.insertPaperTreeStmt,
		insertResearchTopicStmt:                          q.insertResearchTopicStmt,
		insertUsageStatStmt:                              q.insertUsageStatStmt,
		listBibEntriesBySessionStmt:                      q.listBibEntriesBySessionStmt,
		listDocxDiagnosticsStmt:                          q.listDocxDiagnosticsStmt,
		listDocxDocumentsByPipelineStmt:                  q.listDocxDocumentsByPipelineStmt,
		listDocxExportsStmt:                              q.listDocxExportsStmt,
		listDocxMaterialsStmt:                            q.listDocxMaterialsStmt,
		listDocxVersionsStmt:                             q.listDocxVersionsStmt,
		listFailedBatchJobsStmt:                          q.listFailedBatchJobsStmt,
		listFilesBySessionStmt:                           q.listFilesBySessionStmt,
		listGlobalMemoryItemsStmt:                        q.listGlobalMemoryItemsStmt,
		listKBTasksByPaperStmt:                           q.listKBTasksByPaperStmt,
		listMemoryItemsForSessionStmt:                    q.listMemoryItemsForSessionStmt,
		listMessagesBySessionStmt:                        q.listMessagesBySessionStmt,
		listMessagesMissingSearchTextStmt:                q.listMessagesMissingSearchTextStmt,
		listMessagesMissingSearchTextForResumeSearchStmt: q.listMessagesMissingSearchTextForResumeSearchStmt,
		listPaperIndexStatesStmt:                         q.listPaperIndexStatesStmt,
		listPapersStmt:                                   q.listPapersStmt,
		listPapersWithIndexStateAndTaskStmt:              q.listPapersWithIndexStateAndTaskStmt,
		listPendingBatchJobsStmt:                         q.listPendingBatchJobsStmt,
		listPendingKBTasksStmt:                           q.listPendingKBTasksStmt,
		listPermissionRulesStmt:                          q.listPermissionRulesStmt,
		listRecentMemoryItemsStmt:                        q.listRecentMemoryItemsStmt,
		listResearchTopicsStmt:                           q.listResearchTopicsStmt,
		listSessionMemoryItemsStmt:                       q.listSessionMemoryItemsStmt,
		listSessionsStmt:                                 q.listSessionsStmt,
		listSessionsForResumeStmt:                        q.listSessionsForResumeStmt,
		rebuildPaperChunksFTSStmt:                        q.rebuildPaperChunksFTSStmt,
		rebuildPaperChunksFTSForPaperStmt:                q.rebuildPaperChunksFTSForPaperStmt,
		resetBatchJobForRetryStmt:                        q.resetBatchJobForRetryStmt,
		resetFailedBatchJobsStmt:                         q.resetFailedBatchJobsStmt,
		resolveSessionByExactTitleStmt:                   q.resolveSessionByExactTitleStmt,
		retryKBTaskStmt:                                  q.retryKBTaskStmt,
		searchAllPaperChunksStmt:                         q.searchAllPaperChunksStmt,
		searchBibEntriesByTitleStmt:                      q.searchBibEntriesByTitleStmt,
		searchNodeContentsStmt:                           q.searchNodeContentsStmt,
		searchNodeSummariesStmt:                          q.searchNodeSummariesStmt,
		searchPaperChunksStmt:                            q.searchPaperChunksStmt,
		searchPapersByTitleStmt:                          q.searchPapersByTitleStmt,
		searchRootSessionsByMessageFTSStmt:               q.searchRootSessionsByMessageFTSStmt,
		searchSessionsByMetadataStmt:                     q.searchSessionsByMetadataStmt,
		sumPaperChunkBytesStmt:                           q.sumPaperChunkBytesStmt,
		updateBatchJobStatusStmt:                         q.updateBatchJobStatusStmt,
		updateDocxDocumentStateStmt:                      q.updateDocxDocumentStateStmt,
		updateDocxMaterialParsedStmt:                     q.updateDocxMaterialParsedStmt,
		updateFTSStateStmt:                               q.updateFTSStateStmt,
		updateKBTaskProgressStmt:                         q.updateKBTaskProgressStmt,
		updateMemoryItemStmt:                             q.updateMemoryItemStmt,
		updateMessageStmt:                                q.updateMessageStmt,
		updatePaperTreeVersionStmt:                       q.updatePaperTreeVersionStmt,
		updateRawParseStateStmt:                          q.updateRawParseStateStmt,
		updateSemanticTreeStateStmt:                      q.updateSemanticTreeStateStmt,
		updateSessionStmt:                                q.updateSessionStmt,
		upsertMemorySkillStatStmt:                        q.upsertMemorySkillStatStmt,
		upsertPaperIndexStateStmt:                        q.upsertPaperIndexStateStmt,
		upsertPaperRelationStmt:                          q.upsertPaperRelationStmt,
	}
}
