// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: docx.sql

package db

import (
	"context"
	"database/sql"
)

const createDocxDiagnostic = `-- name: CreateDocxDiagnostic :exec
INSERT INTO docx_diagnostics (document_id, version_id, rule_id, level, location_json, message, suggestion, auto_fix, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDocxDiagnosticParams struct {
	DocumentID   int64          `json:"document_id"`
	VersionID    sql.NullInt64  `json:"version_id"`
	RuleID       string         `json:"rule_id"`
	Level        string         `json:"level"`
	LocationJson sql.NullString `json:"location_json"`
	Message      string         `json:"message"`
	Suggestion   sql.NullString `json:"suggestion"`
	AutoFix      int64          `json:"auto_fix"`
	CreatedAt    int64          `json:"created_at"`
}

func (q *Queries) CreateDocxDiagnostic(ctx context.Context, arg CreateDocxDiagnosticParams) error {
	_, err := q.exec(ctx, q.createDocxDiagnosticStmt, createDocxDiagnostic,
		arg.DocumentID,
		arg.VersionID,
		arg.RuleID,
		arg.Level,
		arg.LocationJson,
		arg.Message,
		arg.Suggestion,
		arg.AutoFix,
		arg.CreatedAt,
	)
	return err
}

const createDocxDocument = `-- name: CreateDocxDocument :one
INSERT INTO docx_documents (pipeline_id, doc_type, template_id, template_ver, state, source_path, docx_path, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, pipeline_id, doc_type, template_id, template_ver, state, source_path, docx_path, created_at, updated_at
`

type CreateDocxDocumentParams struct {
	PipelineID  sql.NullInt64  `json:"pipeline_id"`
	DocType     string         `json:"doc_type"`
	TemplateID  sql.NullString `json:"template_id"`
	TemplateVer sql.NullString `json:"template_ver"`
	State       string         `json:"state"`
	SourcePath  sql.NullString `json:"source_path"`
	DocxPath    sql.NullString `json:"docx_path"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

func (q *Queries) CreateDocxDocument(ctx context.Context, arg CreateDocxDocumentParams) (DocxDocument, error) {
	row := q.queryRow(ctx, q.createDocxDocumentStmt, createDocxDocument,
		arg.PipelineID,
		arg.DocType,
		arg.TemplateID,
		arg.TemplateVer,
		arg.State,
		arg.SourcePath,
		arg.DocxPath,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DocxDocument
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.DocType,
		&i.TemplateID,
		&i.TemplateVer,
		&i.State,
		&i.SourcePath,
		&i.DocxPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocxExport = `-- name: CreateDocxExport :one
INSERT INTO docx_exports (document_id, format, engine, params_json, output_path, success, error_msg, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, document_id, format, engine, params_json, output_path, success, error_msg, created_at
`

type CreateDocxExportParams struct {
	DocumentID int64          `json:"document_id"`
	Format     string         `json:"format"`
	Engine     sql.NullString `json:"engine"`
	ParamsJson sql.NullString `json:"params_json"`
	OutputPath string         `json:"output_path"`
	Success    int64          `json:"success"`
	ErrorMsg   sql.NullString `json:"error_msg"`
	CreatedAt  int64          `json:"created_at"`
}

func (q *Queries) CreateDocxExport(ctx context.Context, arg CreateDocxExportParams) (DocxExport, error) {
	row := q.queryRow(ctx, q.createDocxExportStmt, createDocxExport,
		arg.DocumentID,
		arg.Format,
		arg.Engine,
		arg.ParamsJson,
		arg.OutputPath,
		arg.Success,
		arg.ErrorMsg,
		arg.CreatedAt,
	)
	var i DocxExport
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Format,
		&i.Engine,
		&i.ParamsJson,
		&i.OutputPath,
		&i.Success,
		&i.ErrorMsg,
		&i.CreatedAt,
	)
	return i, err
}

const createDocxMaterial = `-- name: CreateDocxMaterial :one
INSERT INTO docx_materials (document_id, source_path, doc_type, parsed, parsed_at, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, document_id, source_path, doc_type, parsed, parsed_at, created_at
`

type CreateDocxMaterialParams struct {
	DocumentID int64         `json:"document_id"`
	SourcePath string        `json:"source_path"`
	DocType    string        `json:"doc_type"`
	Parsed     int64         `json:"parsed"`
	ParsedAt   sql.NullInt64 `json:"parsed_at"`
	CreatedAt  int64         `json:"created_at"`
}

func (q *Queries) CreateDocxMaterial(ctx context.Context, arg CreateDocxMaterialParams) (DocxMaterial, error) {
	row := q.queryRow(ctx, q.createDocxMaterialStmt, createDocxMaterial,
		arg.DocumentID,
		arg.SourcePath,
		arg.DocType,
		arg.Parsed,
		arg.ParsedAt,
		arg.CreatedAt,
	)
	var i DocxMaterial
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.SourcePath,
		&i.DocType,
		&i.Parsed,
		&i.ParsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createDocxVersion = `-- name: CreateDocxVersion :one
INSERT INTO docx_versions (document_id, phase, snapshot_path, created_by, description, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, document_id, phase, snapshot_path, created_by, description, created_at
`

type CreateDocxVersionParams struct {
	DocumentID   int64          `json:"document_id"`
	Phase        string         `json:"phase"`
	SnapshotPath string         `json:"snapshot_path"`
	CreatedBy    string         `json:"created_by"`
	Description  sql.NullString `json:"description"`
	CreatedAt    int64          `json:"created_at"`
}

func (q *Queries) CreateDocxVersion(ctx context.Context, arg CreateDocxVersionParams) (DocxVersion, error) {
	row := q.queryRow(ctx, q.createDocxVersionStmt, createDocxVersion,
		arg.DocumentID,
		arg.Phase,
		arg.SnapshotPath,
		arg.CreatedBy,
		arg.Description,
		arg.CreatedAt,
	)
	var i DocxVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Phase,
		&i.SnapshotPath,
		&i.CreatedBy,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocxDiagnosticsByDocument = `-- name: DeleteDocxDiagnosticsByDocument :exec
DELETE FROM docx_diagnostics WHERE document_id = ?
`

func (q *Queries) DeleteDocxDiagnosticsByDocument(ctx context.Context, documentID int64) error {
	_, err := q.exec(ctx, q.deleteDocxDiagnosticsByDocumentStmt, deleteDocxDiagnosticsByDocument, documentID)
	return err
}

const getDocxDocument = `-- name: GetDocxDocument :one
SELECT id, pipeline_id, doc_type, template_id, template_ver, state, source_path, docx_path, created_at, updated_at FROM docx_documents WHERE id = ?
`

func (q *Queries) GetDocxDocument(ctx context.Context, id int64) (DocxDocument, error) {
	row := q.queryRow(ctx, q.getDocxDocumentStmt, getDocxDocument, id)
	var i DocxDocument
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.DocType,
		&i.TemplateID,
		&i.TemplateVer,
		&i.State,
		&i.SourcePath,
		&i.DocxPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocxDiagnostics = `-- name: ListDocxDiagnostics :many
SELECT id, document_id, version_id, rule_id, level, location_json, message, suggestion, auto_fix, created_at FROM docx_diagnostics WHERE document_id = ? ORDER BY level, rule_id
`

func (q *Queries) ListDocxDiagnostics(ctx context.Context, documentID int64) ([]DocxDiagnostic, error) {
	rows, err := q.query(ctx, q.listDocxDiagnosticsStmt, listDocxDiagnostics, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocxDiagnostic{}
	for rows.Next() {
		var i DocxDiagnostic
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.VersionID,
			&i.RuleID,
			&i.Level,
			&i.LocationJson,
			&i.Message,
			&i.Suggestion,
			&i.AutoFix,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocxDocumentsByPipeline = `-- name: ListDocxDocumentsByPipeline :many
SELECT id, pipeline_id, doc_type, template_id, template_ver, state, source_path, docx_path, created_at, updated_at FROM docx_documents WHERE pipeline_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDocxDocumentsByPipeline(ctx context.Context, pipelineID sql.NullInt64) ([]DocxDocument, error) {
	rows, err := q.query(ctx, q.listDocxDocumentsByPipelineStmt, listDocxDocumentsByPipeline, pipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocxDocument{}
	for rows.Next() {
		var i DocxDocument
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.DocType,
			&i.TemplateID,
			&i.TemplateVer,
			&i.State,
			&i.SourcePath,
			&i.DocxPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocxExports = `-- name: ListDocxExports :many
SELECT id, document_id, format, engine, params_json, output_path, success, error_msg, created_at FROM docx_exports WHERE document_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDocxExports(ctx context.Context, documentID int64) ([]DocxExport, error) {
	rows, err := q.query(ctx, q.listDocxExportsStmt, listDocxExports, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocxExport{}
	for rows.Next() {
		var i DocxExport
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Format,
			&i.Engine,
			&i.ParamsJson,
			&i.OutputPath,
			&i.Success,
			&i.ErrorMsg,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocxMaterials = `-- name: ListDocxMaterials :many
SELECT id, document_id, source_path, doc_type, parsed, parsed_at, created_at FROM docx_materials WHERE document_id = ? ORDER BY created_at
`

func (q *Queries) ListDocxMaterials(ctx context.Context, documentID int64) ([]DocxMaterial, error) {
	rows, err := q.query(ctx, q.listDocxMaterialsStmt, listDocxMaterials, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocxMaterial{}
	for rows.Next() {
		var i DocxMaterial
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.SourcePath,
			&i.DocType,
			&i.Parsed,
			&i.ParsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocxVersions = `-- name: ListDocxVersions :many
SELECT id, document_id, phase, snapshot_path, created_by, description, created_at FROM docx_versions WHERE document_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDocxVersions(ctx context.Context, documentID int64) ([]DocxVersion, error) {
	rows, err := q.query(ctx, q.listDocxVersionsStmt, listDocxVersions, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocxVersion{}
	for rows.Next() {
		var i DocxVersion
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Phase,
			&i.SnapshotPath,
			&i.CreatedBy,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocxDocumentState = `-- name: UpdateDocxDocumentState :exec
UPDATE docx_documents SET state = ?, updated_at = ? WHERE id = ?
`

type UpdateDocxDocumentStateParams struct {
	State     string `json:"state"`
	UpdatedAt int64  `json:"updated_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateDocxDocumentState(ctx context.Context, arg UpdateDocxDocumentStateParams) error {
	_, err := q.exec(ctx, q.updateDocxDocumentStateStmt, updateDocxDocumentState, arg.State, arg.UpdatedAt, arg.ID)
	return err
}

const updateDocxMaterialParsed = `-- name: UpdateDocxMaterialParsed :exec
UPDATE docx_materials SET parsed = 1, parsed_at = ? WHERE id = ?
`

type UpdateDocxMaterialParsedParams struct {
	ParsedAt sql.NullInt64 `json:"parsed_at"`
	ID       int64         `json:"id"`
}

func (q *Queries) UpdateDocxMaterialParsed(ctx context.Context, arg UpdateDocxMaterialParsedParams) error {
	_, err := q.exec(ctx, q.updateDocxMaterialParsedStmt, updateDocxMaterialParsed, arg.ParsedAt, arg.ID)
	return err
}
