// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kb_tasks.sql

package db

import (
	"context"
	"database/sql"
)

const cancelKBTask = `-- name: CancelKBTask :exec
UPDATE kb_tasks
SET
    status = 'canceled',
    error = ?1,
    lease_owner = NULL,
    lease_until = NULL,
    updated_at = ?2,
    finished_at = ?2
WHERE task_id = ?3
  AND status IN ('queued', 'running')
`

type CancelKBTaskParams struct {
	Error     sql.NullString `json:"error"`
	UpdatedAt int64          `json:"updated_at"`
	TaskID    string         `json:"task_id"`
}

func (q *Queries) CancelKBTask(ctx context.Context, arg CancelKBTaskParams) error {
	_, err := q.exec(ctx, q.cancelKBTaskStmt, cancelKBTask, arg.Error, arg.UpdatedAt, arg.TaskID)
	return err
}

const claimPendingKBTask = `-- name: ClaimPendingKBTask :one
UPDATE kb_tasks
SET
    status = 'running',
    lease_owner = ?1,
    lease_until = ?2,
    attempt_count = attempt_count + 1,
    updated_at = ?3,
    started_at = COALESCE(started_at, ?3)
WHERE task_id = (
    SELECT task_id
    FROM kb_tasks AS t
    WHERE t.status = 'queued'
       OR (t.status = 'running' AND t.lease_until IS NOT NULL AND t.lease_until < ?4)
    ORDER BY t.created_at ASC
    LIMIT 1
)
RETURNING task_id, paper_id, task_type, status, progress, input_json, result_json, result_ref, error, lease_owner, lease_until, attempt_count, created_at, updated_at, started_at, finished_at
`

type ClaimPendingKBTaskParams struct {
	LeaseOwner sql.NullString `json:"lease_owner"`
	LeaseUntil sql.NullInt64  `json:"lease_until"`
	UpdatedAt  int64          `json:"updated_at"`
	NowEpoch   sql.NullInt64  `json:"now_epoch"`
}

func (q *Queries) ClaimPendingKBTask(ctx context.Context, arg ClaimPendingKBTaskParams) (KbTask, error) {
	row := q.queryRow(ctx, q.claimPendingKBTaskStmt, claimPendingKBTask,
		arg.LeaseOwner,
		arg.LeaseUntil,
		arg.UpdatedAt,
		arg.NowEpoch,
	)
	var i KbTask
	err := row.Scan(
		&i.TaskID,
		&i.PaperID,
		&i.TaskType,
		&i.Status,
		&i.Progress,
		&i.InputJson,
		&i.ResultJson,
		&i.ResultRef,
		&i.Error,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const claimPendingKBTaskByType = `-- name: ClaimPendingKBTaskByType :one
UPDATE kb_tasks
SET
    status = 'running',
    lease_owner = ?1,
    lease_until = ?2,
    attempt_count = attempt_count + 1,
    updated_at = ?3,
    started_at = COALESCE(started_at, ?3)
WHERE task_id = (
    SELECT task_id
    FROM kb_tasks AS t
    WHERE t.task_type = ?4
      AND (t.status = 'queued'
        OR (t.status = 'running' AND t.lease_until IS NOT NULL AND t.lease_until < ?5))
    ORDER BY t.created_at ASC
    LIMIT 1
)
RETURNING task_id, paper_id, task_type, status, progress, input_json, result_json, result_ref, error, lease_owner, lease_until, attempt_count, created_at, updated_at, started_at, finished_at
`

type ClaimPendingKBTaskByTypeParams struct {
	LeaseOwner sql.NullString `json:"lease_owner"`
	LeaseUntil sql.NullInt64  `json:"lease_until"`
	UpdatedAt  int64          `json:"updated_at"`
	TaskType   string         `json:"task_type"`
	NowEpoch   sql.NullInt64  `json:"now_epoch"`
}

func (q *Queries) ClaimPendingKBTaskByType(ctx context.Context, arg ClaimPendingKBTaskByTypeParams) (KbTask, error) {
	row := q.queryRow(ctx, q.claimPendingKBTaskByTypeStmt, claimPendingKBTaskByType,
		arg.LeaseOwner,
		arg.LeaseUntil,
		arg.UpdatedAt,
		arg.TaskType,
		arg.NowEpoch,
	)
	var i KbTask
	err := row.Scan(
		&i.TaskID,
		&i.PaperID,
		&i.TaskType,
		&i.Status,
		&i.Progress,
		&i.InputJson,
		&i.ResultJson,
		&i.ResultRef,
		&i.Error,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const completeKBTask = `-- name: CompleteKBTask :exec
UPDATE kb_tasks
SET
    status = 'succeeded',
    progress = 1.0,
    result_json = ?1,
    result_ref = ?2,
    error = NULL,
    lease_owner = NULL,
    lease_until = NULL,
    updated_at = ?3,
    finished_at = ?3
WHERE task_id = ?4
`

type CompleteKBTaskParams struct {
	ResultJson sql.NullString `json:"result_json"`
	ResultRef  sql.NullString `json:"result_ref"`
	UpdatedAt  int64          `json:"updated_at"`
	TaskID     string         `json:"task_id"`
}

func (q *Queries) CompleteKBTask(ctx context.Context, arg CompleteKBTaskParams) error {
	_, err := q.exec(ctx, q.completeKBTaskStmt, completeKBTask,
		arg.ResultJson,
		arg.ResultRef,
		arg.UpdatedAt,
		arg.TaskID,
	)
	return err
}

const enqueueKBTask = `-- name: EnqueueKBTask :one
INSERT INTO kb_tasks (
    task_id,
    paper_id,
    task_type,
    status,
    progress,
    input_json,
    result_json,
    result_ref,
    error,
    lease_owner,
    lease_until,
    attempt_count,
    created_at,
    updated_at,
    started_at,
    finished_at
) VALUES (
    ?1,
    ?2,
    ?3,
    'queued',
    0,
    ?4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    ?5,
    ?6,
    NULL,
    NULL
)
ON CONFLICT(task_id) DO UPDATE SET
    status = CASE
        WHEN kb_tasks.status IN ('failed', 'canceled') THEN 'queued'
        ELSE kb_tasks.status
    END,
    input_json = CASE
        WHEN kb_tasks.status IN ('failed', 'canceled') THEN excluded.input_json
        ELSE kb_tasks.input_json
    END,
    error = CASE
        WHEN kb_tasks.status IN ('failed', 'canceled') THEN NULL
        ELSE kb_tasks.error
    END,
    progress = CASE
        WHEN kb_tasks.status IN ('failed', 'canceled') THEN 0
        ELSE kb_tasks.progress
    END,
    lease_owner = CASE
        WHEN kb_tasks.status IN ('failed', 'canceled') THEN NULL
        ELSE kb_tasks.lease_owner
    END,
    lease_until = CASE
        WHEN kb_tasks.status IN ('failed', 'canceled') THEN NULL
        ELSE kb_tasks.lease_until
    END,
    updated_at = excluded.updated_at,
    started_at = CASE
        WHEN kb_tasks.status IN ('failed', 'canceled') THEN NULL
        ELSE kb_tasks.started_at
    END,
    finished_at = CASE
        WHEN kb_tasks.status IN ('failed', 'canceled') THEN NULL
        ELSE kb_tasks.finished_at
    END
RETURNING task_id, paper_id, task_type, status, progress, input_json, result_json, result_ref, error, lease_owner, lease_until, attempt_count, created_at, updated_at, started_at, finished_at
`

type EnqueueKBTaskParams struct {
	TaskID    string         `json:"task_id"`
	PaperID   sql.NullString `json:"paper_id"`
	TaskType  string         `json:"task_type"`
	InputJson sql.NullString `json:"input_json"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

func (q *Queries) EnqueueKBTask(ctx context.Context, arg EnqueueKBTaskParams) (KbTask, error) {
	row := q.queryRow(ctx, q.enqueueKBTaskStmt, enqueueKBTask,
		arg.TaskID,
		arg.PaperID,
		arg.TaskType,
		arg.InputJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i KbTask
	err := row.Scan(
		&i.TaskID,
		&i.PaperID,
		&i.TaskType,
		&i.Status,
		&i.Progress,
		&i.InputJson,
		&i.ResultJson,
		&i.ResultRef,
		&i.Error,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const failKBTask = `-- name: FailKBTask :exec
UPDATE kb_tasks
SET
    status = 'failed',
    error = ?1,
    lease_owner = NULL,
    lease_until = NULL,
    updated_at = ?2,
    finished_at = ?2
WHERE task_id = ?3
`

type FailKBTaskParams struct {
	Error     sql.NullString `json:"error"`
	UpdatedAt int64          `json:"updated_at"`
	TaskID    string         `json:"task_id"`
}

func (q *Queries) FailKBTask(ctx context.Context, arg FailKBTaskParams) error {
	_, err := q.exec(ctx, q.failKBTaskStmt, failKBTask, arg.Error, arg.UpdatedAt, arg.TaskID)
	return err
}

const forceRequeueKBTask = `-- name: ForceRequeueKBTask :one
UPDATE kb_tasks
SET
    status = 'queued',
    progress = 0,
    input_json = ?1,
    result_json = NULL,
    result_ref = NULL,
    error = NULL,
    lease_owner = NULL,
    lease_until = NULL,
    updated_at = ?2,
    started_at = NULL,
    finished_at = NULL
WHERE task_id = ?3
RETURNING task_id, paper_id, task_type, status, progress, input_json, result_json, result_ref, error, lease_owner, lease_until, attempt_count, created_at, updated_at, started_at, finished_at
`

type ForceRequeueKBTaskParams struct {
	InputJson sql.NullString `json:"input_json"`
	UpdatedAt int64          `json:"updated_at"`
	TaskID    string         `json:"task_id"`
}

func (q *Queries) ForceRequeueKBTask(ctx context.Context, arg ForceRequeueKBTaskParams) (KbTask, error) {
	row := q.queryRow(ctx, q.forceRequeueKBTaskStmt, forceRequeueKBTask, arg.InputJson, arg.UpdatedAt, arg.TaskID)
	var i KbTask
	err := row.Scan(
		&i.TaskID,
		&i.PaperID,
		&i.TaskType,
		&i.Status,
		&i.Progress,
		&i.InputJson,
		&i.ResultJson,
		&i.ResultRef,
		&i.Error,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getKBTask = `-- name: GetKBTask :one
SELECT task_id, paper_id, task_type, status, progress, input_json, result_json, result_ref, error, lease_owner, lease_until, attempt_count, created_at, updated_at, started_at, finished_at FROM kb_tasks
WHERE task_id = ?
`

func (q *Queries) GetKBTask(ctx context.Context, taskID string) (KbTask, error) {
	row := q.queryRow(ctx, q.getKBTaskStmt, getKBTask, taskID)
	var i KbTask
	err := row.Scan(
		&i.TaskID,
		&i.PaperID,
		&i.TaskType,
		&i.Status,
		&i.Progress,
		&i.InputJson,
		&i.ResultJson,
		&i.ResultRef,
		&i.Error,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertKBTask = `-- name: InsertKBTask :exec
INSERT INTO kb_tasks (
    task_id,
    paper_id,
    task_type,
    status,
    progress,
    input_json,
    result_json,
    result_ref,
    error,
    lease_owner,
    lease_until,
    attempt_count,
    created_at,
    updated_at,
    started_at,
    finished_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertKBTaskParams struct {
	TaskID       string          `json:"task_id"`
	PaperID      sql.NullString  `json:"paper_id"`
	TaskType     string          `json:"task_type"`
	Status       string          `json:"status"`
	Progress     sql.NullFloat64 `json:"progress"`
	InputJson    sql.NullString  `json:"input_json"`
	ResultJson   sql.NullString  `json:"result_json"`
	ResultRef    sql.NullString  `json:"result_ref"`
	Error        sql.NullString  `json:"error"`
	LeaseOwner   sql.NullString  `json:"lease_owner"`
	LeaseUntil   sql.NullInt64   `json:"lease_until"`
	AttemptCount int64           `json:"attempt_count"`
	CreatedAt    int64           `json:"created_at"`
	UpdatedAt    int64           `json:"updated_at"`
	StartedAt    sql.NullInt64   `json:"started_at"`
	FinishedAt   sql.NullInt64   `json:"finished_at"`
}

func (q *Queries) InsertKBTask(ctx context.Context, arg InsertKBTaskParams) error {
	_, err := q.exec(ctx, q.insertKBTaskStmt, insertKBTask,
		arg.TaskID,
		arg.PaperID,
		arg.TaskType,
		arg.Status,
		arg.Progress,
		arg.InputJson,
		arg.ResultJson,
		arg.ResultRef,
		arg.Error,
		arg.LeaseOwner,
		arg.LeaseUntil,
		arg.AttemptCount,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const listKBTasksByPaper = `-- name: ListKBTasksByPaper :many
SELECT task_id, paper_id, task_type, status, progress, input_json, result_json, result_ref, error, lease_owner, lease_until, attempt_count, created_at, updated_at, started_at, finished_at FROM kb_tasks
WHERE paper_id = ?
ORDER BY created_at DESC, task_id DESC
LIMIT ? OFFSET ?
`

type ListKBTasksByPaperParams struct {
	PaperID sql.NullString `json:"paper_id"`
	Limit   int64          `json:"limit"`
	Offset  int64          `json:"offset"`
}

func (q *Queries) ListKBTasksByPaper(ctx context.Context, arg ListKBTasksByPaperParams) ([]KbTask, error) {
	rows, err := q.query(ctx, q.listKBTasksByPaperStmt, listKBTasksByPaper, arg.PaperID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbTask{}
	for rows.Next() {
		var i KbTask
		if err := rows.Scan(
			&i.TaskID,
			&i.PaperID,
			&i.TaskType,
			&i.Status,
			&i.Progress,
			&i.InputJson,
			&i.ResultJson,
			&i.ResultRef,
			&i.Error,
			&i.LeaseOwner,
			&i.LeaseUntil,
			&i.AttemptCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingKBTasks = `-- name: ListPendingKBTasks :many
SELECT task_id, paper_id, task_type, status, progress, input_json, result_json, result_ref, error, lease_owner, lease_until, attempt_count, created_at, updated_at, started_at, finished_at FROM kb_tasks
WHERE status = 'queued'
ORDER BY created_at ASC
LIMIT ?
`

func (q *Queries) ListPendingKBTasks(ctx context.Context, limit int64) ([]KbTask, error) {
	rows, err := q.query(ctx, q.listPendingKBTasksStmt, listPendingKBTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbTask{}
	for rows.Next() {
		var i KbTask
		if err := rows.Scan(
			&i.TaskID,
			&i.PaperID,
			&i.TaskType,
			&i.Status,
			&i.Progress,
			&i.InputJson,
			&i.ResultJson,
			&i.ResultRef,
			&i.Error,
			&i.LeaseOwner,
			&i.LeaseUntil,
			&i.AttemptCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryKBTask = `-- name: RetryKBTask :exec
UPDATE kb_tasks
SET
    status = 'queued',
    progress = 0,
    error = ?1,
    lease_owner = NULL,
    lease_until = NULL,
    updated_at = ?2
WHERE task_id = ?3
  AND status = 'running'
`

type RetryKBTaskParams struct {
	Error     sql.NullString `json:"error"`
	UpdatedAt int64          `json:"updated_at"`
	TaskID    string         `json:"task_id"`
}

func (q *Queries) RetryKBTask(ctx context.Context, arg RetryKBTaskParams) error {
	_, err := q.exec(ctx, q.retryKBTaskStmt, retryKBTask, arg.Error, arg.UpdatedAt, arg.TaskID)
	return err
}

const updateKBTaskProgress = `-- name: UpdateKBTaskProgress :exec
UPDATE kb_tasks
SET
    progress = ?1,
    lease_owner = ?2,
    lease_until = ?3,
    updated_at = ?4
WHERE task_id = ?5
  AND status = 'running'
`

type UpdateKBTaskProgressParams struct {
	Progress   sql.NullFloat64 `json:"progress"`
	LeaseOwner sql.NullString  `json:"lease_owner"`
	LeaseUntil sql.NullInt64   `json:"lease_until"`
	UpdatedAt  int64           `json:"updated_at"`
	TaskID     string          `json:"task_id"`
}

func (q *Queries) UpdateKBTaskProgress(ctx context.Context, arg UpdateKBTaskProgressParams) error {
	_, err := q.exec(ctx, q.updateKBTaskProgressStmt, updateKBTaskProgress,
		arg.Progress,
		arg.LeaseOwner,
		arg.LeaseUntil,
		arg.UpdatedAt,
		arg.TaskID,
	)
	return err
}
