// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kb_usage.sql

package db

import (
	"context"
	"database/sql"
)

const countKBUsageStats = `-- name: CountKBUsageStats :one
SELECT COUNT(*) FROM kb_usage_stats
`

func (q *Queries) CountKBUsageStats(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countKBUsageStatsStmt, countKBUsageStats)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNodeSummaries = `-- name: CountNodeSummaries :one
SELECT COUNT(*) FROM node_summaries
`

func (q *Queries) CountNodeSummaries(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countNodeSummariesStmt, countNodeSummaries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPaperRelations = `-- name: GetPaperRelations :many
SELECT paper_id_a, paper_id_b, relation_type, weight, updated_at FROM paper_relations
WHERE paper_id_a = ? OR paper_id_b = ?
ORDER BY weight DESC
LIMIT ?
`

type GetPaperRelationsParams struct {
	PaperIDA string `json:"paper_id_a"`
	PaperIDB string `json:"paper_id_b"`
	Limit    int64  `json:"limit"`
}

func (q *Queries) GetPaperRelations(ctx context.Context, arg GetPaperRelationsParams) ([]PaperRelation, error) {
	rows, err := q.query(ctx, q.getPaperRelationsStmt, getPaperRelations, arg.PaperIDA, arg.PaperIDB, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaperRelation{}
	for rows.Next() {
		var i PaperRelation
		if err := rows.Scan(
			&i.PaperIDA,
			&i.PaperIDB,
			&i.RelationType,
			&i.Weight,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopAccessedPapers = `-- name: GetTopAccessedPapers :many
SELECT paper_id, COUNT(*) as access_count
FROM kb_usage_stats
WHERE paper_id IS NOT NULL
GROUP BY paper_id
ORDER BY access_count DESC
LIMIT ?
`

type GetTopAccessedPapersRow struct {
	PaperID     sql.NullString `json:"paper_id"`
	AccessCount int64          `json:"access_count"`
}

func (q *Queries) GetTopAccessedPapers(ctx context.Context, limit int64) ([]GetTopAccessedPapersRow, error) {
	rows, err := q.query(ctx, q.getTopAccessedPapersStmt, getTopAccessedPapers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopAccessedPapersRow{}
	for rows.Next() {
		var i GetTopAccessedPapersRow
		if err := rows.Scan(&i.PaperID, &i.AccessCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertResearchTopic = `-- name: InsertResearchTopic :exec
INSERT INTO research_topics (name, description, paper_ids, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertResearchTopicParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	PaperIds    string         `json:"paper_ids"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

func (q *Queries) InsertResearchTopic(ctx context.Context, arg InsertResearchTopicParams) error {
	_, err := q.exec(ctx, q.insertResearchTopicStmt, insertResearchTopic,
		arg.Name,
		arg.Description,
		arg.PaperIds,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertUsageStat = `-- name: InsertUsageStat :exec
INSERT INTO kb_usage_stats (paper_id, node_id, query, search_type, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertUsageStatParams struct {
	PaperID    sql.NullString `json:"paper_id"`
	NodeID     sql.NullString `json:"node_id"`
	Query      string         `json:"query"`
	SearchType string         `json:"search_type"`
	CreatedAt  int64          `json:"created_at"`
}

func (q *Queries) InsertUsageStat(ctx context.Context, arg InsertUsageStatParams) error {
	_, err := q.exec(ctx, q.insertUsageStatStmt, insertUsageStat,
		arg.PaperID,
		arg.NodeID,
		arg.Query,
		arg.SearchType,
		arg.CreatedAt,
	)
	return err
}

const listResearchTopics = `-- name: ListResearchTopics :many
SELECT id, name, description, paper_ids, created_at, updated_at FROM research_topics ORDER BY updated_at DESC LIMIT ?
`

func (q *Queries) ListResearchTopics(ctx context.Context, limit int64) ([]ResearchTopic, error) {
	rows, err := q.query(ctx, q.listResearchTopicsStmt, listResearchTopics, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResearchTopic{}
	for rows.Next() {
		var i ResearchTopic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PaperIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPaperRelation = `-- name: UpsertPaperRelation :exec
INSERT INTO paper_relations (paper_id_a, paper_id_b, relation_type, weight, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(paper_id_a, paper_id_b, relation_type) DO UPDATE SET
    weight = weight + excluded.weight,
    updated_at = excluded.updated_at
`

type UpsertPaperRelationParams struct {
	PaperIDA     string  `json:"paper_id_a"`
	PaperIDB     string  `json:"paper_id_b"`
	RelationType string  `json:"relation_type"`
	Weight       float64 `json:"weight"`
	UpdatedAt    int64   `json:"updated_at"`
}

func (q *Queries) UpsertPaperRelation(ctx context.Context, arg UpsertPaperRelationParams) error {
	_, err := q.exec(ctx, q.upsertPaperRelationStmt, upsertPaperRelation,
		arg.PaperIDA,
		arg.PaperIDB,
		arg.RelationType,
		arg.Weight,
		arg.UpdatedAt,
	)
	return err
}
