// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory_skill_stats.sql

package db

import (
	"context"
)

const getMemorySkillStats = `-- name: GetMemorySkillStats :many
SELECT skill_name, usage_count, success_count, updated_at FROM memory_skill_stats ORDER BY usage_count DESC
`

func (q *Queries) GetMemorySkillStats(ctx context.Context) ([]MemorySkillStat, error) {
	rows, err := q.query(ctx, q.getMemorySkillStatsStmt, getMemorySkillStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemorySkillStat{}
	for rows.Next() {
		var i MemorySkillStat
		if err := rows.Scan(
			&i.SkillName,
			&i.UsageCount,
			&i.SuccessCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMemorySkillStat = `-- name: UpsertMemorySkillStat :exec
INSERT INTO memory_skill_stats (skill_name, usage_count, success_count, updated_at)
VALUES (?, 1, ?, ?)
ON CONFLICT(skill_name) DO UPDATE SET
    usage_count = usage_count + 1,
    success_count = success_count + excluded.success_count,
    updated_at = excluded.updated_at
`

type UpsertMemorySkillStatParams struct {
	SkillName    string `json:"skill_name"`
	SuccessCount int64  `json:"success_count"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) UpsertMemorySkillStat(ctx context.Context, arg UpsertMemorySkillStatParams) error {
	_, err := q.exec(ctx, q.upsertMemorySkillStatStmt, upsertMemorySkillStat, arg.SkillName, arg.SuccessCount, arg.UpdatedAt)
	return err
}
