// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory_items.sql

package db

import (
	"context"
	"database/sql"
)

const deleteMemoryItem = `-- name: DeleteMemoryItem :exec
DELETE FROM memory_items WHERE id = ?
`

func (q *Queries) DeleteMemoryItem(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteMemoryItemStmt, deleteMemoryItem, id)
	return err
}

const getMemoryItem = `-- name: GetMemoryItem :one
SELECT id, session_id, content, metadata, access_count, operation_history, created_at, updated_at FROM memory_items WHERE id = ?
`

func (q *Queries) GetMemoryItem(ctx context.Context, id string) (MemoryItem, error) {
	row := q.queryRow(ctx, q.getMemoryItemStmt, getMemoryItem, id)
	var i MemoryItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Content,
		&i.Metadata,
		&i.AccessCount,
		&i.OperationHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementMemoryAccessCount = `-- name: IncrementMemoryAccessCount :exec
UPDATE memory_items SET access_count = access_count + 1 WHERE id = ?
`

func (q *Queries) IncrementMemoryAccessCount(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.incrementMemoryAccessCountStmt, incrementMemoryAccessCount, id)
	return err
}

const insertMemoryItem = `-- name: InsertMemoryItem :exec
INSERT INTO memory_items (
    id, session_id, content, metadata, access_count, operation_history, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMemoryItemParams struct {
	ID               string         `json:"id"`
	SessionID        sql.NullString `json:"session_id"`
	Content          string         `json:"content"`
	Metadata         string         `json:"metadata"`
	AccessCount      int64          `json:"access_count"`
	OperationHistory string         `json:"operation_history"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

func (q *Queries) InsertMemoryItem(ctx context.Context, arg InsertMemoryItemParams) error {
	_, err := q.exec(ctx, q.insertMemoryItemStmt, insertMemoryItem,
		arg.ID,
		arg.SessionID,
		arg.Content,
		arg.Metadata,
		arg.AccessCount,
		arg.OperationHistory,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listGlobalMemoryItems = `-- name: ListGlobalMemoryItems :many
SELECT id, session_id, content, metadata, access_count, operation_history, created_at, updated_at FROM memory_items
WHERE session_id IS NULL
ORDER BY updated_at DESC
LIMIT ?
`

func (q *Queries) ListGlobalMemoryItems(ctx context.Context, limit int64) ([]MemoryItem, error) {
	rows, err := q.query(ctx, q.listGlobalMemoryItemsStmt, listGlobalMemoryItems, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryItem{}
	for rows.Next() {
		var i MemoryItem
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.Metadata,
			&i.AccessCount,
			&i.OperationHistory,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryItemsForSession = `-- name: ListMemoryItemsForSession :many
SELECT id, session_id, content, metadata, access_count, operation_history, created_at, updated_at FROM memory_items
WHERE session_id = ? OR session_id IS NULL
ORDER BY updated_at DESC
LIMIT ?
`

type ListMemoryItemsForSessionParams struct {
	SessionID sql.NullString `json:"session_id"`
	Limit     int64          `json:"limit"`
}

func (q *Queries) ListMemoryItemsForSession(ctx context.Context, arg ListMemoryItemsForSessionParams) ([]MemoryItem, error) {
	rows, err := q.query(ctx, q.listMemoryItemsForSessionStmt, listMemoryItemsForSession, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryItem{}
	for rows.Next() {
		var i MemoryItem
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.Metadata,
			&i.AccessCount,
			&i.OperationHistory,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMemoryItems = `-- name: ListRecentMemoryItems :many
SELECT id, session_id, content, metadata, access_count, operation_history, created_at, updated_at FROM memory_items
ORDER BY updated_at DESC
LIMIT ?
`

func (q *Queries) ListRecentMemoryItems(ctx context.Context, limit int64) ([]MemoryItem, error) {
	rows, err := q.query(ctx, q.listRecentMemoryItemsStmt, listRecentMemoryItems, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryItem{}
	for rows.Next() {
		var i MemoryItem
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.Metadata,
			&i.AccessCount,
			&i.OperationHistory,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionMemoryItems = `-- name: ListSessionMemoryItems :many
SELECT id, session_id, content, metadata, access_count, operation_history, created_at, updated_at FROM memory_items
WHERE session_id = ?
ORDER BY updated_at DESC
LIMIT ?
`

type ListSessionMemoryItemsParams struct {
	SessionID sql.NullString `json:"session_id"`
	Limit     int64          `json:"limit"`
}

func (q *Queries) ListSessionMemoryItems(ctx context.Context, arg ListSessionMemoryItemsParams) ([]MemoryItem, error) {
	rows, err := q.query(ctx, q.listSessionMemoryItemsStmt, listSessionMemoryItems, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryItem{}
	for rows.Next() {
		var i MemoryItem
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.Metadata,
			&i.AccessCount,
			&i.OperationHistory,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemoryItem = `-- name: UpdateMemoryItem :exec
UPDATE memory_items SET content = ?, metadata = ? WHERE id = ?
`

type UpdateMemoryItemParams struct {
	Content  string `json:"content"`
	Metadata string `json:"metadata"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateMemoryItem(ctx context.Context, arg UpdateMemoryItemParams) error {
	_, err := q.exec(ctx, q.updateMemoryItemStmt, updateMemoryItem, arg.Content, arg.Metadata, arg.ID)
	return err
}
