// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"
)

const backfillMessageSearchText = `-- name: BackfillMessageSearchText :exec
UPDATE messages
SET search_text = ?
WHERE id = ?
`

type BackfillMessageSearchTextParams struct {
	SearchText string `json:"search_text"`
	ID         string `json:"id"`
}

func (q *Queries) BackfillMessageSearchText(ctx context.Context, arg BackfillMessageSearchTextParams) error {
	_, err := q.exec(ctx, q.backfillMessageSearchTextStmt, backfillMessageSearchText, arg.SearchText, arg.ID)
	return err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id,
    session_id,
    role,
    parts,
    search_text,
    model,
    input_tokens,
    output_tokens,
    cache_creation_input_tokens,
    cache_read_input_tokens,
    meta,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now')
)
RETURNING id, session_id, role, parts, model, created_at, updated_at, finished_at, input_tokens, output_tokens, cache_creation_input_tokens, cache_read_input_tokens, meta, search_text
`

type CreateMessageParams struct {
	ID                       string         `json:"id"`
	SessionID                string         `json:"session_id"`
	Role                     string         `json:"role"`
	Parts                    string         `json:"parts"`
	SearchText               string         `json:"search_text"`
	Model                    sql.NullString `json:"model"`
	InputTokens              int64          `json:"input_tokens"`
	OutputTokens             int64          `json:"output_tokens"`
	CacheCreationInputTokens int64          `json:"cache_creation_input_tokens"`
	CacheReadInputTokens     int64          `json:"cache_read_input_tokens"`
	Meta                     string         `json:"meta"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.queryRow(ctx, q.createMessageStmt, createMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.Parts,
		arg.SearchText,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheCreationInputTokens,
		arg.CacheReadInputTokens,
		arg.Meta,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheCreationInputTokens,
		&i.CacheReadInputTokens,
		&i.Meta,
		&i.SearchText,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = ?
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteMessageStmt, deleteMessage, id)
	return err
}

const deleteSessionMessages = `-- name: DeleteSessionMessages :exec
DELETE FROM messages
WHERE session_id = ?
`

func (q *Queries) DeleteSessionMessages(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteSessionMessagesStmt, deleteSessionMessages, sessionID)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT
    id,
    session_id,
    role,
    parts,
    search_text,
    model,
    created_at,
    updated_at,
    finished_at,
    input_tokens,
    output_tokens,
    cache_creation_input_tokens,
    cache_read_input_tokens,
    meta
FROM messages
WHERE id = ? LIMIT 1
`

type GetMessageRow struct {
	ID                       string         `json:"id"`
	SessionID                string         `json:"session_id"`
	Role                     string         `json:"role"`
	Parts                    string         `json:"parts"`
	SearchText               string         `json:"search_text"`
	Model                    sql.NullString `json:"model"`
	CreatedAt                int64          `json:"created_at"`
	UpdatedAt                int64          `json:"updated_at"`
	FinishedAt               sql.NullInt64  `json:"finished_at"`
	InputTokens              int64          `json:"input_tokens"`
	OutputTokens             int64          `json:"output_tokens"`
	CacheCreationInputTokens int64          `json:"cache_creation_input_tokens"`
	CacheReadInputTokens     int64          `json:"cache_read_input_tokens"`
	Meta                     string         `json:"meta"`
}

func (q *Queries) GetMessage(ctx context.Context, id string) (GetMessageRow, error) {
	row := q.queryRow(ctx, q.getMessageStmt, getMessage, id)
	var i GetMessageRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Parts,
		&i.SearchText,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheCreationInputTokens,
		&i.CacheReadInputTokens,
		&i.Meta,
	)
	return i, err
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
SELECT
    id,
    session_id,
    role,
    parts,
    search_text,
    model,
    created_at,
    updated_at,
    finished_at,
    input_tokens,
    output_tokens,
    cache_creation_input_tokens,
    cache_read_input_tokens,
    meta
FROM messages
WHERE session_id = ?
ORDER BY created_at ASC
`

type ListMessagesBySessionRow struct {
	ID                       string         `json:"id"`
	SessionID                string         `json:"session_id"`
	Role                     string         `json:"role"`
	Parts                    string         `json:"parts"`
	SearchText               string         `json:"search_text"`
	Model                    sql.NullString `json:"model"`
	CreatedAt                int64          `json:"created_at"`
	UpdatedAt                int64          `json:"updated_at"`
	FinishedAt               sql.NullInt64  `json:"finished_at"`
	InputTokens              int64          `json:"input_tokens"`
	OutputTokens             int64          `json:"output_tokens"`
	CacheCreationInputTokens int64          `json:"cache_creation_input_tokens"`
	CacheReadInputTokens     int64          `json:"cache_read_input_tokens"`
	Meta                     string         `json:"meta"`
}

func (q *Queries) ListMessagesBySession(ctx context.Context, sessionID string) ([]ListMessagesBySessionRow, error) {
	rows, err := q.query(ctx, q.listMessagesBySessionStmt, listMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesBySessionRow{}
	for rows.Next() {
		var i ListMessagesBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.SearchText,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheCreationInputTokens,
			&i.CacheReadInputTokens,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesMissingSearchText = `-- name: ListMessagesMissingSearchText :many
SELECT
    id,
    session_id,
    role,
    parts,
    search_text,
    model,
    created_at,
    updated_at,
    finished_at,
    input_tokens,
    output_tokens,
    cache_creation_input_tokens,
    cache_read_input_tokens,
    meta
FROM messages
WHERE search_text = ''
ORDER BY created_at ASC, id ASC
LIMIT ?
`

type ListMessagesMissingSearchTextRow struct {
	ID                       string         `json:"id"`
	SessionID                string         `json:"session_id"`
	Role                     string         `json:"role"`
	Parts                    string         `json:"parts"`
	SearchText               string         `json:"search_text"`
	Model                    sql.NullString `json:"model"`
	CreatedAt                int64          `json:"created_at"`
	UpdatedAt                int64          `json:"updated_at"`
	FinishedAt               sql.NullInt64  `json:"finished_at"`
	InputTokens              int64          `json:"input_tokens"`
	OutputTokens             int64          `json:"output_tokens"`
	CacheCreationInputTokens int64          `json:"cache_creation_input_tokens"`
	CacheReadInputTokens     int64          `json:"cache_read_input_tokens"`
	Meta                     string         `json:"meta"`
}

func (q *Queries) ListMessagesMissingSearchText(ctx context.Context, limit int64) ([]ListMessagesMissingSearchTextRow, error) {
	rows, err := q.query(ctx, q.listMessagesMissingSearchTextStmt, listMessagesMissingSearchText, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesMissingSearchTextRow{}
	for rows.Next() {
		var i ListMessagesMissingSearchTextRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.SearchText,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheCreationInputTokens,
			&i.CacheReadInputTokens,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesMissingSearchTextForResumeSearch = `-- name: ListMessagesMissingSearchTextForResumeSearch :many
SELECT
    m.id,
    m.session_id,
    m.role,
    m.parts,
    m.search_text,
    m.model,
    m.created_at,
    m.updated_at,
    m.finished_at,
    m.input_tokens,
    m.output_tokens,
    m.cache_creation_input_tokens,
    m.cache_read_input_tokens,
    m.meta
FROM messages m
JOIN sessions hit ON hit.id = m.session_id
LEFT JOIN sessions root ON root.id = COALESCE(NULLIF(hit.root_session_id, ''), hit.parent_session_id, hit.id)
WHERE m.search_text = ''
  AND (?1 = '' OR instr(lower(m.parts), lower(?1)) > 0)
  AND (?2 = '' OR instr(lower(m.parts), lower(?2)) > 0)
  AND (?3 = '' OR instr(lower(m.parts), lower(?3)) > 0)
  AND (?4 = '' OR instr(lower(m.parts), lower(?4)) > 0)
  AND (?5 = '' OR instr(lower(m.parts), lower(?5)) > 0)
  AND (?6 = '' OR root.project_path = '' OR root.project_path = ?6)
ORDER BY m.updated_at DESC, m.id ASC
LIMIT ?7
`

type ListMessagesMissingSearchTextForResumeSearchParams struct {
	Token1      interface{} `json:"token_1"`
	Token2      interface{} `json:"token_2"`
	Token3      interface{} `json:"token_3"`
	Token4      interface{} `json:"token_4"`
	Token5      interface{} `json:"token_5"`
	ProjectPath interface{} `json:"project_path"`
	Limit       int64       `json:"limit"`
}

type ListMessagesMissingSearchTextForResumeSearchRow struct {
	ID                       string         `json:"id"`
	SessionID                string         `json:"session_id"`
	Role                     string         `json:"role"`
	Parts                    string         `json:"parts"`
	SearchText               string         `json:"search_text"`
	Model                    sql.NullString `json:"model"`
	CreatedAt                int64          `json:"created_at"`
	UpdatedAt                int64          `json:"updated_at"`
	FinishedAt               sql.NullInt64  `json:"finished_at"`
	InputTokens              int64          `json:"input_tokens"`
	OutputTokens             int64          `json:"output_tokens"`
	CacheCreationInputTokens int64          `json:"cache_creation_input_tokens"`
	CacheReadInputTokens     int64          `json:"cache_read_input_tokens"`
	Meta                     string         `json:"meta"`
}

func (q *Queries) ListMessagesMissingSearchTextForResumeSearch(ctx context.Context, arg ListMessagesMissingSearchTextForResumeSearchParams) ([]ListMessagesMissingSearchTextForResumeSearchRow, error) {
	rows, err := q.query(ctx, q.listMessagesMissingSearchTextForResumeSearchStmt, listMessagesMissingSearchTextForResumeSearch,
		arg.Token1,
		arg.Token2,
		arg.Token3,
		arg.Token4,
		arg.Token5,
		arg.ProjectPath,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesMissingSearchTextForResumeSearchRow{}
	for rows.Next() {
		var i ListMessagesMissingSearchTextForResumeSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.SearchText,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheCreationInputTokens,
			&i.CacheReadInputTokens,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRootSessionsByMessageFTS = `-- name: SearchRootSessionsByMessageFTS :many
WITH RECURSIVE ancestors(id, parent_session_id, updated_at, project_path, depth) AS (
    SELECT
        hit.id,
        hit.parent_session_id,
        hit.updated_at,
        hit.project_path,
        0
    FROM messages_fts mf
    JOIN messages m ON m.id = mf.message_id
    JOIN sessions hit ON hit.id = m.session_id
    WHERE mf.search_text MATCH ?3

    UNION ALL

    SELECT
        parent.id,
        parent.parent_session_id,
        parent.updated_at,
        parent.project_path,
        ancestors.depth + 1
    FROM ancestors
    JOIN sessions parent ON parent.id = ancestors.parent_session_id
    WHERE ancestors.parent_session_id IS NOT NULL
      AND ancestors.parent_session_id != ''
      AND ancestors.depth < 32
)
SELECT id
FROM ancestors
WHERE (parent_session_id IS NULL OR parent_session_id = '')
  AND (?1 = '' OR project_path = '' OR project_path = ?1)
GROUP BY id
ORDER BY MAX(updated_at) DESC
LIMIT ?2
`

type SearchRootSessionsByMessageFTSParams struct {
	ProjectPath interface{} `json:"project_path"`
	Limit       int64       `json:"limit"`
	Query       string      `json:"query"`
}

func (q *Queries) SearchRootSessionsByMessageFTS(ctx context.Context, arg SearchRootSessionsByMessageFTSParams) ([]string, error) {
	rows, err := q.query(ctx, q.searchRootSessionsByMessageFTSStmt, searchRootSessionsByMessageFTS, arg.ProjectPath, arg.Limit, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE messages
SET
    parts = ?,
    search_text = ?,
    finished_at = ?,
    input_tokens = ?,
    output_tokens = ?,
    cache_creation_input_tokens = ?,
    cache_read_input_tokens = ?,
    meta = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateMessageParams struct {
	Parts                    string        `json:"parts"`
	SearchText               string        `json:"search_text"`
	FinishedAt               sql.NullInt64 `json:"finished_at"`
	InputTokens              int64         `json:"input_tokens"`
	OutputTokens             int64         `json:"output_tokens"`
	CacheCreationInputTokens int64         `json:"cache_creation_input_tokens"`
	CacheReadInputTokens     int64         `json:"cache_read_input_tokens"`
	Meta                     string        `json:"meta"`
	ID                       string        `json:"id"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.exec(ctx, q.updateMessageStmt, updateMessage,
		arg.Parts,
		arg.SearchText,
		arg.FinishedAt,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheCreationInputTokens,
		arg.CacheReadInputTokens,
		arg.Meta,
		arg.ID,
	)
	return err
}
