// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type BatchJob struct {
	ID           string         `json:"id"`
	FilePath     string         `json:"file_path"`
	Status       string         `json:"status"`
	Error        sql.NullString `json:"error"`
	PaperID      sql.NullString `json:"paper_id"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
	AttemptCount int64          `json:"attempt_count"`
	MaxAttempts  int64          `json:"max_attempts"`
}

type BibEntry struct {
	ID                string         `json:"id"`
	SessionID         string         `json:"session_id"`
	Title             string         `json:"title"`
	Authors           string         `json:"authors"`
	Year              sql.NullInt64  `json:"year"`
	Venue             sql.NullString `json:"venue"`
	Abstract          sql.NullString `json:"abstract"`
	Doi               sql.NullString `json:"doi"`
	ArxivID           sql.NullString `json:"arxiv_id"`
	SemanticScholarID sql.NullString `json:"semantic_scholar_id"`
	CiteKey           string         `json:"cite_key"`
	BibType           string         `json:"bib_type"`
	CreatedAt         int64          `json:"created_at"`
	UpdatedAt         int64          `json:"updated_at"`
}

type DocxDiagnostic struct {
	ID           int64          `json:"id"`
	DocumentID   int64          `json:"document_id"`
	VersionID    sql.NullInt64  `json:"version_id"`
	RuleID       string         `json:"rule_id"`
	Level        string         `json:"level"`
	LocationJson sql.NullString `json:"location_json"`
	Message      string         `json:"message"`
	Suggestion   sql.NullString `json:"suggestion"`
	AutoFix      int64          `json:"auto_fix"`
	CreatedAt    int64          `json:"created_at"`
}

type DocxDocument struct {
	ID          int64          `json:"id"`
	PipelineID  sql.NullInt64  `json:"pipeline_id"`
	DocType     string         `json:"doc_type"`
	TemplateID  sql.NullString `json:"template_id"`
	TemplateVer sql.NullString `json:"template_ver"`
	State       string         `json:"state"`
	SourcePath  sql.NullString `json:"source_path"`
	DocxPath    sql.NullString `json:"docx_path"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

type DocxExport struct {
	ID         int64          `json:"id"`
	DocumentID int64          `json:"document_id"`
	Format     string         `json:"format"`
	Engine     sql.NullString `json:"engine"`
	ParamsJson sql.NullString `json:"params_json"`
	OutputPath string         `json:"output_path"`
	Success    int64          `json:"success"`
	ErrorMsg   sql.NullString `json:"error_msg"`
	CreatedAt  int64          `json:"created_at"`
}

type DocxMaterial struct {
	ID         int64         `json:"id"`
	DocumentID int64         `json:"document_id"`
	SourcePath string        `json:"source_path"`
	DocType    string        `json:"doc_type"`
	Parsed     int64         `json:"parsed"`
	ParsedAt   sql.NullInt64 `json:"parsed_at"`
	CreatedAt  int64         `json:"created_at"`
}

type DocxVersion struct {
	ID           int64          `json:"id"`
	DocumentID   int64          `json:"document_id"`
	Phase        string         `json:"phase"`
	SnapshotPath string         `json:"snapshot_path"`
	CreatedBy    string         `json:"created_by"`
	Description  sql.NullString `json:"description"`
	CreatedAt    int64          `json:"created_at"`
}

type EvolutionCase struct {
	ID           string         `json:"id"`
	SessionID    string         `json:"session_id"`
	SkillID      sql.NullString `json:"skill_id"`
	UserRequest  string         `json:"user_request"`
	AgentOutput  sql.NullString `json:"agent_output"`
	Feedback     string         `json:"feedback"`
	FeedbackType string         `json:"feedback_type"`
	Status       string         `json:"status"`
	Resolution   sql.NullString `json:"resolution"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

type ExperimentNode struct {
	ID          string          `json:"id"`
	ParentID    sql.NullString  `json:"parent_id"`
	PipelineID  string          `json:"pipeline_id"`
	NodeType    string          `json:"node_type"`
	Status      string          `json:"status"`
	Description sql.NullString  `json:"description"`
	CodePath    sql.NullString  `json:"code_path"`
	Metrics     sql.NullString  `json:"metrics"`
	ErrorLog    sql.NullString  `json:"error_log"`
	Score       sql.NullFloat64 `json:"score"`
	Depth       sql.NullInt64   `json:"depth"`
	CreatedAt   int64           `json:"created_at"`
}

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   string `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type KbTask struct {
	TaskID       string          `json:"task_id"`
	PaperID      sql.NullString  `json:"paper_id"`
	TaskType     string          `json:"task_type"`
	Status       string          `json:"status"`
	Progress     sql.NullFloat64 `json:"progress"`
	InputJson    sql.NullString  `json:"input_json"`
	ResultJson   sql.NullString  `json:"result_json"`
	ResultRef    sql.NullString  `json:"result_ref"`
	Error        sql.NullString  `json:"error"`
	LeaseOwner   sql.NullString  `json:"lease_owner"`
	LeaseUntil   sql.NullInt64   `json:"lease_until"`
	AttemptCount int64           `json:"attempt_count"`
	CreatedAt    int64           `json:"created_at"`
	UpdatedAt    int64           `json:"updated_at"`
	StartedAt    sql.NullInt64   `json:"started_at"`
	FinishedAt   sql.NullInt64   `json:"finished_at"`
}

type KbUsageStat struct {
	ID         int64          `json:"id"`
	PaperID    sql.NullString `json:"paper_id"`
	NodeID     sql.NullString `json:"node_id"`
	Query      string         `json:"query"`
	SearchType string         `json:"search_type"`
	CreatedAt  int64          `json:"created_at"`
}

type MemoryItem struct {
	ID               string         `json:"id"`
	SessionID        sql.NullString `json:"session_id"`
	Content          string         `json:"content"`
	Metadata         string         `json:"metadata"`
	AccessCount      int64          `json:"access_count"`
	OperationHistory string         `json:"operation_history"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

type MemorySkillStat struct {
	SkillName    string `json:"skill_name"`
	UsageCount   int64  `json:"usage_count"`
	SuccessCount int64  `json:"success_count"`
	UpdatedAt    int64  `json:"updated_at"`
}

type Message struct {
	ID                       string         `json:"id"`
	SessionID                string         `json:"session_id"`
	Role                     string         `json:"role"`
	Parts                    string         `json:"parts"`
	Model                    sql.NullString `json:"model"`
	CreatedAt                int64          `json:"created_at"`
	UpdatedAt                int64          `json:"updated_at"`
	FinishedAt               sql.NullInt64  `json:"finished_at"`
	InputTokens              int64          `json:"input_tokens"`
	OutputTokens             int64          `json:"output_tokens"`
	CacheCreationInputTokens int64          `json:"cache_creation_input_tokens"`
	CacheReadInputTokens     int64          `json:"cache_read_input_tokens"`
	Meta                     string         `json:"meta"`
	SearchText               string         `json:"search_text"`
}

type MessagesFt struct {
	MessageID  string `json:"message_id"`
	SessionID  string `json:"session_id"`
	Role       string `json:"role"`
	SearchText string `json:"search_text"`
}

type NodeContent struct {
	PaperID    string         `json:"paper_id"`
	NodeID     string         `json:"node_id"`
	Content    string         `json:"content"`
	TokenCount sql.NullInt64  `json:"token_count"`
	Source     sql.NullString `json:"source"`
	CreatedAt  sql.NullInt64  `json:"created_at"`
}

type NodeContentsFt struct {
	PaperID string `json:"paper_id"`
	NodeID  string `json:"node_id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type NodeEmbedding struct {
	PaperID    string `json:"paper_id"`
	NodeID     string `json:"node_id"`
	Embedding  []byte `json:"embedding"`
	Model      string `json:"model"`
	Dimensions int64  `json:"dimensions"`
	CreatedAt  int64  `json:"created_at"`
}

type NodeSummariesFt struct {
	PaperID string `json:"paper_id"`
	NodeID  string `json:"node_id"`
	Title   string `json:"title"`
	Summary string `json:"summary"`
}

type NodeSummary struct {
	PaperID   sql.NullString `json:"paper_id"`
	NodeID    sql.NullString `json:"node_id"`
	Title     sql.NullString `json:"title"`
	StartPage sql.NullInt64  `json:"start_page"`
	EndPage   sql.NullInt64  `json:"end_page"`
	Summary   string         `json:"summary"`
}

type Paper struct {
	PaperID   string         `json:"paper_id"`
	Title     string         `json:"title"`
	Authors   sql.NullString `json:"authors"`
	Year      sql.NullInt64  `json:"year"`
	Venue     sql.NullString `json:"venue"`
	Abstract  sql.NullString `json:"abstract"`
	Doi       sql.NullString `json:"doi"`
	ArxivID   sql.NullString `json:"arxiv_id"`
	PdfPath   sql.NullString `json:"pdf_path"`
	IndexedAt sql.NullInt64  `json:"indexed_at"`
	FilePath  sql.NullString `json:"file_path"`
	DocType   sql.NullString `json:"doc_type"`
}

type PaperChunk struct {
	PaperID    string         `json:"paper_id"`
	ChunkID    string         `json:"chunk_id"`
	Kind       string         `json:"kind"`
	PageStart  sql.NullInt64  `json:"page_start"`
	PageEnd    sql.NullInt64  `json:"page_end"`
	Title      sql.NullString `json:"title"`
	Content    string         `json:"content"`
	TokenCount sql.NullInt64  `json:"token_count"`
	Source     sql.NullString `json:"source"`
	CreatedAt  int64          `json:"created_at"`
}

type PaperChunksFt struct {
	PaperID   string `json:"paper_id"`
	ChunkID   string `json:"chunk_id"`
	Kind      string `json:"kind"`
	PageStart string `json:"page_start"`
	PageEnd   string `json:"page_end"`
	Title     string `json:"title"`
	Content   string `json:"content"`
}

type PaperEmbedding struct {
	PaperID    string `json:"paper_id"`
	Embedding  []byte `json:"embedding"`
	Model      string `json:"model"`
	Dimensions int64  `json:"dimensions"`
	CreatedAt  int64  `json:"created_at"`
}

type PaperIndexState struct {
	PaperID                string         `json:"paper_id"`
	IndexLevel             sql.NullString `json:"index_level"`
	RawParseStatus         sql.NullString `json:"raw_parse_status"`
	ContentAvailable       int64          `json:"content_available"`
	ContentBytes           int64          `json:"content_bytes"`
	FlatPageIndexAvailable int64          `json:"flat_page_index_available"`
	FtsStatus              sql.NullString `json:"fts_status"`
	SemanticTreeStatus     sql.NullString `json:"semantic_tree_status"`
	SemanticTreeAvailable  int64          `json:"semantic_tree_available"`
	SemanticTreeError      sql.NullString `json:"semantic_tree_error"`
	SemanticTreeTaskID     sql.NullString `json:"semantic_tree_task_id"`
	Extractor              sql.NullString `json:"extractor"`
	FallbackReason         sql.NullString `json:"fallback_reason"`
	TotalPages             sql.NullInt64  `json:"total_pages"`
	TotalTokens            sql.NullInt64  `json:"total_tokens"`
	SourceFileAvailable    sql.NullInt64  `json:"source_file_available"`
	FileHash               sql.NullString `json:"file_hash"`
	UpdatedAt              int64          `json:"updated_at"`
}

type PaperRelation struct {
	PaperIDA     string  `json:"paper_id_a"`
	PaperIDB     string  `json:"paper_id_b"`
	RelationType string  `json:"relation_type"`
	Weight       float64 `json:"weight"`
	UpdatedAt    int64   `json:"updated_at"`
}

type PaperTree struct {
	PaperID        string         `json:"paper_id"`
	TreeJson       string         `json:"tree_json"`
	DocDescription sql.NullString `json:"doc_description"`
	TotalPages     sql.NullInt64  `json:"total_pages"`
	TotalTokens    sql.NullInt64  `json:"total_tokens"`
	ModelUsed      sql.NullString `json:"model_used"`
	Version        sql.NullInt64  `json:"version"`
	CreatedAt      sql.NullInt64  `json:"created_at"`
	IndexMetadata  string         `json:"index_metadata"`
}

type PapersFt struct {
	PaperID  string `json:"paper_id"`
	Title    string `json:"title"`
	Abstract string `json:"abstract"`
	Authors  string `json:"authors"`
}

type PermissionRule struct {
	ID        string `json:"id"`
	ToolName  string `json:"tool_name"`
	Action    string `json:"action"`
	Path      string `json:"path"`
	Decision  string `json:"decision"`
	Scope     string `json:"scope"`
	CreatedAt int64  `json:"created_at"`
}

type Pipeline struct {
	ID          string          `json:"id"`
	SessionID   string          `json:"session_id"`
	Topic       string          `json:"topic"`
	Template    string          `json:"template"`
	Mode        string          `json:"mode"`
	Status      string          `json:"status"`
	BudgetLimit sql.NullFloat64 `json:"budget_limit"`
	BudgetSpent sql.NullFloat64 `json:"budget_spent"`
	WorkDir     string          `json:"work_dir"`
	CreatedAt   int64           `json:"created_at"`
	UpdatedAt   int64           `json:"updated_at"`
}

type PipelineEvent struct {
	ID         int64          `json:"id"`
	PipelineID string         `json:"pipeline_id"`
	EventType  string         `json:"event_type"`
	Payload    sql.NullString `json:"payload"`
	CreatedAt  int64          `json:"created_at"`
}

type PipelinePhase struct {
	ID          string        `json:"id"`
	PipelineID  string        `json:"pipeline_id"`
	Name        string        `json:"name"`
	PhaseOrder  int64         `json:"phase_order"`
	Status      string        `json:"status"`
	Checkpoint  int64         `json:"checkpoint"`
	MaxWorkers  int64         `json:"max_workers"`
	CreatedAt   int64         `json:"created_at"`
	CompletedAt sql.NullInt64 `json:"completed_at"`
}

type ResearchTopic struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	PaperIds    string         `json:"paper_ids"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

type Session struct {
	ID                  string         `json:"id"`
	ParentSessionID     sql.NullString `json:"parent_session_id"`
	Title               string         `json:"title"`
	MessageCount        int64          `json:"message_count"`
	PromptTokens        int64          `json:"prompt_tokens"`
	CompletionTokens    int64          `json:"completion_tokens"`
	Cost                float64        `json:"cost"`
	SummaryMessageID    sql.NullString `json:"summary_message_id"`
	UpdatedAt           int64          `json:"updated_at"`
	CreatedAt           int64          `json:"created_at"`
	Summary             sql.NullString `json:"summary"`
	Tags                sql.NullString `json:"tags"`
	FirstPrompt         sql.NullString `json:"first_prompt"`
	GitBranch           sql.NullString `json:"git_branch"`
	ProjectPath         string         `json:"project_path"`
	WorktreePath        string         `json:"worktree_path"`
	Mode                string         `json:"mode"`
	RootSessionID       string         `json:"root_session_id"`
	ForkedFromSessionID string         `json:"forked_from_session_id"`
}

type SkillSnapshot struct {
	ID        string         `json:"id"`
	SkillID   string         `json:"skill_id"`
	Version   int64          `json:"version"`
	Content   string         `json:"content"`
	Reason    sql.NullString `json:"reason"`
	CreatedAt int64          `json:"created_at"`
}

type SkillSource struct {
	ID          string `json:"id"`
	SkillID     string `json:"skill_id"`
	SourceTier  string `json:"source_tier"`
	SourceKind  string `json:"source_kind"`
	SourceKey   string `json:"source_key"`
	DisplayName string `json:"display_name"`
	FilePath    string `json:"file_path"`
	MetaJson    string `json:"meta_json"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type SkillsFt struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Tags        string `json:"tags"`
	Content     string `json:"content"`
}

type SkillsIndex struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	Description      string `json:"description"`
	Category         string `json:"category"`
	Tags             string `json:"tags"`
	Version          int64  `json:"version"`
	Author           string `json:"author"`
	UsageCount       int64  `json:"usage_count"`
	SuccessCount     int64  `json:"success_count"`
	FilePath         string `json:"file_path"`
	CreatedAt        int64  `json:"created_at"`
	UpdatedAt        int64  `json:"updated_at"`
	MetaJson         string `json:"meta_json"`
	ResolvedSourceID string `json:"resolved_source_id"`
}
