// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: node_contents.sql

package db

import (
	"context"
	"database/sql"
)

const countNodeContents = `-- name: CountNodeContents :one
SELECT COUNT(*) FROM node_contents WHERE paper_id = ?
`

func (q *Queries) CountNodeContents(ctx context.Context, paperID string) (int64, error) {
	row := q.queryRow(ctx, q.countNodeContentsStmt, countNodeContents, paperID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteNodeContents = `-- name: DeleteNodeContents :exec
DELETE FROM node_contents WHERE paper_id = ?
`

func (q *Queries) DeleteNodeContents(ctx context.Context, paperID string) error {
	_, err := q.exec(ctx, q.deleteNodeContentsStmt, deleteNodeContents, paperID)
	return err
}

const getNodeContent = `-- name: GetNodeContent :one
SELECT paper_id, node_id, content, token_count, source, created_at FROM node_contents WHERE paper_id = ? AND node_id = ?
`

type GetNodeContentParams struct {
	PaperID string `json:"paper_id"`
	NodeID  string `json:"node_id"`
}

func (q *Queries) GetNodeContent(ctx context.Context, arg GetNodeContentParams) (NodeContent, error) {
	row := q.queryRow(ctx, q.getNodeContentStmt, getNodeContent, arg.PaperID, arg.NodeID)
	var i NodeContent
	err := row.Scan(
		&i.PaperID,
		&i.NodeID,
		&i.Content,
		&i.TokenCount,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const getNodeContents = `-- name: GetNodeContents :many
SELECT paper_id, node_id, content, token_count, source, created_at FROM node_contents WHERE paper_id = ? ORDER BY node_id
`

func (q *Queries) GetNodeContents(ctx context.Context, paperID string) ([]NodeContent, error) {
	rows, err := q.query(ctx, q.getNodeContentsStmt, getNodeContents, paperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeContent{}
	for rows.Next() {
		var i NodeContent
		if err := rows.Scan(
			&i.PaperID,
			&i.NodeID,
			&i.Content,
			&i.TokenCount,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNodeContent = `-- name: InsertNodeContent :exec
INSERT INTO node_contents (
    paper_id, node_id, content, token_count, source
) VALUES (?, ?, ?, ?, ?)
`

type InsertNodeContentParams struct {
	PaperID    string         `json:"paper_id"`
	NodeID     string         `json:"node_id"`
	Content    string         `json:"content"`
	TokenCount sql.NullInt64  `json:"token_count"`
	Source     sql.NullString `json:"source"`
}

func (q *Queries) InsertNodeContent(ctx context.Context, arg InsertNodeContentParams) error {
	_, err := q.exec(ctx, q.insertNodeContentStmt, insertNodeContent,
		arg.PaperID,
		arg.NodeID,
		arg.Content,
		arg.TokenCount,
		arg.Source,
	)
	return err
}

const searchNodeContents = `-- name: SearchNodeContents :many
SELECT
    nc.paper_id,
    nc.node_id,
    ns.title,
    nc.content,
    nc.token_count,
    nc.source,
    nc.created_at
FROM node_contents_fts f
JOIN node_contents nc ON nc.rowid = f.rowid
JOIN node_summaries ns
  ON ns.paper_id = nc.paper_id
 AND ns.node_id = nc.node_id
WHERE f.paper_id = ?1
  AND f.content MATCH ?2
ORDER BY bm25(node_contents_fts), nc.node_id
LIMIT ?3
`

type SearchNodeContentsParams struct {
	PaperID string `json:"paper_id"`
	Query   string `json:"query"`
	Limit   int64  `json:"limit"`
}

type SearchNodeContentsRow struct {
	PaperID    string         `json:"paper_id"`
	NodeID     string         `json:"node_id"`
	Title      sql.NullString `json:"title"`
	Content    string         `json:"content"`
	TokenCount sql.NullInt64  `json:"token_count"`
	Source     sql.NullString `json:"source"`
	CreatedAt  sql.NullInt64  `json:"created_at"`
}

func (q *Queries) SearchNodeContents(ctx context.Context, arg SearchNodeContentsParams) ([]SearchNodeContentsRow, error) {
	rows, err := q.query(ctx, q.searchNodeContentsStmt, searchNodeContents, arg.PaperID, arg.Query, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchNodeContentsRow{}
	for rows.Next() {
		var i SearchNodeContentsRow
		if err := rows.Scan(
			&i.PaperID,
			&i.NodeID,
			&i.Title,
			&i.Content,
			&i.TokenCount,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
