// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: node_summaries.sql

package db

import (
	"context"
	"database/sql"
)

const deleteNodeSummaries = `-- name: DeleteNodeSummaries :exec
DELETE FROM node_summaries WHERE paper_id = ?
`

func (q *Queries) DeleteNodeSummaries(ctx context.Context, paperID sql.NullString) error {
	_, err := q.exec(ctx, q.deleteNodeSummariesStmt, deleteNodeSummaries, paperID)
	return err
}

const getNodeSummaries = `-- name: GetNodeSummaries :many
SELECT paper_id, node_id, title, start_page, end_page, summary FROM node_summaries WHERE paper_id = ? ORDER BY node_id
`

func (q *Queries) GetNodeSummaries(ctx context.Context, paperID sql.NullString) ([]NodeSummary, error) {
	rows, err := q.query(ctx, q.getNodeSummariesStmt, getNodeSummaries, paperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeSummary{}
	for rows.Next() {
		var i NodeSummary
		if err := rows.Scan(
			&i.PaperID,
			&i.NodeID,
			&i.Title,
			&i.StartPage,
			&i.EndPage,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNodeSummary = `-- name: GetNodeSummary :one
SELECT paper_id, node_id, title, start_page, end_page, summary FROM node_summaries WHERE paper_id = ? AND node_id = ?
`

type GetNodeSummaryParams struct {
	PaperID sql.NullString `json:"paper_id"`
	NodeID  sql.NullString `json:"node_id"`
}

func (q *Queries) GetNodeSummary(ctx context.Context, arg GetNodeSummaryParams) (NodeSummary, error) {
	row := q.queryRow(ctx, q.getNodeSummaryStmt, getNodeSummary, arg.PaperID, arg.NodeID)
	var i NodeSummary
	err := row.Scan(
		&i.PaperID,
		&i.NodeID,
		&i.Title,
		&i.StartPage,
		&i.EndPage,
		&i.Summary,
	)
	return i, err
}

const insertNodeSummary = `-- name: InsertNodeSummary :exec
INSERT INTO node_summaries (
    paper_id, node_id, title, start_page, end_page, summary
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertNodeSummaryParams struct {
	PaperID   sql.NullString `json:"paper_id"`
	NodeID    sql.NullString `json:"node_id"`
	Title     sql.NullString `json:"title"`
	StartPage sql.NullInt64  `json:"start_page"`
	EndPage   sql.NullInt64  `json:"end_page"`
	Summary   string         `json:"summary"`
}

func (q *Queries) InsertNodeSummary(ctx context.Context, arg InsertNodeSummaryParams) error {
	_, err := q.exec(ctx, q.insertNodeSummaryStmt, insertNodeSummary,
		arg.PaperID,
		arg.NodeID,
		arg.Title,
		arg.StartPage,
		arg.EndPage,
		arg.Summary,
	)
	return err
}

const searchNodeSummaries = `-- name: SearchNodeSummaries :many
SELECT paper_id, node_id, title, start_page, end_page, summary FROM node_summaries
WHERE summary LIKE '%' || ? || '%'
ORDER BY paper_id, node_id
LIMIT ?
`

type SearchNodeSummariesParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int64          `json:"limit"`
}

func (q *Queries) SearchNodeSummaries(ctx context.Context, arg SearchNodeSummariesParams) ([]NodeSummary, error) {
	rows, err := q.query(ctx, q.searchNodeSummariesStmt, searchNodeSummaries, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeSummary{}
	for rows.Next() {
		var i NodeSummary
		if err := rows.Scan(
			&i.PaperID,
			&i.NodeID,
			&i.Title,
			&i.StartPage,
			&i.EndPage,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
