// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: papers.sql

package db

import (
	"context"
	"database/sql"
)

const countPapers = `-- name: CountPapers :one
SELECT COUNT(*) FROM papers
`

func (q *Queries) CountPapers(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countPapersStmt, countPapers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePaper = `-- name: DeletePaper :exec
DELETE FROM papers WHERE paper_id = ?
`

func (q *Queries) DeletePaper(ctx context.Context, paperID string) error {
	_, err := q.exec(ctx, q.deletePaperStmt, deletePaper, paperID)
	return err
}

const getPaper = `-- name: GetPaper :one
SELECT paper_id, title, authors, year, venue, abstract, doi, arxiv_id, pdf_path, indexed_at, file_path, doc_type FROM papers WHERE paper_id = ?
`

func (q *Queries) GetPaper(ctx context.Context, paperID string) (Paper, error) {
	row := q.queryRow(ctx, q.getPaperStmt, getPaper, paperID)
	var i Paper
	err := row.Scan(
		&i.PaperID,
		&i.Title,
		&i.Authors,
		&i.Year,
		&i.Venue,
		&i.Abstract,
		&i.Doi,
		&i.ArxivID,
		&i.PdfPath,
		&i.IndexedAt,
		&i.FilePath,
		&i.DocType,
	)
	return i, err
}

const getPaperByArxivID = `-- name: GetPaperByArxivID :one
SELECT paper_id, title, authors, year, venue, abstract, doi, arxiv_id, pdf_path, indexed_at, file_path, doc_type FROM papers WHERE arxiv_id = ? LIMIT 1
`

func (q *Queries) GetPaperByArxivID(ctx context.Context, arxivID sql.NullString) (Paper, error) {
	row := q.queryRow(ctx, q.getPaperByArxivIDStmt, getPaperByArxivID, arxivID)
	var i Paper
	err := row.Scan(
		&i.PaperID,
		&i.Title,
		&i.Authors,
		&i.Year,
		&i.Venue,
		&i.Abstract,
		&i.Doi,
		&i.ArxivID,
		&i.PdfPath,
		&i.IndexedAt,
		&i.FilePath,
		&i.DocType,
	)
	return i, err
}

const getPaperByDOI = `-- name: GetPaperByDOI :one
SELECT paper_id, title, authors, year, venue, abstract, doi, arxiv_id, pdf_path, indexed_at, file_path, doc_type FROM papers WHERE doi = ? LIMIT 1
`

func (q *Queries) GetPaperByDOI(ctx context.Context, doi sql.NullString) (Paper, error) {
	row := q.queryRow(ctx, q.getPaperByDOIStmt, getPaperByDOI, doi)
	var i Paper
	err := row.Scan(
		&i.PaperID,
		&i.Title,
		&i.Authors,
		&i.Year,
		&i.Venue,
		&i.Abstract,
		&i.Doi,
		&i.ArxivID,
		&i.PdfPath,
		&i.IndexedAt,
		&i.FilePath,
		&i.DocType,
	)
	return i, err
}

const getPaperByFilePath = `-- name: GetPaperByFilePath :one
SELECT paper_id, title, authors, year, venue, abstract, doi, arxiv_id, pdf_path, indexed_at, file_path, doc_type FROM papers WHERE file_path = ? LIMIT 1
`

func (q *Queries) GetPaperByFilePath(ctx context.Context, filePath sql.NullString) (Paper, error) {
	row := q.queryRow(ctx, q.getPaperByFilePathStmt, getPaperByFilePath, filePath)
	var i Paper
	err := row.Scan(
		&i.PaperID,
		&i.Title,
		&i.Authors,
		&i.Year,
		&i.Venue,
		&i.Abstract,
		&i.Doi,
		&i.ArxivID,
		&i.PdfPath,
		&i.IndexedAt,
		&i.FilePath,
		&i.DocType,
	)
	return i, err
}

const insertPaper = `-- name: InsertPaper :exec
INSERT INTO papers (
    paper_id, title, authors, year, venue, abstract, doi, arxiv_id, pdf_path, indexed_at, file_path, doc_type
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPaperParams struct {
	PaperID   string         `json:"paper_id"`
	Title     string         `json:"title"`
	Authors   sql.NullString `json:"authors"`
	Year      sql.NullInt64  `json:"year"`
	Venue     sql.NullString `json:"venue"`
	Abstract  sql.NullString `json:"abstract"`
	Doi       sql.NullString `json:"doi"`
	ArxivID   sql.NullString `json:"arxiv_id"`
	PdfPath   sql.NullString `json:"pdf_path"`
	IndexedAt sql.NullInt64  `json:"indexed_at"`
	FilePath  sql.NullString `json:"file_path"`
	DocType   sql.NullString `json:"doc_type"`
}

func (q *Queries) InsertPaper(ctx context.Context, arg InsertPaperParams) error {
	_, err := q.exec(ctx, q.insertPaperStmt, insertPaper,
		arg.PaperID,
		arg.Title,
		arg.Authors,
		arg.Year,
		arg.Venue,
		arg.Abstract,
		arg.Doi,
		arg.ArxivID,
		arg.PdfPath,
		arg.IndexedAt,
		arg.FilePath,
		arg.DocType,
	)
	return err
}

const listPapers = `-- name: ListPapers :many
SELECT paper_id, title, authors, year, venue, abstract, doi, arxiv_id, pdf_path, indexed_at, file_path, doc_type FROM papers ORDER BY indexed_at DESC LIMIT ? OFFSET ?
`

type ListPapersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListPapers(ctx context.Context, arg ListPapersParams) ([]Paper, error) {
	rows, err := q.query(ctx, q.listPapersStmt, listPapers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Paper{}
	for rows.Next() {
		var i Paper
		if err := rows.Scan(
			&i.PaperID,
			&i.Title,
			&i.Authors,
			&i.Year,
			&i.Venue,
			&i.Abstract,
			&i.Doi,
			&i.ArxivID,
			&i.PdfPath,
			&i.IndexedAt,
			&i.FilePath,
			&i.DocType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPapersWithIndexStateAndTask = `-- name: ListPapersWithIndexStateAndTask :many
SELECT
    p.paper_id,
    p.title,
    p.authors,
    p.year,
    p.venue,
    p.abstract,
    p.doi,
    p.arxiv_id,
    p.pdf_path,
    p.indexed_at,
    p.file_path,
    p.doc_type,
    pis.index_level,
    pis.raw_parse_status,
    pis.content_available,
    pis.content_bytes,
    pis.flat_page_index_available,
    pis.fts_status,
    pis.semantic_tree_status,
    pis.semantic_tree_available,
    pis.semantic_tree_error,
    pis.semantic_tree_task_id,
    pis.extractor,
    pis.fallback_reason,
    pis.total_pages,
    pis.total_tokens,
    pis.source_file_available,
    pis.file_hash,
    pis.updated_at AS state_updated_at,
    COALESCE(
        (SELECT task_id FROM kb_tasks kt WHERE kt.paper_id = p.paper_id AND kt.status IN ('queued', 'running') ORDER BY kt.updated_at DESC, kt.created_at DESC LIMIT 1),
        (SELECT task_id FROM kb_tasks kt WHERE kt.paper_id = p.paper_id ORDER BY kt.updated_at DESC, kt.created_at DESC LIMIT 1)
    ) AS task_id,
    COALESCE(
        (SELECT task_type FROM kb_tasks kt WHERE kt.paper_id = p.paper_id AND kt.status IN ('queued', 'running') ORDER BY kt.updated_at DESC, kt.created_at DESC LIMIT 1),
        (SELECT task_type FROM kb_tasks kt WHERE kt.paper_id = p.paper_id ORDER BY kt.updated_at DESC, kt.created_at DESC LIMIT 1)
    ) AS task_type,
    COALESCE(
        (SELECT status FROM kb_tasks kt WHERE kt.paper_id = p.paper_id AND kt.status IN ('queued', 'running') ORDER BY kt.updated_at DESC, kt.created_at DESC LIMIT 1),
        (SELECT status FROM kb_tasks kt WHERE kt.paper_id = p.paper_id ORDER BY kt.updated_at DESC, kt.created_at DESC LIMIT 1)
    ) AS task_status,
    COALESCE(
        (SELECT progress FROM kb_tasks kt WHERE kt.paper_id = p.paper_id AND kt.status IN ('queued', 'running') ORDER BY kt.updated_at DESC, kt.created_at DESC LIMIT 1),
        (SELECT progress FROM kb_tasks kt WHERE kt.paper_id = p.paper_id ORDER BY kt.updated_at DESC, kt.created_at DESC LIMIT 1)
    ) AS task_progress,
    COALESCE(
        (SELECT error FROM kb_tasks kt WHERE kt.paper_id = p.paper_id AND kt.status IN ('queued', 'running') ORDER BY kt.updated_at DESC, kt.created_at DESC LIMIT 1),
        (SELECT error FROM kb_tasks kt WHERE kt.paper_id = p.paper_id ORDER BY kt.updated_at DESC, kt.created_at DESC LIMIT 1)
    ) AS task_error,
    COALESCE(
        (SELECT updated_at FROM kb_tasks kt WHERE kt.paper_id = p.paper_id AND kt.status IN ('queued', 'running') ORDER BY kt.updated_at DESC, kt.created_at DESC LIMIT 1),
        (SELECT updated_at FROM kb_tasks kt WHERE kt.paper_id = p.paper_id ORDER BY kt.updated_at DESC, kt.created_at DESC LIMIT 1)
    ) AS task_updated_at
FROM papers p
LEFT JOIN paper_index_states pis ON pis.paper_id = p.paper_id
ORDER BY p.indexed_at DESC
LIMIT ? OFFSET ?
`

type ListPapersWithIndexStateAndTaskParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListPapersWithIndexStateAndTaskRow struct {
	PaperID                string         `json:"paper_id"`
	Title                  string         `json:"title"`
	Authors                sql.NullString `json:"authors"`
	Year                   sql.NullInt64  `json:"year"`
	Venue                  sql.NullString `json:"venue"`
	Abstract               sql.NullString `json:"abstract"`
	Doi                    sql.NullString `json:"doi"`
	ArxivID                sql.NullString `json:"arxiv_id"`
	PdfPath                sql.NullString `json:"pdf_path"`
	IndexedAt              sql.NullInt64  `json:"indexed_at"`
	FilePath               sql.NullString `json:"file_path"`
	DocType                sql.NullString `json:"doc_type"`
	IndexLevel             sql.NullString `json:"index_level"`
	RawParseStatus         sql.NullString `json:"raw_parse_status"`
	ContentAvailable       sql.NullInt64  `json:"content_available"`
	ContentBytes           sql.NullInt64  `json:"content_bytes"`
	FlatPageIndexAvailable sql.NullInt64  `json:"flat_page_index_available"`
	FtsStatus              sql.NullString `json:"fts_status"`
	SemanticTreeStatus     sql.NullString `json:"semantic_tree_status"`
	SemanticTreeAvailable  sql.NullInt64  `json:"semantic_tree_available"`
	SemanticTreeError      sql.NullString `json:"semantic_tree_error"`
	SemanticTreeTaskID     sql.NullString `json:"semantic_tree_task_id"`
	Extractor              sql.NullString `json:"extractor"`
	FallbackReason         sql.NullString `json:"fallback_reason"`
	TotalPages             sql.NullInt64  `json:"total_pages"`
	TotalTokens            sql.NullInt64  `json:"total_tokens"`
	SourceFileAvailable    sql.NullInt64  `json:"source_file_available"`
	FileHash               sql.NullString `json:"file_hash"`
	StateUpdatedAt         sql.NullInt64  `json:"state_updated_at"`
	TaskID                 interface{}    `json:"task_id"`
	TaskType               interface{}    `json:"task_type"`
	TaskStatus             interface{}    `json:"task_status"`
	TaskProgress           interface{}    `json:"task_progress"`
	TaskError              interface{}    `json:"task_error"`
	TaskUpdatedAt          interface{}    `json:"task_updated_at"`
}

func (q *Queries) ListPapersWithIndexStateAndTask(ctx context.Context, arg ListPapersWithIndexStateAndTaskParams) ([]ListPapersWithIndexStateAndTaskRow, error) {
	rows, err := q.query(ctx, q.listPapersWithIndexStateAndTaskStmt, listPapersWithIndexStateAndTask, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPapersWithIndexStateAndTaskRow{}
	for rows.Next() {
		var i ListPapersWithIndexStateAndTaskRow
		if err := rows.Scan(
			&i.PaperID,
			&i.Title,
			&i.Authors,
			&i.Year,
			&i.Venue,
			&i.Abstract,
			&i.Doi,
			&i.ArxivID,
			&i.PdfPath,
			&i.IndexedAt,
			&i.FilePath,
			&i.DocType,
			&i.IndexLevel,
			&i.RawParseStatus,
			&i.ContentAvailable,
			&i.ContentBytes,
			&i.FlatPageIndexAvailable,
			&i.FtsStatus,
			&i.SemanticTreeStatus,
			&i.SemanticTreeAvailable,
			&i.SemanticTreeError,
			&i.SemanticTreeTaskID,
			&i.Extractor,
			&i.FallbackReason,
			&i.TotalPages,
			&i.TotalTokens,
			&i.SourceFileAvailable,
			&i.FileHash,
			&i.StateUpdatedAt,
			&i.TaskID,
			&i.TaskType,
			&i.TaskStatus,
			&i.TaskProgress,
			&i.TaskError,
			&i.TaskUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPapersByTitle = `-- name: SearchPapersByTitle :many
SELECT paper_id, title, authors, year, venue, abstract, doi, arxiv_id, pdf_path, indexed_at, file_path, doc_type FROM papers
WHERE title LIKE '%' || ? || '%'
ORDER BY year DESC
LIMIT ?
`

type SearchPapersByTitleParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int64          `json:"limit"`
}

func (q *Queries) SearchPapersByTitle(ctx context.Context, arg SearchPapersByTitleParams) ([]Paper, error) {
	rows, err := q.query(ctx, q.searchPapersByTitleStmt, searchPapersByTitle, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Paper{}
	for rows.Next() {
		var i Paper
		if err := rows.Scan(
			&i.PaperID,
			&i.Title,
			&i.Authors,
			&i.Year,
			&i.Venue,
			&i.Abstract,
			&i.Doi,
			&i.ArxivID,
			&i.PdfPath,
			&i.IndexedAt,
			&i.FilePath,
			&i.DocType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
