// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: paper_trees.sql

package db

import (
	"context"
	"database/sql"
)

const deletePaperTree = `-- name: DeletePaperTree :exec
DELETE FROM paper_trees WHERE paper_id = ?
`

func (q *Queries) DeletePaperTree(ctx context.Context, paperID string) error {
	_, err := q.exec(ctx, q.deletePaperTreeStmt, deletePaperTree, paperID)
	return err
}

const getPaperTree = `-- name: GetPaperTree :one
SELECT paper_id, tree_json, doc_description, total_pages, total_tokens, model_used, version, created_at, index_metadata FROM paper_trees WHERE paper_id = ?
`

func (q *Queries) GetPaperTree(ctx context.Context, paperID string) (PaperTree, error) {
	row := q.queryRow(ctx, q.getPaperTreeStmt, getPaperTree, paperID)
	var i PaperTree
	err := row.Scan(
		&i.PaperID,
		&i.TreeJson,
		&i.DocDescription,
		&i.TotalPages,
		&i.TotalTokens,
		&i.ModelUsed,
		&i.Version,
		&i.CreatedAt,
		&i.IndexMetadata,
	)
	return i, err
}

const insertPaperTree = `-- name: InsertPaperTree :exec
INSERT INTO paper_trees (
    paper_id, tree_json, doc_description, total_pages, total_tokens, model_used, version, created_at, index_metadata
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPaperTreeParams struct {
	PaperID        string         `json:"paper_id"`
	TreeJson       string         `json:"tree_json"`
	DocDescription sql.NullString `json:"doc_description"`
	TotalPages     sql.NullInt64  `json:"total_pages"`
	TotalTokens    sql.NullInt64  `json:"total_tokens"`
	ModelUsed      sql.NullString `json:"model_used"`
	Version        sql.NullInt64  `json:"version"`
	CreatedAt      sql.NullInt64  `json:"created_at"`
	IndexMetadata  string         `json:"index_metadata"`
}

func (q *Queries) InsertPaperTree(ctx context.Context, arg InsertPaperTreeParams) error {
	_, err := q.exec(ctx, q.insertPaperTreeStmt, insertPaperTree,
		arg.PaperID,
		arg.TreeJson,
		arg.DocDescription,
		arg.TotalPages,
		arg.TotalTokens,
		arg.ModelUsed,
		arg.Version,
		arg.CreatedAt,
		arg.IndexMetadata,
	)
	return err
}

const updatePaperTreeVersion = `-- name: UpdatePaperTreeVersion :exec
UPDATE paper_trees
SET tree_json = ?, doc_description = ?, version = version + 1
WHERE paper_id = ?
`

type UpdatePaperTreeVersionParams struct {
	TreeJson       string         `json:"tree_json"`
	DocDescription sql.NullString `json:"doc_description"`
	PaperID        string         `json:"paper_id"`
}

func (q *Queries) UpdatePaperTreeVersion(ctx context.Context, arg UpdatePaperTreeVersionParams) error {
	_, err := q.exec(ctx, q.updatePaperTreeVersionStmt, updatePaperTreeVersion, arg.TreeJson, arg.DocDescription, arg.PaperID)
	return err
}
