// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: paper_chunks.sql

package db

import (
	"context"
	"database/sql"
)

const batchInsertPaperChunks = `-- name: BatchInsertPaperChunks :exec
INSERT INTO paper_chunks (
    paper_id,
    chunk_id,
    kind,
    page_start,
    page_end,
    title,
    content,
    token_count,
    source,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type BatchInsertPaperChunksParams struct {
	PaperID    string         `json:"paper_id"`
	ChunkID    string         `json:"chunk_id"`
	Kind       string         `json:"kind"`
	PageStart  sql.NullInt64  `json:"page_start"`
	PageEnd    sql.NullInt64  `json:"page_end"`
	Title      sql.NullString `json:"title"`
	Content    string         `json:"content"`
	TokenCount sql.NullInt64  `json:"token_count"`
	Source     sql.NullString `json:"source"`
	CreatedAt  int64          `json:"created_at"`
}

func (q *Queries) BatchInsertPaperChunks(ctx context.Context, arg BatchInsertPaperChunksParams) error {
	_, err := q.exec(ctx, q.batchInsertPaperChunksStmt, batchInsertPaperChunks,
		arg.PaperID,
		arg.ChunkID,
		arg.Kind,
		arg.PageStart,
		arg.PageEnd,
		arg.Title,
		arg.Content,
		arg.TokenCount,
		arg.Source,
		arg.CreatedAt,
	)
	return err
}

const clearPaperChunksFTS = `-- name: ClearPaperChunksFTS :exec
DELETE FROM paper_chunks_fts
`

func (q *Queries) ClearPaperChunksFTS(ctx context.Context) error {
	_, err := q.exec(ctx, q.clearPaperChunksFTSStmt, clearPaperChunksFTS)
	return err
}

const countPaperChunks = `-- name: CountPaperChunks :one
SELECT COUNT(*) FROM paper_chunks
WHERE paper_id = ?
`

func (q *Queries) CountPaperChunks(ctx context.Context, paperID string) (int64, error) {
	row := q.queryRow(ctx, q.countPaperChunksStmt, countPaperChunks, paperID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePaperChunks = `-- name: DeletePaperChunks :exec
DELETE FROM paper_chunks WHERE paper_id = ?
`

func (q *Queries) DeletePaperChunks(ctx context.Context, paperID string) error {
	_, err := q.exec(ctx, q.deletePaperChunksStmt, deletePaperChunks, paperID)
	return err
}

const deletePaperChunksFTSForPaper = `-- name: DeletePaperChunksFTSForPaper :exec
DELETE FROM paper_chunks_fts
WHERE paper_id = ?1
`

func (q *Queries) DeletePaperChunksFTSForPaper(ctx context.Context, targetPaperID string) error {
	_, err := q.exec(ctx, q.deletePaperChunksFTSForPaperStmt, deletePaperChunksFTSForPaper, targetPaperID)
	return err
}

const getPaperChunk = `-- name: GetPaperChunk :one
SELECT paper_id, chunk_id, kind, page_start, page_end, title, content, token_count, source, created_at FROM paper_chunks
WHERE paper_id = ? AND chunk_id = ?
`

type GetPaperChunkParams struct {
	PaperID string `json:"paper_id"`
	ChunkID string `json:"chunk_id"`
}

func (q *Queries) GetPaperChunk(ctx context.Context, arg GetPaperChunkParams) (PaperChunk, error) {
	row := q.queryRow(ctx, q.getPaperChunkStmt, getPaperChunk, arg.PaperID, arg.ChunkID)
	var i PaperChunk
	err := row.Scan(
		&i.PaperID,
		&i.ChunkID,
		&i.Kind,
		&i.PageStart,
		&i.PageEnd,
		&i.Title,
		&i.Content,
		&i.TokenCount,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const getPaperChunks = `-- name: GetPaperChunks :many
SELECT paper_id, chunk_id, kind, page_start, page_end, title, content, token_count, source, created_at FROM paper_chunks
WHERE paper_id = ?
ORDER BY COALESCE(page_start, 2147483647), chunk_id
`

func (q *Queries) GetPaperChunks(ctx context.Context, paperID string) ([]PaperChunk, error) {
	rows, err := q.query(ctx, q.getPaperChunksStmt, getPaperChunks, paperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaperChunk{}
	for rows.Next() {
		var i PaperChunk
		if err := rows.Scan(
			&i.PaperID,
			&i.ChunkID,
			&i.Kind,
			&i.PageStart,
			&i.PageEnd,
			&i.Title,
			&i.Content,
			&i.TokenCount,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPaperChunk = `-- name: InsertPaperChunk :exec
INSERT INTO paper_chunks (
    paper_id,
    chunk_id,
    kind,
    page_start,
    page_end,
    title,
    content,
    token_count,
    source,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPaperChunkParams struct {
	PaperID    string         `json:"paper_id"`
	ChunkID    string         `json:"chunk_id"`
	Kind       string         `json:"kind"`
	PageStart  sql.NullInt64  `json:"page_start"`
	PageEnd    sql.NullInt64  `json:"page_end"`
	Title      sql.NullString `json:"title"`
	Content    string         `json:"content"`
	TokenCount sql.NullInt64  `json:"token_count"`
	Source     sql.NullString `json:"source"`
	CreatedAt  int64          `json:"created_at"`
}

func (q *Queries) InsertPaperChunk(ctx context.Context, arg InsertPaperChunkParams) error {
	_, err := q.exec(ctx, q.insertPaperChunkStmt, insertPaperChunk,
		arg.PaperID,
		arg.ChunkID,
		arg.Kind,
		arg.PageStart,
		arg.PageEnd,
		arg.Title,
		arg.Content,
		arg.TokenCount,
		arg.Source,
		arg.CreatedAt,
	)
	return err
}

const rebuildPaperChunksFTS = `-- name: RebuildPaperChunksFTS :exec
INSERT OR REPLACE INTO paper_chunks_fts(rowid, paper_id, chunk_id, kind, page_start, page_end, title, content)
SELECT
    pc.rowid,
    COALESCE(pc.paper_id, ''),
    COALESCE(pc.chunk_id, ''),
    COALESCE(pc.kind, ''),
    COALESCE(pc.page_start, 0),
    COALESCE(pc.page_end, 0),
    COALESCE(pc.title, ''),
    COALESCE(pc.content, '')
FROM paper_chunks pc
`

func (q *Queries) RebuildPaperChunksFTS(ctx context.Context) error {
	_, err := q.exec(ctx, q.rebuildPaperChunksFTSStmt, rebuildPaperChunksFTS)
	return err
}

const rebuildPaperChunksFTSForPaper = `-- name: RebuildPaperChunksFTSForPaper :exec
INSERT OR REPLACE INTO paper_chunks_fts(rowid, paper_id, chunk_id, kind, page_start, page_end, title, content)
SELECT
    pc.rowid,
    COALESCE(pc.paper_id, ''),
    COALESCE(pc.chunk_id, ''),
    COALESCE(pc.kind, ''),
    COALESCE(pc.page_start, 0),
    COALESCE(pc.page_end, 0),
    COALESCE(pc.title, ''),
    COALESCE(pc.content, '')
FROM paper_chunks pc
WHERE pc.paper_id = ?1
`

func (q *Queries) RebuildPaperChunksFTSForPaper(ctx context.Context, targetPaperID string) error {
	_, err := q.exec(ctx, q.rebuildPaperChunksFTSForPaperStmt, rebuildPaperChunksFTSForPaper, targetPaperID)
	return err
}

const searchAllPaperChunks = `-- name: SearchAllPaperChunks :many
SELECT
    pc.paper_id,
    pc.chunk_id,
    pc.kind,
    pc.page_start,
    pc.page_end,
    pc.title,
    pc.content,
    pc.token_count,
    pc.source,
    pc.created_at
FROM paper_chunks_fts
JOIN paper_chunks pc ON pc.rowid = paper_chunks_fts.rowid
WHERE paper_chunks_fts.content MATCH ?1
ORDER BY bm25(paper_chunks_fts), pc.paper_id, COALESCE(pc.page_start, 2147483647), pc.chunk_id
LIMIT ?2
`

type SearchAllPaperChunksParams struct {
	Query string `json:"query"`
	Limit int64  `json:"limit"`
}

func (q *Queries) SearchAllPaperChunks(ctx context.Context, arg SearchAllPaperChunksParams) ([]PaperChunk, error) {
	rows, err := q.query(ctx, q.searchAllPaperChunksStmt, searchAllPaperChunks, arg.Query, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaperChunk{}
	for rows.Next() {
		var i PaperChunk
		if err := rows.Scan(
			&i.PaperID,
			&i.ChunkID,
			&i.Kind,
			&i.PageStart,
			&i.PageEnd,
			&i.Title,
			&i.Content,
			&i.TokenCount,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPaperChunks = `-- name: SearchPaperChunks :many
SELECT
    pc.paper_id,
    pc.chunk_id,
    pc.kind,
    pc.page_start,
    pc.page_end,
    pc.title,
    pc.content,
    pc.token_count,
    pc.source,
    pc.created_at
FROM paper_chunks_fts
JOIN paper_chunks pc ON pc.rowid = paper_chunks_fts.rowid
WHERE paper_chunks_fts.paper_id = ?1
  AND paper_chunks_fts.content MATCH ?2
ORDER BY bm25(paper_chunks_fts), COALESCE(pc.page_start, 2147483647), pc.chunk_id
LIMIT ?3
`

type SearchPaperChunksParams struct {
	PaperID string `json:"paper_id"`
	Query   string `json:"query"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) SearchPaperChunks(ctx context.Context, arg SearchPaperChunksParams) ([]PaperChunk, error) {
	rows, err := q.query(ctx, q.searchPaperChunksStmt, searchPaperChunks, arg.PaperID, arg.Query, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaperChunk{}
	for rows.Next() {
		var i PaperChunk
		if err := rows.Scan(
			&i.PaperID,
			&i.ChunkID,
			&i.Kind,
			&i.PageStart,
			&i.PageEnd,
			&i.Title,
			&i.Content,
			&i.TokenCount,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumPaperChunkBytes = `-- name: SumPaperChunkBytes :one
SELECT CAST(COALESCE(SUM(LENGTH(COALESCE(content, ''))), 0) AS INTEGER) FROM paper_chunks
WHERE paper_id = ?
`

func (q *Queries) SumPaperChunkBytes(ctx context.Context, paperID string) (int64, error) {
	row := q.queryRow(ctx, q.sumPaperChunkBytesStmt, sumPaperChunkBytes, paperID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
