// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: paper_index_states.sql

package db

import (
	"context"
	"database/sql"
)

const countPaperIndexStatesByStatus = `-- name: CountPaperIndexStatesByStatus :one
SELECT COUNT(*) FROM paper_index_states
WHERE raw_parse_status = ?1
  AND fts_status = ?2
  AND semantic_tree_status = ?3
`

type CountPaperIndexStatesByStatusParams struct {
	RawParseStatus     sql.NullString `json:"raw_parse_status"`
	FtsStatus          sql.NullString `json:"fts_status"`
	SemanticTreeStatus sql.NullString `json:"semantic_tree_status"`
}

func (q *Queries) CountPaperIndexStatesByStatus(ctx context.Context, arg CountPaperIndexStatesByStatusParams) (int64, error) {
	row := q.queryRow(ctx, q.countPaperIndexStatesByStatusStmt, countPaperIndexStatesByStatus, arg.RawParseStatus, arg.FtsStatus, arg.SemanticTreeStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPaperIndexState = `-- name: GetPaperIndexState :one
SELECT paper_id, index_level, raw_parse_status, content_available, content_bytes, flat_page_index_available, fts_status, semantic_tree_status, semantic_tree_available, semantic_tree_error, semantic_tree_task_id, extractor, fallback_reason, total_pages, total_tokens, source_file_available, file_hash, updated_at FROM paper_index_states
WHERE paper_id = ?
`

func (q *Queries) GetPaperIndexState(ctx context.Context, paperID string) (PaperIndexState, error) {
	row := q.queryRow(ctx, q.getPaperIndexStateStmt, getPaperIndexState, paperID)
	var i PaperIndexState
	err := row.Scan(
		&i.PaperID,
		&i.IndexLevel,
		&i.RawParseStatus,
		&i.ContentAvailable,
		&i.ContentBytes,
		&i.FlatPageIndexAvailable,
		&i.FtsStatus,
		&i.SemanticTreeStatus,
		&i.SemanticTreeAvailable,
		&i.SemanticTreeError,
		&i.SemanticTreeTaskID,
		&i.Extractor,
		&i.FallbackReason,
		&i.TotalPages,
		&i.TotalTokens,
		&i.SourceFileAvailable,
		&i.FileHash,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaperIndexStates = `-- name: ListPaperIndexStates :many
SELECT paper_id, index_level, raw_parse_status, content_available, content_bytes, flat_page_index_available, fts_status, semantic_tree_status, semantic_tree_available, semantic_tree_error, semantic_tree_task_id, extractor, fallback_reason, total_pages, total_tokens, source_file_available, file_hash, updated_at FROM paper_index_states
ORDER BY updated_at DESC, paper_id
LIMIT ? OFFSET ?
`

type ListPaperIndexStatesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListPaperIndexStates(ctx context.Context, arg ListPaperIndexStatesParams) ([]PaperIndexState, error) {
	rows, err := q.query(ctx, q.listPaperIndexStatesStmt, listPaperIndexStates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaperIndexState{}
	for rows.Next() {
		var i PaperIndexState
		if err := rows.Scan(
			&i.PaperID,
			&i.IndexLevel,
			&i.RawParseStatus,
			&i.ContentAvailable,
			&i.ContentBytes,
			&i.FlatPageIndexAvailable,
			&i.FtsStatus,
			&i.SemanticTreeStatus,
			&i.SemanticTreeAvailable,
			&i.SemanticTreeError,
			&i.SemanticTreeTaskID,
			&i.Extractor,
			&i.FallbackReason,
			&i.TotalPages,
			&i.TotalTokens,
			&i.SourceFileAvailable,
			&i.FileHash,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFTSState = `-- name: UpdateFTSState :exec
UPDATE paper_index_states
SET
    fts_status = ?1,
    updated_at = ?2
WHERE paper_id = ?3
`

type UpdateFTSStateParams struct {
	FtsStatus sql.NullString `json:"fts_status"`
	UpdatedAt int64          `json:"updated_at"`
	PaperID   string         `json:"paper_id"`
}

func (q *Queries) UpdateFTSState(ctx context.Context, arg UpdateFTSStateParams) error {
	_, err := q.exec(ctx, q.updateFTSStateStmt, updateFTSState, arg.FtsStatus, arg.UpdatedAt, arg.PaperID)
	return err
}

const updateRawParseState = `-- name: UpdateRawParseState :exec
UPDATE paper_index_states
SET
    raw_parse_status = ?1,
    index_level = ?2,
    content_available = ?3,
    content_bytes = ?4,
    extractor = ?5,
    fallback_reason = ?6,
    total_pages = ?7,
    total_tokens = ?8,
    updated_at = ?9
WHERE paper_id = ?10
`

type UpdateRawParseStateParams struct {
	RawParseStatus   sql.NullString `json:"raw_parse_status"`
	IndexLevel       sql.NullString `json:"index_level"`
	ContentAvailable int64          `json:"content_available"`
	ContentBytes     int64          `json:"content_bytes"`
	Extractor        sql.NullString `json:"extractor"`
	FallbackReason   sql.NullString `json:"fallback_reason"`
	TotalPages       sql.NullInt64  `json:"total_pages"`
	TotalTokens      sql.NullInt64  `json:"total_tokens"`
	UpdatedAt        int64          `json:"updated_at"`
	PaperID          string         `json:"paper_id"`
}

func (q *Queries) UpdateRawParseState(ctx context.Context, arg UpdateRawParseStateParams) error {
	_, err := q.exec(ctx, q.updateRawParseStateStmt, updateRawParseState,
		arg.RawParseStatus,
		arg.IndexLevel,
		arg.ContentAvailable,
		arg.ContentBytes,
		arg.Extractor,
		arg.FallbackReason,
		arg.TotalPages,
		arg.TotalTokens,
		arg.UpdatedAt,
		arg.PaperID,
	)
	return err
}

const updateSemanticTreeState = `-- name: UpdateSemanticTreeState :exec
UPDATE paper_index_states
SET
    semantic_tree_status = ?1,
    semantic_tree_available = ?2,
    semantic_tree_error = ?3,
    semantic_tree_task_id = ?4,
    updated_at = ?5
WHERE paper_id = ?6
`

type UpdateSemanticTreeStateParams struct {
	SemanticTreeStatus    sql.NullString `json:"semantic_tree_status"`
	SemanticTreeAvailable int64          `json:"semantic_tree_available"`
	SemanticTreeError     sql.NullString `json:"semantic_tree_error"`
	SemanticTreeTaskID    sql.NullString `json:"semantic_tree_task_id"`
	UpdatedAt             int64          `json:"updated_at"`
	PaperID               string         `json:"paper_id"`
}

func (q *Queries) UpdateSemanticTreeState(ctx context.Context, arg UpdateSemanticTreeStateParams) error {
	_, err := q.exec(ctx, q.updateSemanticTreeStateStmt, updateSemanticTreeState,
		arg.SemanticTreeStatus,
		arg.SemanticTreeAvailable,
		arg.SemanticTreeError,
		arg.SemanticTreeTaskID,
		arg.UpdatedAt,
		arg.PaperID,
	)
	return err
}

const upsertPaperIndexState = `-- name: UpsertPaperIndexState :exec
INSERT INTO paper_index_states (
    paper_id,
    index_level,
    raw_parse_status,
    content_available,
    content_bytes,
    flat_page_index_available,
    fts_status,
    semantic_tree_status,
    semantic_tree_available,
    semantic_tree_error,
    semantic_tree_task_id,
    extractor,
    fallback_reason,
    total_pages,
    total_tokens,
    source_file_available,
    file_hash,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(paper_id) DO UPDATE SET
    index_level = excluded.index_level,
    raw_parse_status = excluded.raw_parse_status,
    content_available = excluded.content_available,
    content_bytes = excluded.content_bytes,
    flat_page_index_available = excluded.flat_page_index_available,
    fts_status = excluded.fts_status,
    semantic_tree_status = excluded.semantic_tree_status,
    semantic_tree_available = excluded.semantic_tree_available,
    semantic_tree_error = excluded.semantic_tree_error,
    semantic_tree_task_id = excluded.semantic_tree_task_id,
    extractor = excluded.extractor,
    fallback_reason = excluded.fallback_reason,
    total_pages = excluded.total_pages,
    total_tokens = excluded.total_tokens,
    source_file_available = excluded.source_file_available,
    file_hash = excluded.file_hash,
    updated_at = excluded.updated_at
`

type UpsertPaperIndexStateParams struct {
	PaperID                string         `json:"paper_id"`
	IndexLevel             sql.NullString `json:"index_level"`
	RawParseStatus         sql.NullString `json:"raw_parse_status"`
	ContentAvailable       int64          `json:"content_available"`
	ContentBytes           int64          `json:"content_bytes"`
	FlatPageIndexAvailable int64          `json:"flat_page_index_available"`
	FtsStatus              sql.NullString `json:"fts_status"`
	SemanticTreeStatus     sql.NullString `json:"semantic_tree_status"`
	SemanticTreeAvailable  int64          `json:"semantic_tree_available"`
	SemanticTreeError      sql.NullString `json:"semantic_tree_error"`
	SemanticTreeTaskID     sql.NullString `json:"semantic_tree_task_id"`
	Extractor              sql.NullString `json:"extractor"`
	FallbackReason         sql.NullString `json:"fallback_reason"`
	TotalPages             sql.NullInt64  `json:"total_pages"`
	TotalTokens            sql.NullInt64  `json:"total_tokens"`
	SourceFileAvailable    sql.NullInt64  `json:"source_file_available"`
	FileHash               sql.NullString `json:"file_hash"`
	UpdatedAt              int64          `json:"updated_at"`
}

func (q *Queries) UpsertPaperIndexState(ctx context.Context, arg UpsertPaperIndexStateParams) error {
	_, err := q.exec(ctx, q.upsertPaperIndexStateStmt, upsertPaperIndexState,
		arg.PaperID,
		arg.IndexLevel,
		arg.RawParseStatus,
		arg.ContentAvailable,
		arg.ContentBytes,
		arg.FlatPageIndexAvailable,
		arg.FtsStatus,
		arg.SemanticTreeStatus,
		arg.SemanticTreeAvailable,
		arg.SemanticTreeError,
		arg.SemanticTreeTaskID,
		arg.Extractor,
		arg.FallbackReason,
		arg.TotalPages,
		arg.TotalTokens,
		arg.SourceFileAvailable,
		arg.FileHash,
		arg.UpdatedAt,
	)
	return err
}
