// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package db

import (
	"context"
)

const createPermissionRule = `-- name: CreatePermissionRule :one
INSERT INTO permission_rules (id, tool_name, action, path, decision, scope)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, tool_name, "action", path, decision, scope, created_at
`

type CreatePermissionRuleParams struct {
	ID       string `json:"id"`
	ToolName string `json:"tool_name"`
	Action   string `json:"action"`
	Path     string `json:"path"`
	Decision string `json:"decision"`
	Scope    string `json:"scope"`
}

func (q *Queries) CreatePermissionRule(ctx context.Context, arg CreatePermissionRuleParams) (PermissionRule, error) {
	row := q.queryRow(ctx, q.createPermissionRuleStmt, createPermissionRule,
		arg.ID,
		arg.ToolName,
		arg.Action,
		arg.Path,
		arg.Decision,
		arg.Scope,
	)
	var i PermissionRule
	err := row.Scan(
		&i.ID,
		&i.ToolName,
		&i.Action,
		&i.Path,
		&i.Decision,
		&i.Scope,
		&i.CreatedAt,
	)
	return i, err
}

const deletePermissionRule = `-- name: DeletePermissionRule :exec
DELETE FROM permission_rules WHERE id = ?
`

func (q *Queries) DeletePermissionRule(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deletePermissionRuleStmt, deletePermissionRule, id)
	return err
}

const deleteSessionPermissions = `-- name: DeleteSessionPermissions :exec
DELETE FROM permission_rules WHERE scope = 'session'
`

func (q *Queries) DeleteSessionPermissions(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteSessionPermissionsStmt, deleteSessionPermissions)
	return err
}

const getPermissionRule = `-- name: GetPermissionRule :one
SELECT id, tool_name, "action", path, decision, scope, created_at FROM permission_rules
WHERE tool_name = ? AND action = ? AND path = ? AND scope = 'always'
LIMIT 1
`

type GetPermissionRuleParams struct {
	ToolName string `json:"tool_name"`
	Action   string `json:"action"`
	Path     string `json:"path"`
}

func (q *Queries) GetPermissionRule(ctx context.Context, arg GetPermissionRuleParams) (PermissionRule, error) {
	row := q.queryRow(ctx, q.getPermissionRuleStmt, getPermissionRule, arg.ToolName, arg.Action, arg.Path)
	var i PermissionRule
	err := row.Scan(
		&i.ID,
		&i.ToolName,
		&i.Action,
		&i.Path,
		&i.Decision,
		&i.Scope,
		&i.CreatedAt,
	)
	return i, err
}

const listPermissionRules = `-- name: ListPermissionRules :many
SELECT id, tool_name, "action", path, decision, scope, created_at FROM permission_rules
WHERE scope = 'always'
ORDER BY created_at DESC
`

func (q *Queries) ListPermissionRules(ctx context.Context) ([]PermissionRule, error) {
	rows, err := q.query(ctx, q.listPermissionRulesStmt, listPermissionRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionRule{}
	for rows.Next() {
		var i PermissionRule
		if err := rows.Scan(
			&i.ID,
			&i.ToolName,
			&i.Action,
			&i.Path,
			&i.Decision,
			&i.Scope,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
