// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	BackfillMessageSearchText(ctx context.Context, arg BackfillMessageSearchTextParams) error
	BatchInsertPaperChunks(ctx context.Context, arg BatchInsertPaperChunksParams) error
	CancelKBTask(ctx context.Context, arg CancelKBTaskParams) error
	ClaimPendingKBTask(ctx context.Context, arg ClaimPendingKBTaskParams) (KbTask, error)
	ClaimPendingKBTaskByType(ctx context.Context, arg ClaimPendingKBTaskByTypeParams) (KbTask, error)
	ClearPaperChunksFTS(ctx context.Context) error
	CompleteKBTask(ctx context.Context, arg CompleteKBTaskParams) error
	CountBatchJobsByStatus(ctx context.Context) ([]CountBatchJobsByStatusRow, error)
	CountKBUsageStats(ctx context.Context) (int64, error)
	CountNodeContents(ctx context.Context, paperID string) (int64, error)
	CountNodeSummaries(ctx context.Context) (int64, error)
	CountPaperChunks(ctx context.Context, paperID string) (int64, error)
	CountPaperIndexStatesByStatus(ctx context.Context, arg CountPaperIndexStatesByStatusParams) (int64, error)
	CountPapers(ctx context.Context) (int64, error)
	CreateBibEntry(ctx context.Context, arg CreateBibEntryParams) error
	CreateDocxDiagnostic(ctx context.Context, arg CreateDocxDiagnosticParams) error
	CreateDocxDocument(ctx context.Context, arg CreateDocxDocumentParams) (DocxDocument, error)
	CreateDocxExport(ctx context.Context, arg CreateDocxExportParams) (DocxExport, error)
	CreateDocxMaterial(ctx context.Context, arg CreateDocxMaterialParams) (DocxMaterial, error)
	CreateDocxVersion(ctx context.Context, arg CreateDocxVersionParams) (DocxVersion, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreatePermissionRule(ctx context.Context, arg CreatePermissionRuleParams) (PermissionRule, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteBibEntriesBySession(ctx context.Context, sessionID string) error
	DeleteBibEntry(ctx context.Context, id string) error
	DeleteDocxDiagnosticsByDocument(ctx context.Context, documentID int64) error
	DeleteFile(ctx context.Context, id string) error
	DeleteMemoryItem(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteNodeContents(ctx context.Context, paperID string) error
	DeleteNodeSummaries(ctx context.Context, paperID sql.NullString) error
	DeletePaper(ctx context.Context, paperID string) error
	DeletePaperChunks(ctx context.Context, paperID string) error
	DeletePaperChunksFTSForPaper(ctx context.Context, targetPaperID string) error
	DeletePaperTree(ctx context.Context, paperID string) error
	DeletePermissionRule(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	DeleteSessionPermissions(ctx context.Context) error
	EnqueueKBTask(ctx context.Context, arg EnqueueKBTaskParams) (KbTask, error)
	FailKBTask(ctx context.Context, arg FailKBTaskParams) error
	ForceRequeueKBTask(ctx context.Context, arg ForceRequeueKBTaskParams) (KbTask, error)
	GetBatchJob(ctx context.Context, id string) (BatchJob, error)
	GetBibEntry(ctx context.Context, id string) (BibEntry, error)
	GetBibEntryByCiteKey(ctx context.Context, arg GetBibEntryByCiteKeyParams) (BibEntry, error)
	GetBibEntryByDOI(ctx context.Context, arg GetBibEntryByDOIParams) (BibEntry, error)
	GetDocxDocument(ctx context.Context, id int64) (DocxDocument, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPath(ctx context.Context, arg GetFileByPathParams) (File, error)
	GetKBTask(ctx context.Context, taskID string) (KbTask, error)
	GetMemoryItem(ctx context.Context, id string) (MemoryItem, error)
	GetMemorySkillStats(ctx context.Context) ([]MemorySkillStat, error)
	GetMessage(ctx context.Context, id string) (GetMessageRow, error)
	GetNodeContent(ctx context.Context, arg GetNodeContentParams) (NodeContent, error)
	GetNodeContents(ctx context.Context, paperID string) ([]NodeContent, error)
	GetNodeSummaries(ctx context.Context, paperID sql.NullString) ([]NodeSummary, error)
	GetNodeSummary(ctx context.Context, arg GetNodeSummaryParams) (NodeSummary, error)
	GetPaper(ctx context.Context, paperID string) (Paper, error)
	GetPaperByArxivID(ctx context.Context, arxivID sql.NullString) (Paper, error)
	GetPaperByDOI(ctx context.Context, doi sql.NullString) (Paper, error)
	GetPaperByFilePath(ctx context.Context, filePath sql.NullString) (Paper, error)
	GetPaperChunk(ctx context.Context, arg GetPaperChunkParams) (PaperChunk, error)
	GetPaperChunks(ctx context.Context, paperID string) ([]PaperChunk, error)
	GetPaperIndexState(ctx context.Context, paperID string) (PaperIndexState, error)
	GetPaperRelations(ctx context.Context, arg GetPaperRelationsParams) ([]PaperRelation, error)
	GetPaperTree(ctx context.Context, paperID string) (PaperTree, error)
	GetPermissionRule(ctx context.Context, arg GetPermissionRuleParams) (PermissionRule, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetTopAccessedPapers(ctx context.Context, limit int64) ([]GetTopAccessedPapersRow, error)
	IncrementBatchJobAttempt(ctx context.Context, id string) error
	IncrementMemoryAccessCount(ctx context.Context, id string) error
	InsertBatchJob(ctx context.Context, arg InsertBatchJobParams) error
	InsertKBTask(ctx context.Context, arg InsertKBTaskParams) error
	InsertMemoryItem(ctx context.Context, arg InsertMemoryItemParams) error
	InsertNodeContent(ctx context.Context, arg InsertNodeContentParams) error
	InsertNodeSummary(ctx context.Context, arg InsertNodeSummaryParams) error
	InsertPaper(ctx context.Context, arg InsertPaperParams) error
	InsertPaperChunk(ctx context.Context, arg InsertPaperChunkParams) error
	InsertPaperTree(ctx context.Context, arg InsertPaperTreeParams) error
	InsertResearchTopic(ctx context.Context, arg InsertResearchTopicParams) error
	InsertUsageStat(ctx context.Context, arg InsertUsageStatParams) error
	ListBibEntriesBySession(ctx context.Context, sessionID string) ([]BibEntry, error)
	ListDocxDiagnostics(ctx context.Context, documentID int64) ([]DocxDiagnostic, error)
	ListDocxDocumentsByPipeline(ctx context.Context, pipelineID sql.NullInt64) ([]DocxDocument, error)
	ListDocxExports(ctx context.Context, documentID int64) ([]DocxExport, error)
	ListDocxMaterials(ctx context.Context, documentID int64) ([]DocxMaterial, error)
	ListDocxVersions(ctx context.Context, documentID int64) ([]DocxVersion, error)
	ListFailedBatchJobs(ctx context.Context, limit int64) ([]BatchJob, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListGlobalMemoryItems(ctx context.Context, limit int64) ([]MemoryItem, error)
	ListKBTasksByPaper(ctx context.Context, arg ListKBTasksByPaperParams) ([]KbTask, error)
	ListMemoryItemsForSession(ctx context.Context, arg ListMemoryItemsForSessionParams) ([]MemoryItem, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]ListMessagesBySessionRow, error)
	ListMessagesMissingSearchText(ctx context.Context, limit int64) ([]ListMessagesMissingSearchTextRow, error)
	ListMessagesMissingSearchTextForResumeSearch(ctx context.Context, arg ListMessagesMissingSearchTextForResumeSearchParams) ([]ListMessagesMissingSearchTextForResumeSearchRow, error)
	ListPaperIndexStates(ctx context.Context, arg ListPaperIndexStatesParams) ([]PaperIndexState, error)
	ListPapers(ctx context.Context, arg ListPapersParams) ([]Paper, error)
	ListPapersWithIndexStateAndTask(ctx context.Context, arg ListPapersWithIndexStateAndTaskParams) ([]ListPapersWithIndexStateAndTaskRow, error)
	ListPendingBatchJobs(ctx context.Context, limit int64) ([]BatchJob, error)
	ListPendingKBTasks(ctx context.Context, limit int64) ([]KbTask, error)
	ListPermissionRules(ctx context.Context) ([]PermissionRule, error)
	ListRecentMemoryItems(ctx context.Context, limit int64) ([]MemoryItem, error)
	ListResearchTopics(ctx context.Context, limit int64) ([]ResearchTopic, error)
	ListSessionMemoryItems(ctx context.Context, arg ListSessionMemoryItemsParams) ([]MemoryItem, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListSessionsForResume(ctx context.Context, arg ListSessionsForResumeParams) ([]Session, error)
	RebuildPaperChunksFTS(ctx context.Context) error
	RebuildPaperChunksFTSForPaper(ctx context.Context, targetPaperID string) error
	ResetBatchJobForRetry(ctx context.Context, id string) error
	ResetFailedBatchJobs(ctx context.Context, updatedAt int64) error
	ResolveSessionByExactTitle(ctx context.Context, arg ResolveSessionByExactTitleParams) ([]Session, error)
	RetryKBTask(ctx context.Context, arg RetryKBTaskParams) error
	SearchAllPaperChunks(ctx context.Context, arg SearchAllPaperChunksParams) ([]PaperChunk, error)
	SearchBibEntriesByTitle(ctx context.Context, arg SearchBibEntriesByTitleParams) ([]BibEntry, error)
	SearchNodeContents(ctx context.Context, arg SearchNodeContentsParams) ([]SearchNodeContentsRow, error)
	SearchNodeSummaries(ctx context.Context, arg SearchNodeSummariesParams) ([]NodeSummary, error)
	SearchPaperChunks(ctx context.Context, arg SearchPaperChunksParams) ([]PaperChunk, error)
	SearchPapersByTitle(ctx context.Context, arg SearchPapersByTitleParams) ([]Paper, error)
	SearchRootSessionsByMessageFTS(ctx context.Context, arg SearchRootSessionsByMessageFTSParams) ([]string, error)
	SearchSessionsByMetadata(ctx context.Context, arg SearchSessionsByMetadataParams) ([]Session, error)
	SumPaperChunkBytes(ctx context.Context, paperID string) (int64, error)
	UpdateBatchJobStatus(ctx context.Context, arg UpdateBatchJobStatusParams) error
	UpdateDocxDocumentState(ctx context.Context, arg UpdateDocxDocumentStateParams) error
	UpdateDocxMaterialParsed(ctx context.Context, arg UpdateDocxMaterialParsedParams) error
	UpdateFTSState(ctx context.Context, arg UpdateFTSStateParams) error
	UpdateKBTaskProgress(ctx context.Context, arg UpdateKBTaskProgressParams) error
	UpdateMemoryItem(ctx context.Context, arg UpdateMemoryItemParams) error
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdatePaperTreeVersion(ctx context.Context, arg UpdatePaperTreeVersionParams) error
	UpdateRawParseState(ctx context.Context, arg UpdateRawParseStateParams) error
	UpdateSemanticTreeState(ctx context.Context, arg UpdateSemanticTreeStateParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpsertMemorySkillStat(ctx context.Context, arg UpsertMemorySkillStatParams) error
	UpsertPaperIndexState(ctx context.Context, arg UpsertPaperIndexStateParams) error
	UpsertPaperRelation(ctx context.Context, arg UpsertPaperRelationParams) error
}

var _ Querier = (*Queries)(nil)
