// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    parent_session_id,
    title,
    message_count,
    prompt_tokens,
    completion_tokens,
    cost,
    summary,
    tags,
    first_prompt,
    git_branch,
    project_path,
    worktree_path,
    mode,
    root_session_id,
    forked_from_session_id,
    summary_message_id,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    null,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, summary_message_id, updated_at, created_at, summary, tags, first_prompt, git_branch, project_path, worktree_path, mode, root_session_id, forked_from_session_id
`

type CreateSessionParams struct {
	ID                  string         `json:"id"`
	ParentSessionID     sql.NullString `json:"parent_session_id"`
	Title               string         `json:"title"`
	MessageCount        int64          `json:"message_count"`
	PromptTokens        int64          `json:"prompt_tokens"`
	CompletionTokens    int64          `json:"completion_tokens"`
	Cost                float64        `json:"cost"`
	Summary             sql.NullString `json:"summary"`
	Tags                sql.NullString `json:"tags"`
	FirstPrompt         sql.NullString `json:"first_prompt"`
	GitBranch           sql.NullString `json:"git_branch"`
	ProjectPath         string         `json:"project_path"`
	WorktreePath        string         `json:"worktree_path"`
	Mode                string         `json:"mode"`
	RootSessionID       string         `json:"root_session_id"`
	ForkedFromSessionID string         `json:"forked_from_session_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.createSessionStmt, createSession,
		arg.ID,
		arg.ParentSessionID,
		arg.Title,
		arg.MessageCount,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.Summary,
		arg.Tags,
		arg.FirstPrompt,
		arg.GitBranch,
		arg.ProjectPath,
		arg.WorktreePath,
		arg.Mode,
		arg.RootSessionID,
		arg.ForkedFromSessionID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.SummaryMessageID,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Summary,
		&i.Tags,
		&i.FirstPrompt,
		&i.GitBranch,
		&i.ProjectPath,
		&i.WorktreePath,
		&i.Mode,
		&i.RootSessionID,
		&i.ForkedFromSessionID,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, id)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, summary_message_id, updated_at, created_at, summary, tags, first_prompt, git_branch, project_path, worktree_path, mode, root_session_id, forked_from_session_id
FROM sessions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.queryRow(ctx, q.getSessionByIDStmt, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.SummaryMessageID,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Summary,
		&i.Tags,
		&i.FirstPrompt,
		&i.GitBranch,
		&i.ProjectPath,
		&i.WorktreePath,
		&i.Mode,
		&i.RootSessionID,
		&i.ForkedFromSessionID,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, summary_message_id, updated_at, created_at, summary, tags, first_prompt, git_branch, project_path, worktree_path, mode, root_session_id, forked_from_session_id
FROM sessions
WHERE parent_session_id is NULL
ORDER BY created_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.query(ctx, q.listSessionsStmt, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.SummaryMessageID,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Summary,
			&i.Tags,
			&i.FirstPrompt,
			&i.GitBranch,
			&i.ProjectPath,
			&i.WorktreePath,
			&i.Mode,
			&i.RootSessionID,
			&i.ForkedFromSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForResume = `-- name: ListSessionsForResume :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, summary_message_id, updated_at, created_at, summary, tags, first_prompt, git_branch, project_path, worktree_path, mode, root_session_id, forked_from_session_id
FROM sessions
WHERE parent_session_id IS NULL
  AND message_count > 0
  AND (?1 = '' OR project_path = '' OR project_path = ?1)
ORDER BY updated_at DESC
LIMIT ?2
`

type ListSessionsForResumeParams struct {
	ProjectPath interface{} `json:"project_path"`
	Limit       int64       `json:"limit"`
}

func (q *Queries) ListSessionsForResume(ctx context.Context, arg ListSessionsForResumeParams) ([]Session, error) {
	rows, err := q.query(ctx, q.listSessionsForResumeStmt, listSessionsForResume, arg.ProjectPath, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.SummaryMessageID,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Summary,
			&i.Tags,
			&i.FirstPrompt,
			&i.GitBranch,
			&i.ProjectPath,
			&i.WorktreePath,
			&i.Mode,
			&i.RootSessionID,
			&i.ForkedFromSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveSessionByExactTitle = `-- name: ResolveSessionByExactTitle :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, summary_message_id, updated_at, created_at, summary, tags, first_prompt, git_branch, project_path, worktree_path, mode, root_session_id, forked_from_session_id
FROM sessions
WHERE parent_session_id IS NULL
  AND title = ?1
  AND (?2 = '' OR project_path = '' OR project_path = ?2)
ORDER BY updated_at DESC
LIMIT ?3
`

type ResolveSessionByExactTitleParams struct {
	Title       string      `json:"title"`
	ProjectPath interface{} `json:"project_path"`
	Limit       int64       `json:"limit"`
}

func (q *Queries) ResolveSessionByExactTitle(ctx context.Context, arg ResolveSessionByExactTitleParams) ([]Session, error) {
	rows, err := q.query(ctx, q.resolveSessionByExactTitleStmt, resolveSessionByExactTitle, arg.Title, arg.ProjectPath, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.SummaryMessageID,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Summary,
			&i.Tags,
			&i.FirstPrompt,
			&i.GitBranch,
			&i.ProjectPath,
			&i.WorktreePath,
			&i.Mode,
			&i.RootSessionID,
			&i.ForkedFromSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSessionsByMetadata = `-- name: SearchSessionsByMetadata :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, summary_message_id, updated_at, created_at, summary, tags, first_prompt, git_branch, project_path, worktree_path, mode, root_session_id, forked_from_session_id
FROM sessions
WHERE parent_session_id IS NULL
  AND (?1 = '' OR project_path = '' OR project_path = ?1)
  AND (
      instr(lower(title), lower(?2)) > 0
      OR instr(lower(summary), lower(?2)) > 0
      OR instr(lower(first_prompt), lower(?2)) > 0
      OR instr(lower(tags), lower(?2)) > 0
      OR instr(lower(git_branch), lower(?2)) > 0
  )
ORDER BY updated_at DESC
LIMIT ?3
`

type SearchSessionsByMetadataParams struct {
	ProjectPath interface{} `json:"project_path"`
	Query       string      `json:"query"`
	Limit       int64       `json:"limit"`
}

func (q *Queries) SearchSessionsByMetadata(ctx context.Context, arg SearchSessionsByMetadataParams) ([]Session, error) {
	rows, err := q.query(ctx, q.searchSessionsByMetadataStmt, searchSessionsByMetadata, arg.ProjectPath, arg.Query, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.SummaryMessageID,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Summary,
			&i.Tags,
			&i.FirstPrompt,
			&i.GitBranch,
			&i.ProjectPath,
			&i.WorktreePath,
			&i.Mode,
			&i.RootSessionID,
			&i.ForkedFromSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET
    title = ?,
    prompt_tokens = ?,
    completion_tokens = ?,
    summary_message_id = ?,
    cost = ?,
    summary = ?,
    tags = ?,
    first_prompt = ?,
    git_branch = ?,
    project_path = ?,
    worktree_path = ?,
    mode = ?,
    root_session_id = ?,
    forked_from_session_id = ?
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, summary_message_id, updated_at, created_at, summary, tags, first_prompt, git_branch, project_path, worktree_path, mode, root_session_id, forked_from_session_id
`

type UpdateSessionParams struct {
	Title               string         `json:"title"`
	PromptTokens        int64          `json:"prompt_tokens"`
	CompletionTokens    int64          `json:"completion_tokens"`
	SummaryMessageID    sql.NullString `json:"summary_message_id"`
	Cost                float64        `json:"cost"`
	Summary             sql.NullString `json:"summary"`
	Tags                sql.NullString `json:"tags"`
	FirstPrompt         sql.NullString `json:"first_prompt"`
	GitBranch           sql.NullString `json:"git_branch"`
	ProjectPath         string         `json:"project_path"`
	WorktreePath        string         `json:"worktree_path"`
	Mode                string         `json:"mode"`
	RootSessionID       string         `json:"root_session_id"`
	ForkedFromSessionID string         `json:"forked_from_session_id"`
	ID                  string         `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.updateSessionStmt, updateSession,
		arg.Title,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.SummaryMessageID,
		arg.Cost,
		arg.Summary,
		arg.Tags,
		arg.FirstPrompt,
		arg.GitBranch,
		arg.ProjectPath,
		arg.WorktreePath,
		arg.Mode,
		arg.RootSessionID,
		arg.ForkedFromSessionID,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.SummaryMessageID,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Summary,
		&i.Tags,
		&i.FirstPrompt,
		&i.GitBranch,
		&i.ProjectPath,
		&i.WorktreePath,
		&i.Mode,
		&i.RootSessionID,
		&i.ForkedFromSessionID,
	)
	return i, err
}
